include_guard(GLOBAL)

function(cod_add_test)
    foreach(required_keyword TARGET CASES LABELS)
        list(FIND ARGN "${required_keyword}" keyword_index)
        if(keyword_index EQUAL -1)
            message(FATAL_ERROR "cod_add_test requires explicit ${required_keyword}")
        endif()
    endforeach()

    cmake_parse_arguments(PARSE_ARGV 0 COD "" "TARGET" "CASES;LABELS")
    if(COD_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "invalid cod_add_test arguments: ${ARGN}")
    endif()
    if(NOT COD_TARGET OR NOT COD_LABELS)
        message(FATAL_ERROR "cod_add_test requires non-empty TARGET and LABELS")
    endif()

    if(COD_CASES)
        foreach(case_name IN LISTS COD_CASES)
            set(test_name "${COD_TARGET}.${case_name}")
            add_test(NAME "${test_name}" COMMAND "${COD_TARGET}" "${case_name}")
            set_tests_properties("${test_name}" PROPERTIES LABELS "${COD_LABELS}")
        endforeach()
    else()
        add_test(NAME "${COD_TARGET}" COMMAND "${COD_TARGET}")
        set_tests_properties("${COD_TARGET}" PROPERTIES LABELS "${COD_LABELS}")
    endif()
endfunction()
