/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BOARD_BACKEND_CONTRACT_H
#define _MOCK_BOARD_BACKEND_CONTRACT_H

#include "unity.h"
#include "board_backend_contract.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_board_backend_contract_Init(void);
void mock_board_backend_contract_Destroy(void);
void mock_board_backend_contract_Verify(void);




#define HOST_DWT_CreateCtx_Ignore() TEST_FAIL_MESSAGE("HOST_DWT_CreateCtx requires _IgnoreAndReturn");
#define HOST_DWT_CreateCtx_IgnoreAndReturn(cmock_retval) HOST_DWT_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_DWT_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_DWT_CreateCtx_StopIgnore() HOST_DWT_CreateCtx_CMockStopIgnore()
void HOST_DWT_CreateCtx_CMockStopIgnore(void);
#define HOST_DWT_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("HOST_DWT_CreateCtx requires _ExpectAnyArgsAndReturn");
#define HOST_DWT_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) HOST_DWT_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HOST_DWT_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_DWT_CreateCtx_Expect(cpu_freq_hz) TEST_FAIL_MESSAGE("HOST_DWT_CreateCtx requires _ExpectAndReturn");
#define HOST_DWT_CreateCtx_ExpectAndReturn(cpu_freq_hz, cmock_retval) HOST_DWT_CreateCtx_CMockExpectAndReturn(__LINE__, cpu_freq_hz, cmock_retval)
void HOST_DWT_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cpu_freq_hz, void* cmock_to_return);
typedef void* (* CMOCK_HOST_DWT_CreateCtx_CALLBACK)(uint32_t cpu_freq_hz, int cmock_num_calls);
void HOST_DWT_CreateCtx_AddCallback(CMOCK_HOST_DWT_CreateCtx_CALLBACK Callback);
void HOST_DWT_CreateCtx_Stub(CMOCK_HOST_DWT_CreateCtx_CALLBACK Callback);
#define HOST_DWT_CreateCtx_StubWithCallback HOST_DWT_CreateCtx_Stub
int HOST_DWT_CreateCtx_CallCount(void);
#define HOST_DWT_CreateCtx_IgnoreArg_cpu_freq_hz() HOST_DWT_CreateCtx_CMockIgnoreArg_cpu_freq_hz(__LINE__)
void HOST_DWT_CreateCtx_CMockIgnoreArg_cpu_freq_hz(UNITY_LINE_TYPE cmock_line);
#define HOST_DWT_GetOps_Ignore() TEST_FAIL_MESSAGE("HOST_DWT_GetOps requires _IgnoreAndReturn");
#define HOST_DWT_GetOps_IgnoreAndReturn(cmock_retval) HOST_DWT_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_DWT_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const DWT_Ops_s* cmock_to_return);
#define HOST_DWT_GetOps_StopIgnore() HOST_DWT_GetOps_CMockStopIgnore()
void HOST_DWT_GetOps_CMockStopIgnore(void);
#define HOST_DWT_GetOps_Expect() TEST_FAIL_MESSAGE("HOST_DWT_GetOps requires _ExpectAndReturn");
#define HOST_DWT_GetOps_ExpectAndReturn(cmock_retval) HOST_DWT_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void HOST_DWT_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DWT_Ops_s* cmock_to_return);
typedef const DWT_Ops_s* (* CMOCK_HOST_DWT_GetOps_CALLBACK)(int cmock_num_calls);
void HOST_DWT_GetOps_AddCallback(CMOCK_HOST_DWT_GetOps_CALLBACK Callback);
void HOST_DWT_GetOps_Stub(CMOCK_HOST_DWT_GetOps_CALLBACK Callback);
#define HOST_DWT_GetOps_StubWithCallback HOST_DWT_GetOps_Stub
int HOST_DWT_GetOps_CallCount(void);
#define HOST_DWT_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_DWT_DestroyCtx requires _Ignore (not AndReturn)");
#define HOST_DWT_DestroyCtx_Ignore() HOST_DWT_DestroyCtx_CMockIgnore()
void HOST_DWT_DestroyCtx_CMockIgnore(void);
#define HOST_DWT_DestroyCtx_StopIgnore() HOST_DWT_DestroyCtx_CMockStopIgnore()
void HOST_DWT_DestroyCtx_CMockStopIgnore(void);
#define HOST_DWT_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_DWT_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define HOST_DWT_DestroyCtx_ExpectAnyArgs() HOST_DWT_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void HOST_DWT_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HOST_DWT_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("HOST_DWT_DestroyCtx requires _Expect (not AndReturn)");
#define HOST_DWT_DestroyCtx_Expect(ctx) HOST_DWT_DestroyCtx_CMockExpect(__LINE__, ctx)
void HOST_DWT_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_HOST_DWT_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void HOST_DWT_DestroyCtx_AddCallback(CMOCK_HOST_DWT_DestroyCtx_CALLBACK Callback);
void HOST_DWT_DestroyCtx_Stub(CMOCK_HOST_DWT_DestroyCtx_CALLBACK Callback);
#define HOST_DWT_DestroyCtx_StubWithCallback HOST_DWT_DestroyCtx_Stub
int HOST_DWT_DestroyCtx_CallCount(void);
#define HOST_DWT_DestroyCtx_ReturnThruPtr_ctx(ctx) HOST_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define HOST_DWT_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) HOST_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define HOST_DWT_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) HOST_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void HOST_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define HOST_DWT_DestroyCtx_IgnoreArg_ctx() HOST_DWT_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void HOST_DWT_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define HOST_SPI_CreateCtx_Ignore() TEST_FAIL_MESSAGE("HOST_SPI_CreateCtx requires _IgnoreAndReturn");
#define HOST_SPI_CreateCtx_IgnoreAndReturn(cmock_retval) HOST_SPI_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_SPI_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_SPI_CreateCtx_StopIgnore() HOST_SPI_CreateCtx_CMockStopIgnore()
void HOST_SPI_CreateCtx_CMockStopIgnore(void);
#define HOST_SPI_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("HOST_SPI_CreateCtx requires _ExpectAnyArgsAndReturn");
#define HOST_SPI_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) HOST_SPI_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HOST_SPI_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_SPI_CreateCtx_Expect(hspi, cs_port, cs_pin, mode) TEST_FAIL_MESSAGE("HOST_SPI_CreateCtx requires _ExpectAndReturn");
#define HOST_SPI_CreateCtx_ExpectAndReturn(hspi, cs_port, cs_pin, mode, cmock_retval) HOST_SPI_CreateCtx_CMockExpectAndReturn(__LINE__, hspi, cs_port, cs_pin, mode, cmock_retval)
void HOST_SPI_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, GPIO_TypeDef* cs_port, uint16_t cs_pin, SPI_Xfer_Mode_e mode, void* cmock_to_return);
typedef void* (* CMOCK_HOST_SPI_CreateCtx_CALLBACK)(SPI_HandleTypeDef* hspi, GPIO_TypeDef* cs_port, uint16_t cs_pin, SPI_Xfer_Mode_e mode, int cmock_num_calls);
void HOST_SPI_CreateCtx_AddCallback(CMOCK_HOST_SPI_CreateCtx_CALLBACK Callback);
void HOST_SPI_CreateCtx_Stub(CMOCK_HOST_SPI_CreateCtx_CALLBACK Callback);
#define HOST_SPI_CreateCtx_StubWithCallback HOST_SPI_CreateCtx_Stub
int HOST_SPI_CreateCtx_CallCount(void);
#define HOST_SPI_CreateCtx_ReturnThruPtr_hspi(hspi) HOST_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(__LINE__, hspi, sizeof(SPI_HandleTypeDef))
#define HOST_SPI_CreateCtx_ReturnArrayThruPtr_hspi(hspi, cmock_len) HOST_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(__LINE__, hspi, (cmock_len * sizeof(*hspi)))
#define HOST_SPI_CreateCtx_ReturnMemThruPtr_hspi(hspi, cmock_size) HOST_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(__LINE__, hspi, (cmock_size))
void HOST_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef const* hspi, size_t cmock_size);
#define HOST_SPI_CreateCtx_ReturnThruPtr_cs_port(cs_port) HOST_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(__LINE__, cs_port, sizeof(GPIO_TypeDef))
#define HOST_SPI_CreateCtx_ReturnArrayThruPtr_cs_port(cs_port, cmock_len) HOST_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(__LINE__, cs_port, (cmock_len * sizeof(*cs_port)))
#define HOST_SPI_CreateCtx_ReturnMemThruPtr_cs_port(cs_port, cmock_size) HOST_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(__LINE__, cs_port, (cmock_size))
void HOST_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef const* cs_port, size_t cmock_size);
#define HOST_SPI_CreateCtx_IgnoreArg_hspi() HOST_SPI_CreateCtx_CMockIgnoreArg_hspi(__LINE__)
void HOST_SPI_CreateCtx_CMockIgnoreArg_hspi(UNITY_LINE_TYPE cmock_line);
#define HOST_SPI_CreateCtx_IgnoreArg_cs_port() HOST_SPI_CreateCtx_CMockIgnoreArg_cs_port(__LINE__)
void HOST_SPI_CreateCtx_CMockIgnoreArg_cs_port(UNITY_LINE_TYPE cmock_line);
#define HOST_SPI_CreateCtx_IgnoreArg_cs_pin() HOST_SPI_CreateCtx_CMockIgnoreArg_cs_pin(__LINE__)
void HOST_SPI_CreateCtx_CMockIgnoreArg_cs_pin(UNITY_LINE_TYPE cmock_line);
#define HOST_SPI_CreateCtx_IgnoreArg_mode() HOST_SPI_CreateCtx_CMockIgnoreArg_mode(__LINE__)
void HOST_SPI_CreateCtx_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line);
#define HOST_SPI_GetOps_Ignore() TEST_FAIL_MESSAGE("HOST_SPI_GetOps requires _IgnoreAndReturn");
#define HOST_SPI_GetOps_IgnoreAndReturn(cmock_retval) HOST_SPI_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_SPI_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_Ops_s* cmock_to_return);
#define HOST_SPI_GetOps_StopIgnore() HOST_SPI_GetOps_CMockStopIgnore()
void HOST_SPI_GetOps_CMockStopIgnore(void);
#define HOST_SPI_GetOps_Expect() TEST_FAIL_MESSAGE("HOST_SPI_GetOps requires _ExpectAndReturn");
#define HOST_SPI_GetOps_ExpectAndReturn(cmock_retval) HOST_SPI_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void HOST_SPI_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_Ops_s* cmock_to_return);
typedef const SPI_Ops_s* (* CMOCK_HOST_SPI_GetOps_CALLBACK)(int cmock_num_calls);
void HOST_SPI_GetOps_AddCallback(CMOCK_HOST_SPI_GetOps_CALLBACK Callback);
void HOST_SPI_GetOps_Stub(CMOCK_HOST_SPI_GetOps_CALLBACK Callback);
#define HOST_SPI_GetOps_StubWithCallback HOST_SPI_GetOps_Stub
int HOST_SPI_GetOps_CallCount(void);
#define HOST_SPI_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_SPI_DestroyCtx requires _Ignore (not AndReturn)");
#define HOST_SPI_DestroyCtx_Ignore() HOST_SPI_DestroyCtx_CMockIgnore()
void HOST_SPI_DestroyCtx_CMockIgnore(void);
#define HOST_SPI_DestroyCtx_StopIgnore() HOST_SPI_DestroyCtx_CMockStopIgnore()
void HOST_SPI_DestroyCtx_CMockStopIgnore(void);
#define HOST_SPI_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_SPI_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define HOST_SPI_DestroyCtx_ExpectAnyArgs() HOST_SPI_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void HOST_SPI_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HOST_SPI_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("HOST_SPI_DestroyCtx requires _Expect (not AndReturn)");
#define HOST_SPI_DestroyCtx_Expect(ctx) HOST_SPI_DestroyCtx_CMockExpect(__LINE__, ctx)
void HOST_SPI_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_HOST_SPI_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void HOST_SPI_DestroyCtx_AddCallback(CMOCK_HOST_SPI_DestroyCtx_CALLBACK Callback);
void HOST_SPI_DestroyCtx_Stub(CMOCK_HOST_SPI_DestroyCtx_CALLBACK Callback);
#define HOST_SPI_DestroyCtx_StubWithCallback HOST_SPI_DestroyCtx_Stub
int HOST_SPI_DestroyCtx_CallCount(void);
#define HOST_SPI_DestroyCtx_ReturnThruPtr_ctx(ctx) HOST_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define HOST_SPI_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) HOST_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define HOST_SPI_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) HOST_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void HOST_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define HOST_SPI_DestroyCtx_IgnoreArg_ctx() HOST_SPI_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void HOST_SPI_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define HOST_UART_CreateCtx_Ignore() TEST_FAIL_MESSAGE("HOST_UART_CreateCtx requires _IgnoreAndReturn");
#define HOST_UART_CreateCtx_IgnoreAndReturn(cmock_retval) HOST_UART_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_UART_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_UART_CreateCtx_StopIgnore() HOST_UART_CreateCtx_CMockStopIgnore()
void HOST_UART_CreateCtx_CMockStopIgnore(void);
#define HOST_UART_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("HOST_UART_CreateCtx requires _ExpectAnyArgsAndReturn");
#define HOST_UART_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) HOST_UART_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HOST_UART_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_UART_CreateCtx_Expect(huart, mode) TEST_FAIL_MESSAGE("HOST_UART_CreateCtx requires _ExpectAndReturn");
#define HOST_UART_CreateCtx_ExpectAndReturn(huart, mode, cmock_retval) HOST_UART_CreateCtx_CMockExpectAndReturn(__LINE__, huart, mode, cmock_retval)
void HOST_UART_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, UART_Xfer_Mode_e mode, void* cmock_to_return);
typedef void* (* CMOCK_HOST_UART_CreateCtx_CALLBACK)(UART_HandleTypeDef* huart, UART_Xfer_Mode_e mode, int cmock_num_calls);
void HOST_UART_CreateCtx_AddCallback(CMOCK_HOST_UART_CreateCtx_CALLBACK Callback);
void HOST_UART_CreateCtx_Stub(CMOCK_HOST_UART_CreateCtx_CALLBACK Callback);
#define HOST_UART_CreateCtx_StubWithCallback HOST_UART_CreateCtx_Stub
int HOST_UART_CreateCtx_CallCount(void);
#define HOST_UART_CreateCtx_ReturnThruPtr_huart(huart) HOST_UART_CreateCtx_CMockReturnMemThruPtr_huart(__LINE__, huart, sizeof(UART_HandleTypeDef))
#define HOST_UART_CreateCtx_ReturnArrayThruPtr_huart(huart, cmock_len) HOST_UART_CreateCtx_CMockReturnMemThruPtr_huart(__LINE__, huart, (cmock_len * sizeof(*huart)))
#define HOST_UART_CreateCtx_ReturnMemThruPtr_huart(huart, cmock_size) HOST_UART_CreateCtx_CMockReturnMemThruPtr_huart(__LINE__, huart, (cmock_size))
void HOST_UART_CreateCtx_CMockReturnMemThruPtr_huart(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef const* huart, size_t cmock_size);
#define HOST_UART_CreateCtx_IgnoreArg_huart() HOST_UART_CreateCtx_CMockIgnoreArg_huart(__LINE__)
void HOST_UART_CreateCtx_CMockIgnoreArg_huart(UNITY_LINE_TYPE cmock_line);
#define HOST_UART_CreateCtx_IgnoreArg_mode() HOST_UART_CreateCtx_CMockIgnoreArg_mode(__LINE__)
void HOST_UART_CreateCtx_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line);
#define HOST_UART_GetOps_Ignore() TEST_FAIL_MESSAGE("HOST_UART_GetOps requires _IgnoreAndReturn");
#define HOST_UART_GetOps_IgnoreAndReturn(cmock_retval) HOST_UART_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_UART_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const UART_Ops_s* cmock_to_return);
#define HOST_UART_GetOps_StopIgnore() HOST_UART_GetOps_CMockStopIgnore()
void HOST_UART_GetOps_CMockStopIgnore(void);
#define HOST_UART_GetOps_Expect() TEST_FAIL_MESSAGE("HOST_UART_GetOps requires _ExpectAndReturn");
#define HOST_UART_GetOps_ExpectAndReturn(cmock_retval) HOST_UART_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void HOST_UART_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UART_Ops_s* cmock_to_return);
typedef const UART_Ops_s* (* CMOCK_HOST_UART_GetOps_CALLBACK)(int cmock_num_calls);
void HOST_UART_GetOps_AddCallback(CMOCK_HOST_UART_GetOps_CALLBACK Callback);
void HOST_UART_GetOps_Stub(CMOCK_HOST_UART_GetOps_CALLBACK Callback);
#define HOST_UART_GetOps_StubWithCallback HOST_UART_GetOps_Stub
int HOST_UART_GetOps_CallCount(void);
#define HOST_UART_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_UART_DestroyCtx requires _Ignore (not AndReturn)");
#define HOST_UART_DestroyCtx_Ignore() HOST_UART_DestroyCtx_CMockIgnore()
void HOST_UART_DestroyCtx_CMockIgnore(void);
#define HOST_UART_DestroyCtx_StopIgnore() HOST_UART_DestroyCtx_CMockStopIgnore()
void HOST_UART_DestroyCtx_CMockStopIgnore(void);
#define HOST_UART_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_UART_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define HOST_UART_DestroyCtx_ExpectAnyArgs() HOST_UART_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void HOST_UART_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HOST_UART_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("HOST_UART_DestroyCtx requires _Expect (not AndReturn)");
#define HOST_UART_DestroyCtx_Expect(ctx) HOST_UART_DestroyCtx_CMockExpect(__LINE__, ctx)
void HOST_UART_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_HOST_UART_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void HOST_UART_DestroyCtx_AddCallback(CMOCK_HOST_UART_DestroyCtx_CALLBACK Callback);
void HOST_UART_DestroyCtx_Stub(CMOCK_HOST_UART_DestroyCtx_CALLBACK Callback);
#define HOST_UART_DestroyCtx_StubWithCallback HOST_UART_DestroyCtx_Stub
int HOST_UART_DestroyCtx_CallCount(void);
#define HOST_UART_DestroyCtx_ReturnThruPtr_ctx(ctx) HOST_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define HOST_UART_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) HOST_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define HOST_UART_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) HOST_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void HOST_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define HOST_UART_DestroyCtx_IgnoreArg_ctx() HOST_UART_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void HOST_UART_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define HOST_PWM_CreateCtx_Ignore() TEST_FAIL_MESSAGE("HOST_PWM_CreateCtx requires _IgnoreAndReturn");
#define HOST_PWM_CreateCtx_IgnoreAndReturn(cmock_retval) HOST_PWM_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_PWM_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_PWM_CreateCtx_StopIgnore() HOST_PWM_CreateCtx_CMockStopIgnore()
void HOST_PWM_CreateCtx_CMockStopIgnore(void);
#define HOST_PWM_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("HOST_PWM_CreateCtx requires _ExpectAnyArgsAndReturn");
#define HOST_PWM_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) HOST_PWM_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HOST_PWM_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_PWM_CreateCtx_Expect(htim, channel) TEST_FAIL_MESSAGE("HOST_PWM_CreateCtx requires _ExpectAndReturn");
#define HOST_PWM_CreateCtx_ExpectAndReturn(htim, channel, cmock_retval) HOST_PWM_CreateCtx_CMockExpectAndReturn(__LINE__, htim, channel, cmock_retval)
void HOST_PWM_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TIM_HandleTypeDef* htim, uint32_t channel, void* cmock_to_return);
typedef void* (* CMOCK_HOST_PWM_CreateCtx_CALLBACK)(TIM_HandleTypeDef* htim, uint32_t channel, int cmock_num_calls);
void HOST_PWM_CreateCtx_AddCallback(CMOCK_HOST_PWM_CreateCtx_CALLBACK Callback);
void HOST_PWM_CreateCtx_Stub(CMOCK_HOST_PWM_CreateCtx_CALLBACK Callback);
#define HOST_PWM_CreateCtx_StubWithCallback HOST_PWM_CreateCtx_Stub
int HOST_PWM_CreateCtx_CallCount(void);
#define HOST_PWM_CreateCtx_ReturnThruPtr_htim(htim) HOST_PWM_CreateCtx_CMockReturnMemThruPtr_htim(__LINE__, htim, sizeof(TIM_HandleTypeDef))
#define HOST_PWM_CreateCtx_ReturnArrayThruPtr_htim(htim, cmock_len) HOST_PWM_CreateCtx_CMockReturnMemThruPtr_htim(__LINE__, htim, (cmock_len * sizeof(*htim)))
#define HOST_PWM_CreateCtx_ReturnMemThruPtr_htim(htim, cmock_size) HOST_PWM_CreateCtx_CMockReturnMemThruPtr_htim(__LINE__, htim, (cmock_size))
void HOST_PWM_CreateCtx_CMockReturnMemThruPtr_htim(UNITY_LINE_TYPE cmock_line, TIM_HandleTypeDef const* htim, size_t cmock_size);
#define HOST_PWM_CreateCtx_IgnoreArg_htim() HOST_PWM_CreateCtx_CMockIgnoreArg_htim(__LINE__)
void HOST_PWM_CreateCtx_CMockIgnoreArg_htim(UNITY_LINE_TYPE cmock_line);
#define HOST_PWM_CreateCtx_IgnoreArg_channel() HOST_PWM_CreateCtx_CMockIgnoreArg_channel(__LINE__)
void HOST_PWM_CreateCtx_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line);
#define HOST_PWM_GetOps_Ignore() TEST_FAIL_MESSAGE("HOST_PWM_GetOps requires _IgnoreAndReturn");
#define HOST_PWM_GetOps_IgnoreAndReturn(cmock_retval) HOST_PWM_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_PWM_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const PWM_Ops_s* cmock_to_return);
#define HOST_PWM_GetOps_StopIgnore() HOST_PWM_GetOps_CMockStopIgnore()
void HOST_PWM_GetOps_CMockStopIgnore(void);
#define HOST_PWM_GetOps_Expect() TEST_FAIL_MESSAGE("HOST_PWM_GetOps requires _ExpectAndReturn");
#define HOST_PWM_GetOps_ExpectAndReturn(cmock_retval) HOST_PWM_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void HOST_PWM_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const PWM_Ops_s* cmock_to_return);
typedef const PWM_Ops_s* (* CMOCK_HOST_PWM_GetOps_CALLBACK)(int cmock_num_calls);
void HOST_PWM_GetOps_AddCallback(CMOCK_HOST_PWM_GetOps_CALLBACK Callback);
void HOST_PWM_GetOps_Stub(CMOCK_HOST_PWM_GetOps_CALLBACK Callback);
#define HOST_PWM_GetOps_StubWithCallback HOST_PWM_GetOps_Stub
int HOST_PWM_GetOps_CallCount(void);
#define HOST_PWM_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_PWM_DestroyCtx requires _Ignore (not AndReturn)");
#define HOST_PWM_DestroyCtx_Ignore() HOST_PWM_DestroyCtx_CMockIgnore()
void HOST_PWM_DestroyCtx_CMockIgnore(void);
#define HOST_PWM_DestroyCtx_StopIgnore() HOST_PWM_DestroyCtx_CMockStopIgnore()
void HOST_PWM_DestroyCtx_CMockStopIgnore(void);
#define HOST_PWM_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_PWM_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define HOST_PWM_DestroyCtx_ExpectAnyArgs() HOST_PWM_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void HOST_PWM_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HOST_PWM_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("HOST_PWM_DestroyCtx requires _Expect (not AndReturn)");
#define HOST_PWM_DestroyCtx_Expect(ctx) HOST_PWM_DestroyCtx_CMockExpect(__LINE__, ctx)
void HOST_PWM_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_HOST_PWM_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void HOST_PWM_DestroyCtx_AddCallback(CMOCK_HOST_PWM_DestroyCtx_CALLBACK Callback);
void HOST_PWM_DestroyCtx_Stub(CMOCK_HOST_PWM_DestroyCtx_CALLBACK Callback);
#define HOST_PWM_DestroyCtx_StubWithCallback HOST_PWM_DestroyCtx_Stub
int HOST_PWM_DestroyCtx_CallCount(void);
#define HOST_PWM_DestroyCtx_ReturnThruPtr_ctx(ctx) HOST_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define HOST_PWM_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) HOST_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define HOST_PWM_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) HOST_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void HOST_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define HOST_PWM_DestroyCtx_IgnoreArg_ctx() HOST_PWM_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void HOST_PWM_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define HOST_FLASH_CreateCtx_Ignore() TEST_FAIL_MESSAGE("HOST_FLASH_CreateCtx requires _IgnoreAndReturn");
#define HOST_FLASH_CreateCtx_IgnoreAndReturn(cmock_retval) HOST_FLASH_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_FLASH_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_FLASH_CreateCtx_StopIgnore() HOST_FLASH_CreateCtx_CMockStopIgnore()
void HOST_FLASH_CreateCtx_CMockStopIgnore(void);
#define HOST_FLASH_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("HOST_FLASH_CreateCtx requires _ExpectAnyArgsAndReturn");
#define HOST_FLASH_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) HOST_FLASH_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HOST_FLASH_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_FLASH_CreateCtx_Expect(first_sector, sector_count) TEST_FAIL_MESSAGE("HOST_FLASH_CreateCtx requires _ExpectAndReturn");
#define HOST_FLASH_CreateCtx_ExpectAndReturn(first_sector, sector_count, cmock_retval) HOST_FLASH_CreateCtx_CMockExpectAndReturn(__LINE__, first_sector, sector_count, cmock_retval)
void HOST_FLASH_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t first_sector, uint32_t sector_count, void* cmock_to_return);
typedef void* (* CMOCK_HOST_FLASH_CreateCtx_CALLBACK)(uint32_t first_sector, uint32_t sector_count, int cmock_num_calls);
void HOST_FLASH_CreateCtx_AddCallback(CMOCK_HOST_FLASH_CreateCtx_CALLBACK Callback);
void HOST_FLASH_CreateCtx_Stub(CMOCK_HOST_FLASH_CreateCtx_CALLBACK Callback);
#define HOST_FLASH_CreateCtx_StubWithCallback HOST_FLASH_CreateCtx_Stub
int HOST_FLASH_CreateCtx_CallCount(void);
#define HOST_FLASH_CreateCtx_IgnoreArg_first_sector() HOST_FLASH_CreateCtx_CMockIgnoreArg_first_sector(__LINE__)
void HOST_FLASH_CreateCtx_CMockIgnoreArg_first_sector(UNITY_LINE_TYPE cmock_line);
#define HOST_FLASH_CreateCtx_IgnoreArg_sector_count() HOST_FLASH_CreateCtx_CMockIgnoreArg_sector_count(__LINE__)
void HOST_FLASH_CreateCtx_CMockIgnoreArg_sector_count(UNITY_LINE_TYPE cmock_line);
#define HOST_FLASH_GetOps_Ignore() TEST_FAIL_MESSAGE("HOST_FLASH_GetOps requires _IgnoreAndReturn");
#define HOST_FLASH_GetOps_IgnoreAndReturn(cmock_retval) HOST_FLASH_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_FLASH_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const Flash_Ops_s* cmock_to_return);
#define HOST_FLASH_GetOps_StopIgnore() HOST_FLASH_GetOps_CMockStopIgnore()
void HOST_FLASH_GetOps_CMockStopIgnore(void);
#define HOST_FLASH_GetOps_Expect() TEST_FAIL_MESSAGE("HOST_FLASH_GetOps requires _ExpectAndReturn");
#define HOST_FLASH_GetOps_ExpectAndReturn(cmock_retval) HOST_FLASH_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void HOST_FLASH_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const Flash_Ops_s* cmock_to_return);
typedef const Flash_Ops_s* (* CMOCK_HOST_FLASH_GetOps_CALLBACK)(int cmock_num_calls);
void HOST_FLASH_GetOps_AddCallback(CMOCK_HOST_FLASH_GetOps_CALLBACK Callback);
void HOST_FLASH_GetOps_Stub(CMOCK_HOST_FLASH_GetOps_CALLBACK Callback);
#define HOST_FLASH_GetOps_StubWithCallback HOST_FLASH_GetOps_Stub
int HOST_FLASH_GetOps_CallCount(void);
#define HOST_FLASH_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_FLASH_DestroyCtx requires _Ignore (not AndReturn)");
#define HOST_FLASH_DestroyCtx_Ignore() HOST_FLASH_DestroyCtx_CMockIgnore()
void HOST_FLASH_DestroyCtx_CMockIgnore(void);
#define HOST_FLASH_DestroyCtx_StopIgnore() HOST_FLASH_DestroyCtx_CMockStopIgnore()
void HOST_FLASH_DestroyCtx_CMockStopIgnore(void);
#define HOST_FLASH_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HOST_FLASH_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define HOST_FLASH_DestroyCtx_ExpectAnyArgs() HOST_FLASH_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void HOST_FLASH_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HOST_FLASH_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("HOST_FLASH_DestroyCtx requires _Expect (not AndReturn)");
#define HOST_FLASH_DestroyCtx_Expect(ctx) HOST_FLASH_DestroyCtx_CMockExpect(__LINE__, ctx)
void HOST_FLASH_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_HOST_FLASH_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void HOST_FLASH_DestroyCtx_AddCallback(CMOCK_HOST_FLASH_DestroyCtx_CALLBACK Callback);
void HOST_FLASH_DestroyCtx_Stub(CMOCK_HOST_FLASH_DestroyCtx_CALLBACK Callback);
#define HOST_FLASH_DestroyCtx_StubWithCallback HOST_FLASH_DestroyCtx_Stub
int HOST_FLASH_DestroyCtx_CallCount(void);
#define HOST_FLASH_DestroyCtx_ReturnThruPtr_ctx(ctx) HOST_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define HOST_FLASH_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) HOST_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define HOST_FLASH_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) HOST_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void HOST_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define HOST_FLASH_DestroyCtx_IgnoreArg_ctx() HOST_FLASH_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void HOST_FLASH_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define HOST_CAN_CreateCtx_Ignore() TEST_FAIL_MESSAGE("HOST_CAN_CreateCtx requires _IgnoreAndReturn");
#define HOST_CAN_CreateCtx_IgnoreAndReturn(cmock_retval) HOST_CAN_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_CAN_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_CAN_CreateCtx_StopIgnore() HOST_CAN_CreateCtx_CMockStopIgnore()
void HOST_CAN_CreateCtx_CMockStopIgnore(void);
#define HOST_CAN_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("HOST_CAN_CreateCtx requires _ExpectAnyArgsAndReturn");
#define HOST_CAN_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) HOST_CAN_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HOST_CAN_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define HOST_CAN_CreateCtx_Expect(hfdcan, tx_id, rx_id) TEST_FAIL_MESSAGE("HOST_CAN_CreateCtx requires _ExpectAndReturn");
#define HOST_CAN_CreateCtx_ExpectAndReturn(hfdcan, tx_id, rx_id, cmock_retval) HOST_CAN_CreateCtx_CMockExpectAndReturn(__LINE__, hfdcan, tx_id, rx_id, cmock_retval)
void HOST_CAN_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef* hfdcan, uint32_t tx_id, uint32_t rx_id, void* cmock_to_return);
typedef void* (* CMOCK_HOST_CAN_CreateCtx_CALLBACK)(FDCAN_HandleTypeDef* hfdcan, uint32_t tx_id, uint32_t rx_id, int cmock_num_calls);
void HOST_CAN_CreateCtx_AddCallback(CMOCK_HOST_CAN_CreateCtx_CALLBACK Callback);
void HOST_CAN_CreateCtx_Stub(CMOCK_HOST_CAN_CreateCtx_CALLBACK Callback);
#define HOST_CAN_CreateCtx_StubWithCallback HOST_CAN_CreateCtx_Stub
int HOST_CAN_CreateCtx_CallCount(void);
#define HOST_CAN_CreateCtx_ReturnThruPtr_hfdcan(hfdcan) HOST_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(__LINE__, hfdcan, sizeof(FDCAN_HandleTypeDef))
#define HOST_CAN_CreateCtx_ReturnArrayThruPtr_hfdcan(hfdcan, cmock_len) HOST_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(__LINE__, hfdcan, (cmock_len * sizeof(*hfdcan)))
#define HOST_CAN_CreateCtx_ReturnMemThruPtr_hfdcan(hfdcan, cmock_size) HOST_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(__LINE__, hfdcan, (cmock_size))
void HOST_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef const* hfdcan, size_t cmock_size);
#define HOST_CAN_CreateCtx_IgnoreArg_hfdcan() HOST_CAN_CreateCtx_CMockIgnoreArg_hfdcan(__LINE__)
void HOST_CAN_CreateCtx_CMockIgnoreArg_hfdcan(UNITY_LINE_TYPE cmock_line);
#define HOST_CAN_CreateCtx_IgnoreArg_tx_id() HOST_CAN_CreateCtx_CMockIgnoreArg_tx_id(__LINE__)
void HOST_CAN_CreateCtx_CMockIgnoreArg_tx_id(UNITY_LINE_TYPE cmock_line);
#define HOST_CAN_CreateCtx_IgnoreArg_rx_id() HOST_CAN_CreateCtx_CMockIgnoreArg_rx_id(__LINE__)
void HOST_CAN_CreateCtx_CMockIgnoreArg_rx_id(UNITY_LINE_TYPE cmock_line);
#define HOST_CAN_GetOps_Ignore() TEST_FAIL_MESSAGE("HOST_CAN_GetOps requires _IgnoreAndReturn");
#define HOST_CAN_GetOps_IgnoreAndReturn(cmock_retval) HOST_CAN_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HOST_CAN_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const CAN_Ops_s* cmock_to_return);
#define HOST_CAN_GetOps_StopIgnore() HOST_CAN_GetOps_CMockStopIgnore()
void HOST_CAN_GetOps_CMockStopIgnore(void);
#define HOST_CAN_GetOps_Expect() TEST_FAIL_MESSAGE("HOST_CAN_GetOps requires _ExpectAndReturn");
#define HOST_CAN_GetOps_ExpectAndReturn(cmock_retval) HOST_CAN_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void HOST_CAN_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const CAN_Ops_s* cmock_to_return);
typedef const CAN_Ops_s* (* CMOCK_HOST_CAN_GetOps_CALLBACK)(int cmock_num_calls);
void HOST_CAN_GetOps_AddCallback(CMOCK_HOST_CAN_GetOps_CALLBACK Callback);
void HOST_CAN_GetOps_Stub(CMOCK_HOST_CAN_GetOps_CALLBACK Callback);
#define HOST_CAN_GetOps_StubWithCallback HOST_CAN_GetOps_Stub
int HOST_CAN_GetOps_CallCount(void);
#define PLAT_malloc_Ignore() TEST_FAIL_MESSAGE("PLAT_malloc requires _IgnoreAndReturn");
#define PLAT_malloc_IgnoreAndReturn(cmock_retval) PLAT_malloc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_malloc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define PLAT_malloc_StopIgnore() PLAT_malloc_CMockStopIgnore()
void PLAT_malloc_CMockStopIgnore(void);
#define PLAT_malloc_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_malloc requires _ExpectAnyArgsAndReturn");
#define PLAT_malloc_ExpectAnyArgsAndReturn(cmock_retval) PLAT_malloc_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_malloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define PLAT_malloc_Expect(size) TEST_FAIL_MESSAGE("PLAT_malloc requires _ExpectAndReturn");
#define PLAT_malloc_ExpectAndReturn(size, cmock_retval) PLAT_malloc_CMockExpectAndReturn(__LINE__, size, cmock_retval)
void PLAT_malloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t size, void* cmock_to_return);
typedef void* (* CMOCK_PLAT_malloc_CALLBACK)(size_t size, int cmock_num_calls);
void PLAT_malloc_AddCallback(CMOCK_PLAT_malloc_CALLBACK Callback);
void PLAT_malloc_Stub(CMOCK_PLAT_malloc_CALLBACK Callback);
#define PLAT_malloc_StubWithCallback PLAT_malloc_Stub
int PLAT_malloc_CallCount(void);
#define PLAT_malloc_IgnoreArg_size() PLAT_malloc_CMockIgnoreArg_size(__LINE__)
void PLAT_malloc_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define PLAT_free_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("PLAT_free requires _Ignore (not AndReturn)");
#define PLAT_free_Ignore() PLAT_free_CMockIgnore()
void PLAT_free_CMockIgnore(void);
#define PLAT_free_StopIgnore() PLAT_free_CMockStopIgnore()
void PLAT_free_CMockStopIgnore(void);
#define PLAT_free_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("PLAT_free requires _ExpectAnyArgs (not AndReturn)");
#define PLAT_free_ExpectAnyArgs() PLAT_free_CMockExpectAnyArgs(__LINE__)
void PLAT_free_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PLAT_free_ExpectAndReturn(ptr, cmock_retval) TEST_FAIL_MESSAGE("PLAT_free requires _Expect (not AndReturn)");
#define PLAT_free_Expect(ptr) PLAT_free_CMockExpect(__LINE__, ptr)
void PLAT_free_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ptr);
typedef void (* CMOCK_PLAT_free_CALLBACK)(void* ptr, int cmock_num_calls);
void PLAT_free_AddCallback(CMOCK_PLAT_free_CALLBACK Callback);
void PLAT_free_Stub(CMOCK_PLAT_free_CALLBACK Callback);
#define PLAT_free_StubWithCallback PLAT_free_Stub
int PLAT_free_CallCount(void);
#define PLAT_free_ReturnThruPtr_ptr(ptr) PLAT_free_CMockReturnMemThruPtr_ptr(__LINE__, ptr, sizeof(*ptr))
#define PLAT_free_ReturnArrayThruPtr_ptr(ptr, cmock_len) PLAT_free_CMockReturnMemThruPtr_ptr(__LINE__, ptr, (cmock_len * sizeof(*ptr)))
#define PLAT_free_ReturnMemThruPtr_ptr(ptr, cmock_size) PLAT_free_CMockReturnMemThruPtr_ptr(__LINE__, ptr, (cmock_size))
void PLAT_free_CMockReturnMemThruPtr_ptr(UNITY_LINE_TYPE cmock_line, void const* ptr, size_t cmock_size);
#define PLAT_free_IgnoreArg_ptr() PLAT_free_CMockIgnoreArg_ptr(__LINE__)
void PLAT_free_CMockIgnoreArg_ptr(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
