/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BOARD_DEPS_H
#define _MOCK_BOARD_DEPS_H

#include "unity.h"
#include "board_deps.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_board_deps_Init(void);
void mock_board_deps_Destroy(void);
void mock_board_deps_Verify(void);




#define IMPL_STM32_DWT_CreateCtx_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_DWT_CreateCtx requires _IgnoreAndReturn");
#define IMPL_STM32_DWT_CreateCtx_IgnoreAndReturn(cmock_retval) IMPL_STM32_DWT_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_DWT_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_DWT_CreateCtx_StopIgnore() IMPL_STM32_DWT_CreateCtx_CMockStopIgnore()
void IMPL_STM32_DWT_CreateCtx_CMockStopIgnore(void);
#define IMPL_STM32_DWT_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("IMPL_STM32_DWT_CreateCtx requires _ExpectAnyArgsAndReturn");
#define IMPL_STM32_DWT_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) IMPL_STM32_DWT_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_DWT_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_DWT_CreateCtx_Expect(cpu_freq_hz) TEST_FAIL_MESSAGE("IMPL_STM32_DWT_CreateCtx requires _ExpectAndReturn");
#define IMPL_STM32_DWT_CreateCtx_ExpectAndReturn(cpu_freq_hz, cmock_retval) IMPL_STM32_DWT_CreateCtx_CMockExpectAndReturn(__LINE__, cpu_freq_hz, cmock_retval)
void IMPL_STM32_DWT_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cpu_freq_hz, void* cmock_to_return);
typedef void* (* CMOCK_IMPL_STM32_DWT_CreateCtx_CALLBACK)(uint32_t cpu_freq_hz, int cmock_num_calls);
void IMPL_STM32_DWT_CreateCtx_AddCallback(CMOCK_IMPL_STM32_DWT_CreateCtx_CALLBACK Callback);
void IMPL_STM32_DWT_CreateCtx_Stub(CMOCK_IMPL_STM32_DWT_CreateCtx_CALLBACK Callback);
#define IMPL_STM32_DWT_CreateCtx_StubWithCallback IMPL_STM32_DWT_CreateCtx_Stub
int IMPL_STM32_DWT_CreateCtx_CallCount(void);
#define IMPL_STM32_DWT_CreateCtx_IgnoreArg_cpu_freq_hz() IMPL_STM32_DWT_CreateCtx_CMockIgnoreArg_cpu_freq_hz(__LINE__)
void IMPL_STM32_DWT_CreateCtx_CMockIgnoreArg_cpu_freq_hz(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_DWT_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_DWT_GetOps requires _IgnoreAndReturn");
#define IMPL_STM32_DWT_GetOps_IgnoreAndReturn(cmock_retval) IMPL_STM32_DWT_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_DWT_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const DWT_Ops_s* cmock_to_return);
#define IMPL_STM32_DWT_GetOps_StopIgnore() IMPL_STM32_DWT_GetOps_CMockStopIgnore()
void IMPL_STM32_DWT_GetOps_CMockStopIgnore(void);
#define IMPL_STM32_DWT_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_STM32_DWT_GetOps requires _ExpectAndReturn");
#define IMPL_STM32_DWT_GetOps_ExpectAndReturn(cmock_retval) IMPL_STM32_DWT_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_DWT_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DWT_Ops_s* cmock_to_return);
typedef const DWT_Ops_s* (* CMOCK_IMPL_STM32_DWT_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_STM32_DWT_GetOps_AddCallback(CMOCK_IMPL_STM32_DWT_GetOps_CALLBACK Callback);
void IMPL_STM32_DWT_GetOps_Stub(CMOCK_IMPL_STM32_DWT_GetOps_CALLBACK Callback);
#define IMPL_STM32_DWT_GetOps_StubWithCallback IMPL_STM32_DWT_GetOps_Stub
int IMPL_STM32_DWT_GetOps_CallCount(void);
#define IMPL_STM32_DWT_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_DWT_DestroyCtx requires _Ignore (not AndReturn)");
#define IMPL_STM32_DWT_DestroyCtx_Ignore() IMPL_STM32_DWT_DestroyCtx_CMockIgnore()
void IMPL_STM32_DWT_DestroyCtx_CMockIgnore(void);
#define IMPL_STM32_DWT_DestroyCtx_StopIgnore() IMPL_STM32_DWT_DestroyCtx_CMockStopIgnore()
void IMPL_STM32_DWT_DestroyCtx_CMockStopIgnore(void);
#define IMPL_STM32_DWT_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_DWT_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define IMPL_STM32_DWT_DestroyCtx_ExpectAnyArgs() IMPL_STM32_DWT_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void IMPL_STM32_DWT_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_DWT_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_DWT_DestroyCtx requires _Expect (not AndReturn)");
#define IMPL_STM32_DWT_DestroyCtx_Expect(ctx) IMPL_STM32_DWT_DestroyCtx_CMockExpect(__LINE__, ctx)
void IMPL_STM32_DWT_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_IMPL_STM32_DWT_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void IMPL_STM32_DWT_DestroyCtx_AddCallback(CMOCK_IMPL_STM32_DWT_DestroyCtx_CALLBACK Callback);
void IMPL_STM32_DWT_DestroyCtx_Stub(CMOCK_IMPL_STM32_DWT_DestroyCtx_CALLBACK Callback);
#define IMPL_STM32_DWT_DestroyCtx_StubWithCallback IMPL_STM32_DWT_DestroyCtx_Stub
int IMPL_STM32_DWT_DestroyCtx_CallCount(void);
#define IMPL_STM32_DWT_DestroyCtx_ReturnThruPtr_ctx(ctx) IMPL_STM32_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define IMPL_STM32_DWT_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) IMPL_STM32_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define IMPL_STM32_DWT_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) IMPL_STM32_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void IMPL_STM32_DWT_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define IMPL_STM32_DWT_DestroyCtx_IgnoreArg_ctx() IMPL_STM32_DWT_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void IMPL_STM32_DWT_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_SPI_CreateCtx_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_SPI_CreateCtx requires _IgnoreAndReturn");
#define IMPL_STM32_SPI_CreateCtx_IgnoreAndReturn(cmock_retval) IMPL_STM32_SPI_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_SPI_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_SPI_CreateCtx_StopIgnore() IMPL_STM32_SPI_CreateCtx_CMockStopIgnore()
void IMPL_STM32_SPI_CreateCtx_CMockStopIgnore(void);
#define IMPL_STM32_SPI_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("IMPL_STM32_SPI_CreateCtx requires _ExpectAnyArgsAndReturn");
#define IMPL_STM32_SPI_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) IMPL_STM32_SPI_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_SPI_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_SPI_CreateCtx_Expect(hspi, cs_port, cs_pin, mode) TEST_FAIL_MESSAGE("IMPL_STM32_SPI_CreateCtx requires _ExpectAndReturn");
#define IMPL_STM32_SPI_CreateCtx_ExpectAndReturn(hspi, cs_port, cs_pin, mode, cmock_retval) IMPL_STM32_SPI_CreateCtx_CMockExpectAndReturn(__LINE__, hspi, cs_port, cs_pin, mode, cmock_retval)
void IMPL_STM32_SPI_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, GPIO_TypeDef* cs_port, uint16_t cs_pin, SPI_Xfer_Mode_e mode, void* cmock_to_return);
typedef void* (* CMOCK_IMPL_STM32_SPI_CreateCtx_CALLBACK)(SPI_HandleTypeDef* hspi, GPIO_TypeDef* cs_port, uint16_t cs_pin, SPI_Xfer_Mode_e mode, int cmock_num_calls);
void IMPL_STM32_SPI_CreateCtx_AddCallback(CMOCK_IMPL_STM32_SPI_CreateCtx_CALLBACK Callback);
void IMPL_STM32_SPI_CreateCtx_Stub(CMOCK_IMPL_STM32_SPI_CreateCtx_CALLBACK Callback);
#define IMPL_STM32_SPI_CreateCtx_StubWithCallback IMPL_STM32_SPI_CreateCtx_Stub
int IMPL_STM32_SPI_CreateCtx_CallCount(void);
#define IMPL_STM32_SPI_CreateCtx_ReturnThruPtr_hspi(hspi) IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(__LINE__, hspi, sizeof(SPI_HandleTypeDef))
#define IMPL_STM32_SPI_CreateCtx_ReturnArrayThruPtr_hspi(hspi, cmock_len) IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(__LINE__, hspi, (cmock_len * sizeof(*hspi)))
#define IMPL_STM32_SPI_CreateCtx_ReturnMemThruPtr_hspi(hspi, cmock_size) IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(__LINE__, hspi, (cmock_size))
void IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_hspi(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef const* hspi, size_t cmock_size);
#define IMPL_STM32_SPI_CreateCtx_ReturnThruPtr_cs_port(cs_port) IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(__LINE__, cs_port, sizeof(GPIO_TypeDef))
#define IMPL_STM32_SPI_CreateCtx_ReturnArrayThruPtr_cs_port(cs_port, cmock_len) IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(__LINE__, cs_port, (cmock_len * sizeof(*cs_port)))
#define IMPL_STM32_SPI_CreateCtx_ReturnMemThruPtr_cs_port(cs_port, cmock_size) IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(__LINE__, cs_port, (cmock_size))
void IMPL_STM32_SPI_CreateCtx_CMockReturnMemThruPtr_cs_port(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef const* cs_port, size_t cmock_size);
#define IMPL_STM32_SPI_CreateCtx_IgnoreArg_hspi() IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_hspi(__LINE__)
void IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_hspi(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_SPI_CreateCtx_IgnoreArg_cs_port() IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_cs_port(__LINE__)
void IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_cs_port(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_SPI_CreateCtx_IgnoreArg_cs_pin() IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_cs_pin(__LINE__)
void IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_cs_pin(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_SPI_CreateCtx_IgnoreArg_mode() IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_mode(__LINE__)
void IMPL_STM32_SPI_CreateCtx_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_SPI_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_SPI_GetOps requires _IgnoreAndReturn");
#define IMPL_STM32_SPI_GetOps_IgnoreAndReturn(cmock_retval) IMPL_STM32_SPI_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_SPI_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_Ops_s* cmock_to_return);
#define IMPL_STM32_SPI_GetOps_StopIgnore() IMPL_STM32_SPI_GetOps_CMockStopIgnore()
void IMPL_STM32_SPI_GetOps_CMockStopIgnore(void);
#define IMPL_STM32_SPI_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_STM32_SPI_GetOps requires _ExpectAndReturn");
#define IMPL_STM32_SPI_GetOps_ExpectAndReturn(cmock_retval) IMPL_STM32_SPI_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_SPI_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_Ops_s* cmock_to_return);
typedef const SPI_Ops_s* (* CMOCK_IMPL_STM32_SPI_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_STM32_SPI_GetOps_AddCallback(CMOCK_IMPL_STM32_SPI_GetOps_CALLBACK Callback);
void IMPL_STM32_SPI_GetOps_Stub(CMOCK_IMPL_STM32_SPI_GetOps_CALLBACK Callback);
#define IMPL_STM32_SPI_GetOps_StubWithCallback IMPL_STM32_SPI_GetOps_Stub
int IMPL_STM32_SPI_GetOps_CallCount(void);
#define IMPL_STM32_SPI_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_SPI_DestroyCtx requires _Ignore (not AndReturn)");
#define IMPL_STM32_SPI_DestroyCtx_Ignore() IMPL_STM32_SPI_DestroyCtx_CMockIgnore()
void IMPL_STM32_SPI_DestroyCtx_CMockIgnore(void);
#define IMPL_STM32_SPI_DestroyCtx_StopIgnore() IMPL_STM32_SPI_DestroyCtx_CMockStopIgnore()
void IMPL_STM32_SPI_DestroyCtx_CMockStopIgnore(void);
#define IMPL_STM32_SPI_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_SPI_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define IMPL_STM32_SPI_DestroyCtx_ExpectAnyArgs() IMPL_STM32_SPI_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void IMPL_STM32_SPI_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_SPI_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_SPI_DestroyCtx requires _Expect (not AndReturn)");
#define IMPL_STM32_SPI_DestroyCtx_Expect(ctx) IMPL_STM32_SPI_DestroyCtx_CMockExpect(__LINE__, ctx)
void IMPL_STM32_SPI_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_IMPL_STM32_SPI_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void IMPL_STM32_SPI_DestroyCtx_AddCallback(CMOCK_IMPL_STM32_SPI_DestroyCtx_CALLBACK Callback);
void IMPL_STM32_SPI_DestroyCtx_Stub(CMOCK_IMPL_STM32_SPI_DestroyCtx_CALLBACK Callback);
#define IMPL_STM32_SPI_DestroyCtx_StubWithCallback IMPL_STM32_SPI_DestroyCtx_Stub
int IMPL_STM32_SPI_DestroyCtx_CallCount(void);
#define IMPL_STM32_SPI_DestroyCtx_ReturnThruPtr_ctx(ctx) IMPL_STM32_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define IMPL_STM32_SPI_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) IMPL_STM32_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define IMPL_STM32_SPI_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) IMPL_STM32_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void IMPL_STM32_SPI_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define IMPL_STM32_SPI_DestroyCtx_IgnoreArg_ctx() IMPL_STM32_SPI_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void IMPL_STM32_SPI_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_UART_CreateCtx_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_UART_CreateCtx requires _IgnoreAndReturn");
#define IMPL_STM32_UART_CreateCtx_IgnoreAndReturn(cmock_retval) IMPL_STM32_UART_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_UART_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_UART_CreateCtx_StopIgnore() IMPL_STM32_UART_CreateCtx_CMockStopIgnore()
void IMPL_STM32_UART_CreateCtx_CMockStopIgnore(void);
#define IMPL_STM32_UART_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("IMPL_STM32_UART_CreateCtx requires _ExpectAnyArgsAndReturn");
#define IMPL_STM32_UART_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) IMPL_STM32_UART_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_UART_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_UART_CreateCtx_Expect(huart, mode) TEST_FAIL_MESSAGE("IMPL_STM32_UART_CreateCtx requires _ExpectAndReturn");
#define IMPL_STM32_UART_CreateCtx_ExpectAndReturn(huart, mode, cmock_retval) IMPL_STM32_UART_CreateCtx_CMockExpectAndReturn(__LINE__, huart, mode, cmock_retval)
void IMPL_STM32_UART_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, UART_Xfer_Mode_e mode, void* cmock_to_return);
typedef void* (* CMOCK_IMPL_STM32_UART_CreateCtx_CALLBACK)(UART_HandleTypeDef* huart, UART_Xfer_Mode_e mode, int cmock_num_calls);
void IMPL_STM32_UART_CreateCtx_AddCallback(CMOCK_IMPL_STM32_UART_CreateCtx_CALLBACK Callback);
void IMPL_STM32_UART_CreateCtx_Stub(CMOCK_IMPL_STM32_UART_CreateCtx_CALLBACK Callback);
#define IMPL_STM32_UART_CreateCtx_StubWithCallback IMPL_STM32_UART_CreateCtx_Stub
int IMPL_STM32_UART_CreateCtx_CallCount(void);
#define IMPL_STM32_UART_CreateCtx_ReturnThruPtr_huart(huart) IMPL_STM32_UART_CreateCtx_CMockReturnMemThruPtr_huart(__LINE__, huart, sizeof(UART_HandleTypeDef))
#define IMPL_STM32_UART_CreateCtx_ReturnArrayThruPtr_huart(huart, cmock_len) IMPL_STM32_UART_CreateCtx_CMockReturnMemThruPtr_huart(__LINE__, huart, (cmock_len * sizeof(*huart)))
#define IMPL_STM32_UART_CreateCtx_ReturnMemThruPtr_huart(huart, cmock_size) IMPL_STM32_UART_CreateCtx_CMockReturnMemThruPtr_huart(__LINE__, huart, (cmock_size))
void IMPL_STM32_UART_CreateCtx_CMockReturnMemThruPtr_huart(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef const* huart, size_t cmock_size);
#define IMPL_STM32_UART_CreateCtx_IgnoreArg_huart() IMPL_STM32_UART_CreateCtx_CMockIgnoreArg_huart(__LINE__)
void IMPL_STM32_UART_CreateCtx_CMockIgnoreArg_huart(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_UART_CreateCtx_IgnoreArg_mode() IMPL_STM32_UART_CreateCtx_CMockIgnoreArg_mode(__LINE__)
void IMPL_STM32_UART_CreateCtx_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_UART_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_UART_GetOps requires _IgnoreAndReturn");
#define IMPL_STM32_UART_GetOps_IgnoreAndReturn(cmock_retval) IMPL_STM32_UART_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_UART_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const UART_Ops_s* cmock_to_return);
#define IMPL_STM32_UART_GetOps_StopIgnore() IMPL_STM32_UART_GetOps_CMockStopIgnore()
void IMPL_STM32_UART_GetOps_CMockStopIgnore(void);
#define IMPL_STM32_UART_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_STM32_UART_GetOps requires _ExpectAndReturn");
#define IMPL_STM32_UART_GetOps_ExpectAndReturn(cmock_retval) IMPL_STM32_UART_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_UART_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UART_Ops_s* cmock_to_return);
typedef const UART_Ops_s* (* CMOCK_IMPL_STM32_UART_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_STM32_UART_GetOps_AddCallback(CMOCK_IMPL_STM32_UART_GetOps_CALLBACK Callback);
void IMPL_STM32_UART_GetOps_Stub(CMOCK_IMPL_STM32_UART_GetOps_CALLBACK Callback);
#define IMPL_STM32_UART_GetOps_StubWithCallback IMPL_STM32_UART_GetOps_Stub
int IMPL_STM32_UART_GetOps_CallCount(void);
#define IMPL_STM32_UART_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_UART_DestroyCtx requires _Ignore (not AndReturn)");
#define IMPL_STM32_UART_DestroyCtx_Ignore() IMPL_STM32_UART_DestroyCtx_CMockIgnore()
void IMPL_STM32_UART_DestroyCtx_CMockIgnore(void);
#define IMPL_STM32_UART_DestroyCtx_StopIgnore() IMPL_STM32_UART_DestroyCtx_CMockStopIgnore()
void IMPL_STM32_UART_DestroyCtx_CMockStopIgnore(void);
#define IMPL_STM32_UART_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_UART_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define IMPL_STM32_UART_DestroyCtx_ExpectAnyArgs() IMPL_STM32_UART_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void IMPL_STM32_UART_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_UART_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_UART_DestroyCtx requires _Expect (not AndReturn)");
#define IMPL_STM32_UART_DestroyCtx_Expect(ctx) IMPL_STM32_UART_DestroyCtx_CMockExpect(__LINE__, ctx)
void IMPL_STM32_UART_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_IMPL_STM32_UART_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void IMPL_STM32_UART_DestroyCtx_AddCallback(CMOCK_IMPL_STM32_UART_DestroyCtx_CALLBACK Callback);
void IMPL_STM32_UART_DestroyCtx_Stub(CMOCK_IMPL_STM32_UART_DestroyCtx_CALLBACK Callback);
#define IMPL_STM32_UART_DestroyCtx_StubWithCallback IMPL_STM32_UART_DestroyCtx_Stub
int IMPL_STM32_UART_DestroyCtx_CallCount(void);
#define IMPL_STM32_UART_DestroyCtx_ReturnThruPtr_ctx(ctx) IMPL_STM32_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define IMPL_STM32_UART_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) IMPL_STM32_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define IMPL_STM32_UART_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) IMPL_STM32_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void IMPL_STM32_UART_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define IMPL_STM32_UART_DestroyCtx_IgnoreArg_ctx() IMPL_STM32_UART_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void IMPL_STM32_UART_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_PWM_CreateCtx_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_PWM_CreateCtx requires _IgnoreAndReturn");
#define IMPL_STM32_PWM_CreateCtx_IgnoreAndReturn(cmock_retval) IMPL_STM32_PWM_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_PWM_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_PWM_CreateCtx_StopIgnore() IMPL_STM32_PWM_CreateCtx_CMockStopIgnore()
void IMPL_STM32_PWM_CreateCtx_CMockStopIgnore(void);
#define IMPL_STM32_PWM_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("IMPL_STM32_PWM_CreateCtx requires _ExpectAnyArgsAndReturn");
#define IMPL_STM32_PWM_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) IMPL_STM32_PWM_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_PWM_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_PWM_CreateCtx_Expect(htim, channel) TEST_FAIL_MESSAGE("IMPL_STM32_PWM_CreateCtx requires _ExpectAndReturn");
#define IMPL_STM32_PWM_CreateCtx_ExpectAndReturn(htim, channel, cmock_retval) IMPL_STM32_PWM_CreateCtx_CMockExpectAndReturn(__LINE__, htim, channel, cmock_retval)
void IMPL_STM32_PWM_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TIM_HandleTypeDef* htim, uint32_t channel, void* cmock_to_return);
typedef void* (* CMOCK_IMPL_STM32_PWM_CreateCtx_CALLBACK)(TIM_HandleTypeDef* htim, uint32_t channel, int cmock_num_calls);
void IMPL_STM32_PWM_CreateCtx_AddCallback(CMOCK_IMPL_STM32_PWM_CreateCtx_CALLBACK Callback);
void IMPL_STM32_PWM_CreateCtx_Stub(CMOCK_IMPL_STM32_PWM_CreateCtx_CALLBACK Callback);
#define IMPL_STM32_PWM_CreateCtx_StubWithCallback IMPL_STM32_PWM_CreateCtx_Stub
int IMPL_STM32_PWM_CreateCtx_CallCount(void);
#define IMPL_STM32_PWM_CreateCtx_ReturnThruPtr_htim(htim) IMPL_STM32_PWM_CreateCtx_CMockReturnMemThruPtr_htim(__LINE__, htim, sizeof(TIM_HandleTypeDef))
#define IMPL_STM32_PWM_CreateCtx_ReturnArrayThruPtr_htim(htim, cmock_len) IMPL_STM32_PWM_CreateCtx_CMockReturnMemThruPtr_htim(__LINE__, htim, (cmock_len * sizeof(*htim)))
#define IMPL_STM32_PWM_CreateCtx_ReturnMemThruPtr_htim(htim, cmock_size) IMPL_STM32_PWM_CreateCtx_CMockReturnMemThruPtr_htim(__LINE__, htim, (cmock_size))
void IMPL_STM32_PWM_CreateCtx_CMockReturnMemThruPtr_htim(UNITY_LINE_TYPE cmock_line, TIM_HandleTypeDef const* htim, size_t cmock_size);
#define IMPL_STM32_PWM_CreateCtx_IgnoreArg_htim() IMPL_STM32_PWM_CreateCtx_CMockIgnoreArg_htim(__LINE__)
void IMPL_STM32_PWM_CreateCtx_CMockIgnoreArg_htim(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_PWM_CreateCtx_IgnoreArg_channel() IMPL_STM32_PWM_CreateCtx_CMockIgnoreArg_channel(__LINE__)
void IMPL_STM32_PWM_CreateCtx_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_PWM_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_PWM_GetOps requires _IgnoreAndReturn");
#define IMPL_STM32_PWM_GetOps_IgnoreAndReturn(cmock_retval) IMPL_STM32_PWM_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_PWM_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const PWM_Ops_s* cmock_to_return);
#define IMPL_STM32_PWM_GetOps_StopIgnore() IMPL_STM32_PWM_GetOps_CMockStopIgnore()
void IMPL_STM32_PWM_GetOps_CMockStopIgnore(void);
#define IMPL_STM32_PWM_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_STM32_PWM_GetOps requires _ExpectAndReturn");
#define IMPL_STM32_PWM_GetOps_ExpectAndReturn(cmock_retval) IMPL_STM32_PWM_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_PWM_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const PWM_Ops_s* cmock_to_return);
typedef const PWM_Ops_s* (* CMOCK_IMPL_STM32_PWM_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_STM32_PWM_GetOps_AddCallback(CMOCK_IMPL_STM32_PWM_GetOps_CALLBACK Callback);
void IMPL_STM32_PWM_GetOps_Stub(CMOCK_IMPL_STM32_PWM_GetOps_CALLBACK Callback);
#define IMPL_STM32_PWM_GetOps_StubWithCallback IMPL_STM32_PWM_GetOps_Stub
int IMPL_STM32_PWM_GetOps_CallCount(void);
#define IMPL_STM32_PWM_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_PWM_DestroyCtx requires _Ignore (not AndReturn)");
#define IMPL_STM32_PWM_DestroyCtx_Ignore() IMPL_STM32_PWM_DestroyCtx_CMockIgnore()
void IMPL_STM32_PWM_DestroyCtx_CMockIgnore(void);
#define IMPL_STM32_PWM_DestroyCtx_StopIgnore() IMPL_STM32_PWM_DestroyCtx_CMockStopIgnore()
void IMPL_STM32_PWM_DestroyCtx_CMockStopIgnore(void);
#define IMPL_STM32_PWM_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_PWM_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define IMPL_STM32_PWM_DestroyCtx_ExpectAnyArgs() IMPL_STM32_PWM_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void IMPL_STM32_PWM_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_PWM_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_PWM_DestroyCtx requires _Expect (not AndReturn)");
#define IMPL_STM32_PWM_DestroyCtx_Expect(ctx) IMPL_STM32_PWM_DestroyCtx_CMockExpect(__LINE__, ctx)
void IMPL_STM32_PWM_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_IMPL_STM32_PWM_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void IMPL_STM32_PWM_DestroyCtx_AddCallback(CMOCK_IMPL_STM32_PWM_DestroyCtx_CALLBACK Callback);
void IMPL_STM32_PWM_DestroyCtx_Stub(CMOCK_IMPL_STM32_PWM_DestroyCtx_CALLBACK Callback);
#define IMPL_STM32_PWM_DestroyCtx_StubWithCallback IMPL_STM32_PWM_DestroyCtx_Stub
int IMPL_STM32_PWM_DestroyCtx_CallCount(void);
#define IMPL_STM32_PWM_DestroyCtx_ReturnThruPtr_ctx(ctx) IMPL_STM32_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define IMPL_STM32_PWM_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) IMPL_STM32_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define IMPL_STM32_PWM_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) IMPL_STM32_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void IMPL_STM32_PWM_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define IMPL_STM32_PWM_DestroyCtx_IgnoreArg_ctx() IMPL_STM32_PWM_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void IMPL_STM32_PWM_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_FLASH_CreateCtx_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_CreateCtx requires _IgnoreAndReturn");
#define IMPL_STM32_FLASH_CreateCtx_IgnoreAndReturn(cmock_retval) IMPL_STM32_FLASH_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_FLASH_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_FLASH_CreateCtx_StopIgnore() IMPL_STM32_FLASH_CreateCtx_CMockStopIgnore()
void IMPL_STM32_FLASH_CreateCtx_CMockStopIgnore(void);
#define IMPL_STM32_FLASH_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_CreateCtx requires _ExpectAnyArgsAndReturn");
#define IMPL_STM32_FLASH_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) IMPL_STM32_FLASH_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_FLASH_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_FLASH_CreateCtx_Expect(first_sector, sector_count) TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_CreateCtx requires _ExpectAndReturn");
#define IMPL_STM32_FLASH_CreateCtx_ExpectAndReturn(first_sector, sector_count, cmock_retval) IMPL_STM32_FLASH_CreateCtx_CMockExpectAndReturn(__LINE__, first_sector, sector_count, cmock_retval)
void IMPL_STM32_FLASH_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t first_sector, uint32_t sector_count, void* cmock_to_return);
typedef void* (* CMOCK_IMPL_STM32_FLASH_CreateCtx_CALLBACK)(uint32_t first_sector, uint32_t sector_count, int cmock_num_calls);
void IMPL_STM32_FLASH_CreateCtx_AddCallback(CMOCK_IMPL_STM32_FLASH_CreateCtx_CALLBACK Callback);
void IMPL_STM32_FLASH_CreateCtx_Stub(CMOCK_IMPL_STM32_FLASH_CreateCtx_CALLBACK Callback);
#define IMPL_STM32_FLASH_CreateCtx_StubWithCallback IMPL_STM32_FLASH_CreateCtx_Stub
int IMPL_STM32_FLASH_CreateCtx_CallCount(void);
#define IMPL_STM32_FLASH_CreateCtx_IgnoreArg_first_sector() IMPL_STM32_FLASH_CreateCtx_CMockIgnoreArg_first_sector(__LINE__)
void IMPL_STM32_FLASH_CreateCtx_CMockIgnoreArg_first_sector(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_FLASH_CreateCtx_IgnoreArg_sector_count() IMPL_STM32_FLASH_CreateCtx_CMockIgnoreArg_sector_count(__LINE__)
void IMPL_STM32_FLASH_CreateCtx_CMockIgnoreArg_sector_count(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_FLASH_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_GetOps requires _IgnoreAndReturn");
#define IMPL_STM32_FLASH_GetOps_IgnoreAndReturn(cmock_retval) IMPL_STM32_FLASH_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_FLASH_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const Flash_Ops_s* cmock_to_return);
#define IMPL_STM32_FLASH_GetOps_StopIgnore() IMPL_STM32_FLASH_GetOps_CMockStopIgnore()
void IMPL_STM32_FLASH_GetOps_CMockStopIgnore(void);
#define IMPL_STM32_FLASH_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_GetOps requires _ExpectAndReturn");
#define IMPL_STM32_FLASH_GetOps_ExpectAndReturn(cmock_retval) IMPL_STM32_FLASH_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_FLASH_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const Flash_Ops_s* cmock_to_return);
typedef const Flash_Ops_s* (* CMOCK_IMPL_STM32_FLASH_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_STM32_FLASH_GetOps_AddCallback(CMOCK_IMPL_STM32_FLASH_GetOps_CALLBACK Callback);
void IMPL_STM32_FLASH_GetOps_Stub(CMOCK_IMPL_STM32_FLASH_GetOps_CALLBACK Callback);
#define IMPL_STM32_FLASH_GetOps_StubWithCallback IMPL_STM32_FLASH_GetOps_Stub
int IMPL_STM32_FLASH_GetOps_CallCount(void);
#define IMPL_STM32_FLASH_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_DestroyCtx requires _Ignore (not AndReturn)");
#define IMPL_STM32_FLASH_DestroyCtx_Ignore() IMPL_STM32_FLASH_DestroyCtx_CMockIgnore()
void IMPL_STM32_FLASH_DestroyCtx_CMockIgnore(void);
#define IMPL_STM32_FLASH_DestroyCtx_StopIgnore() IMPL_STM32_FLASH_DestroyCtx_CMockStopIgnore()
void IMPL_STM32_FLASH_DestroyCtx_CMockStopIgnore(void);
#define IMPL_STM32_FLASH_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define IMPL_STM32_FLASH_DestroyCtx_ExpectAnyArgs() IMPL_STM32_FLASH_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void IMPL_STM32_FLASH_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_FLASH_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_FLASH_DestroyCtx requires _Expect (not AndReturn)");
#define IMPL_STM32_FLASH_DestroyCtx_Expect(ctx) IMPL_STM32_FLASH_DestroyCtx_CMockExpect(__LINE__, ctx)
void IMPL_STM32_FLASH_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_IMPL_STM32_FLASH_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void IMPL_STM32_FLASH_DestroyCtx_AddCallback(CMOCK_IMPL_STM32_FLASH_DestroyCtx_CALLBACK Callback);
void IMPL_STM32_FLASH_DestroyCtx_Stub(CMOCK_IMPL_STM32_FLASH_DestroyCtx_CALLBACK Callback);
#define IMPL_STM32_FLASH_DestroyCtx_StubWithCallback IMPL_STM32_FLASH_DestroyCtx_Stub
int IMPL_STM32_FLASH_DestroyCtx_CallCount(void);
#define IMPL_STM32_FLASH_DestroyCtx_ReturnThruPtr_ctx(ctx) IMPL_STM32_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define IMPL_STM32_FLASH_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) IMPL_STM32_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define IMPL_STM32_FLASH_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) IMPL_STM32_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void IMPL_STM32_FLASH_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define IMPL_STM32_FLASH_DestroyCtx_IgnoreArg_ctx() IMPL_STM32_FLASH_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void IMPL_STM32_FLASH_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_CAN_CreateCtx_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_CAN_CreateCtx requires _IgnoreAndReturn");
#define IMPL_STM32_CAN_CreateCtx_IgnoreAndReturn(cmock_retval) IMPL_STM32_CAN_CreateCtx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_CAN_CreateCtx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_CAN_CreateCtx_StopIgnore() IMPL_STM32_CAN_CreateCtx_CMockStopIgnore()
void IMPL_STM32_CAN_CreateCtx_CMockStopIgnore(void);
#define IMPL_STM32_CAN_CreateCtx_ExpectAnyArgs() TEST_FAIL_MESSAGE("IMPL_STM32_CAN_CreateCtx requires _ExpectAnyArgsAndReturn");
#define IMPL_STM32_CAN_CreateCtx_ExpectAnyArgsAndReturn(cmock_retval) IMPL_STM32_CAN_CreateCtx_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_CAN_CreateCtx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define IMPL_STM32_CAN_CreateCtx_Expect(hfdcan, tx_id, rx_id) TEST_FAIL_MESSAGE("IMPL_STM32_CAN_CreateCtx requires _ExpectAndReturn");
#define IMPL_STM32_CAN_CreateCtx_ExpectAndReturn(hfdcan, tx_id, rx_id, cmock_retval) IMPL_STM32_CAN_CreateCtx_CMockExpectAndReturn(__LINE__, hfdcan, tx_id, rx_id, cmock_retval)
void IMPL_STM32_CAN_CreateCtx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef* hfdcan, uint32_t tx_id, uint32_t rx_id, void* cmock_to_return);
typedef void* (* CMOCK_IMPL_STM32_CAN_CreateCtx_CALLBACK)(FDCAN_HandleTypeDef* hfdcan, uint32_t tx_id, uint32_t rx_id, int cmock_num_calls);
void IMPL_STM32_CAN_CreateCtx_AddCallback(CMOCK_IMPL_STM32_CAN_CreateCtx_CALLBACK Callback);
void IMPL_STM32_CAN_CreateCtx_Stub(CMOCK_IMPL_STM32_CAN_CreateCtx_CALLBACK Callback);
#define IMPL_STM32_CAN_CreateCtx_StubWithCallback IMPL_STM32_CAN_CreateCtx_Stub
int IMPL_STM32_CAN_CreateCtx_CallCount(void);
#define IMPL_STM32_CAN_CreateCtx_ReturnThruPtr_hfdcan(hfdcan) IMPL_STM32_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(__LINE__, hfdcan, sizeof(FDCAN_HandleTypeDef))
#define IMPL_STM32_CAN_CreateCtx_ReturnArrayThruPtr_hfdcan(hfdcan, cmock_len) IMPL_STM32_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(__LINE__, hfdcan, (cmock_len * sizeof(*hfdcan)))
#define IMPL_STM32_CAN_CreateCtx_ReturnMemThruPtr_hfdcan(hfdcan, cmock_size) IMPL_STM32_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(__LINE__, hfdcan, (cmock_size))
void IMPL_STM32_CAN_CreateCtx_CMockReturnMemThruPtr_hfdcan(UNITY_LINE_TYPE cmock_line, FDCAN_HandleTypeDef const* hfdcan, size_t cmock_size);
#define IMPL_STM32_CAN_CreateCtx_IgnoreArg_hfdcan() IMPL_STM32_CAN_CreateCtx_CMockIgnoreArg_hfdcan(__LINE__)
void IMPL_STM32_CAN_CreateCtx_CMockIgnoreArg_hfdcan(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_CAN_CreateCtx_IgnoreArg_tx_id() IMPL_STM32_CAN_CreateCtx_CMockIgnoreArg_tx_id(__LINE__)
void IMPL_STM32_CAN_CreateCtx_CMockIgnoreArg_tx_id(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_CAN_CreateCtx_IgnoreArg_rx_id() IMPL_STM32_CAN_CreateCtx_CMockIgnoreArg_rx_id(__LINE__)
void IMPL_STM32_CAN_CreateCtx_CMockIgnoreArg_rx_id(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_CAN_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_STM32_CAN_GetOps requires _IgnoreAndReturn");
#define IMPL_STM32_CAN_GetOps_IgnoreAndReturn(cmock_retval) IMPL_STM32_CAN_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_CAN_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const CAN_Ops_s* cmock_to_return);
#define IMPL_STM32_CAN_GetOps_StopIgnore() IMPL_STM32_CAN_GetOps_CMockStopIgnore()
void IMPL_STM32_CAN_GetOps_CMockStopIgnore(void);
#define IMPL_STM32_CAN_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_STM32_CAN_GetOps requires _ExpectAndReturn");
#define IMPL_STM32_CAN_GetOps_ExpectAndReturn(cmock_retval) IMPL_STM32_CAN_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_STM32_CAN_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const CAN_Ops_s* cmock_to_return);
typedef const CAN_Ops_s* (* CMOCK_IMPL_STM32_CAN_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_STM32_CAN_GetOps_AddCallback(CMOCK_IMPL_STM32_CAN_GetOps_CALLBACK Callback);
void IMPL_STM32_CAN_GetOps_Stub(CMOCK_IMPL_STM32_CAN_GetOps_CALLBACK Callback);
#define IMPL_STM32_CAN_GetOps_StubWithCallback IMPL_STM32_CAN_GetOps_Stub
int IMPL_STM32_CAN_GetOps_CallCount(void);
#define IMPL_STM32_CAN_DestroyCtx_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_CAN_DestroyCtx requires _Ignore (not AndReturn)");
#define IMPL_STM32_CAN_DestroyCtx_Ignore() IMPL_STM32_CAN_DestroyCtx_CMockIgnore()
void IMPL_STM32_CAN_DestroyCtx_CMockIgnore(void);
#define IMPL_STM32_CAN_DestroyCtx_StopIgnore() IMPL_STM32_CAN_DestroyCtx_CMockStopIgnore()
void IMPL_STM32_CAN_DestroyCtx_CMockStopIgnore(void);
#define IMPL_STM32_CAN_DestroyCtx_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_CAN_DestroyCtx requires _ExpectAnyArgs (not AndReturn)");
#define IMPL_STM32_CAN_DestroyCtx_ExpectAnyArgs() IMPL_STM32_CAN_DestroyCtx_CMockExpectAnyArgs(__LINE__)
void IMPL_STM32_CAN_DestroyCtx_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IMPL_STM32_CAN_DestroyCtx_ExpectAndReturn(ctx, cmock_retval) TEST_FAIL_MESSAGE("IMPL_STM32_CAN_DestroyCtx requires _Expect (not AndReturn)");
#define IMPL_STM32_CAN_DestroyCtx_Expect(ctx) IMPL_STM32_CAN_DestroyCtx_CMockExpect(__LINE__, ctx)
void IMPL_STM32_CAN_DestroyCtx_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ctx);
typedef void (* CMOCK_IMPL_STM32_CAN_DestroyCtx_CALLBACK)(void* ctx, int cmock_num_calls);
void IMPL_STM32_CAN_DestroyCtx_AddCallback(CMOCK_IMPL_STM32_CAN_DestroyCtx_CALLBACK Callback);
void IMPL_STM32_CAN_DestroyCtx_Stub(CMOCK_IMPL_STM32_CAN_DestroyCtx_CALLBACK Callback);
#define IMPL_STM32_CAN_DestroyCtx_StubWithCallback IMPL_STM32_CAN_DestroyCtx_Stub
int IMPL_STM32_CAN_DestroyCtx_CallCount(void);
#define IMPL_STM32_CAN_DestroyCtx_ReturnThruPtr_ctx(ctx) IMPL_STM32_CAN_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define IMPL_STM32_CAN_DestroyCtx_ReturnArrayThruPtr_ctx(ctx, cmock_len) IMPL_STM32_CAN_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define IMPL_STM32_CAN_DestroyCtx_ReturnMemThruPtr_ctx(ctx, cmock_size) IMPL_STM32_CAN_DestroyCtx_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void IMPL_STM32_CAN_DestroyCtx_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define IMPL_STM32_CAN_DestroyCtx_IgnoreArg_ctx() IMPL_STM32_CAN_DestroyCtx_CMockIgnoreArg_ctx(__LINE__)
void IMPL_STM32_CAN_DestroyCtx_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define PLAT_DWT_Init_Ignore() TEST_FAIL_MESSAGE("PLAT_DWT_Init requires _IgnoreAndReturn");
#define PLAT_DWT_Init_IgnoreAndReturn(cmock_retval) PLAT_DWT_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_DWT_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_DWT_Init_StopIgnore() PLAT_DWT_Init_CMockStopIgnore()
void PLAT_DWT_Init_CMockStopIgnore(void);
#define PLAT_DWT_Init_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_DWT_Init requires _ExpectAnyArgsAndReturn");
#define PLAT_DWT_Init_ExpectAnyArgsAndReturn(cmock_retval) PLAT_DWT_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_DWT_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_DWT_Init_Expect(inst, ops, ctx) TEST_FAIL_MESSAGE("PLAT_DWT_Init requires _ExpectAndReturn");
#define PLAT_DWT_Init_ExpectAndReturn(inst, ops, ctx, cmock_retval) PLAT_DWT_Init_CMockExpectAndReturn(__LINE__, inst, ops, ctx, cmock_retval)
void PLAT_DWT_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DWT_Instance_s* inst, const DWT_Ops_s* ops, void* ctx, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_DWT_Init_CALLBACK)(DWT_Instance_s* inst, const DWT_Ops_s* ops, void* ctx, int cmock_num_calls);
void PLAT_DWT_Init_AddCallback(CMOCK_PLAT_DWT_Init_CALLBACK Callback);
void PLAT_DWT_Init_Stub(CMOCK_PLAT_DWT_Init_CALLBACK Callback);
#define PLAT_DWT_Init_StubWithCallback PLAT_DWT_Init_Stub
int PLAT_DWT_Init_CallCount(void);
#define PLAT_DWT_Init_ReturnThruPtr_inst(inst) PLAT_DWT_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, sizeof(DWT_Instance_s))
#define PLAT_DWT_Init_ReturnArrayThruPtr_inst(inst, cmock_len) PLAT_DWT_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_len * sizeof(*inst)))
#define PLAT_DWT_Init_ReturnMemThruPtr_inst(inst, cmock_size) PLAT_DWT_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_size))
void PLAT_DWT_Init_CMockReturnMemThruPtr_inst(UNITY_LINE_TYPE cmock_line, DWT_Instance_s const* inst, size_t cmock_size);
#define PLAT_DWT_Init_ReturnThruPtr_ctx(ctx) PLAT_DWT_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define PLAT_DWT_Init_ReturnArrayThruPtr_ctx(ctx, cmock_len) PLAT_DWT_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define PLAT_DWT_Init_ReturnMemThruPtr_ctx(ctx, cmock_size) PLAT_DWT_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void PLAT_DWT_Init_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define PLAT_DWT_Init_IgnoreArg_inst() PLAT_DWT_Init_CMockIgnoreArg_inst(__LINE__)
void PLAT_DWT_Init_CMockIgnoreArg_inst(UNITY_LINE_TYPE cmock_line);
#define PLAT_DWT_Init_IgnoreArg_ops() PLAT_DWT_Init_CMockIgnoreArg_ops(__LINE__)
void PLAT_DWT_Init_CMockIgnoreArg_ops(UNITY_LINE_TYPE cmock_line);
#define PLAT_DWT_Init_IgnoreArg_ctx() PLAT_DWT_Init_CMockIgnoreArg_ctx(__LINE__)
void PLAT_DWT_Init_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define PLAT_SPI_Init_Ignore() TEST_FAIL_MESSAGE("PLAT_SPI_Init requires _IgnoreAndReturn");
#define PLAT_SPI_Init_IgnoreAndReturn(cmock_retval) PLAT_SPI_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_SPI_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_SPI_Init_StopIgnore() PLAT_SPI_Init_CMockStopIgnore()
void PLAT_SPI_Init_CMockStopIgnore(void);
#define PLAT_SPI_Init_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_SPI_Init requires _ExpectAnyArgsAndReturn");
#define PLAT_SPI_Init_ExpectAnyArgsAndReturn(cmock_retval) PLAT_SPI_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_SPI_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_SPI_Init_Expect(inst, ops, ctx) TEST_FAIL_MESSAGE("PLAT_SPI_Init requires _ExpectAndReturn");
#define PLAT_SPI_Init_ExpectAndReturn(inst, ops, ctx, cmock_retval) PLAT_SPI_Init_CMockExpectAndReturn(__LINE__, inst, ops, ctx, cmock_retval)
void PLAT_SPI_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Instance_s* inst, const SPI_Ops_s* ops, void* ctx, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_SPI_Init_CALLBACK)(SPI_Instance_s* inst, const SPI_Ops_s* ops, void* ctx, int cmock_num_calls);
void PLAT_SPI_Init_AddCallback(CMOCK_PLAT_SPI_Init_CALLBACK Callback);
void PLAT_SPI_Init_Stub(CMOCK_PLAT_SPI_Init_CALLBACK Callback);
#define PLAT_SPI_Init_StubWithCallback PLAT_SPI_Init_Stub
int PLAT_SPI_Init_CallCount(void);
#define PLAT_SPI_Init_ReturnThruPtr_inst(inst) PLAT_SPI_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, sizeof(SPI_Instance_s))
#define PLAT_SPI_Init_ReturnArrayThruPtr_inst(inst, cmock_len) PLAT_SPI_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_len * sizeof(*inst)))
#define PLAT_SPI_Init_ReturnMemThruPtr_inst(inst, cmock_size) PLAT_SPI_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_size))
void PLAT_SPI_Init_CMockReturnMemThruPtr_inst(UNITY_LINE_TYPE cmock_line, SPI_Instance_s const* inst, size_t cmock_size);
#define PLAT_SPI_Init_ReturnThruPtr_ctx(ctx) PLAT_SPI_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define PLAT_SPI_Init_ReturnArrayThruPtr_ctx(ctx, cmock_len) PLAT_SPI_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define PLAT_SPI_Init_ReturnMemThruPtr_ctx(ctx, cmock_size) PLAT_SPI_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void PLAT_SPI_Init_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define PLAT_SPI_Init_IgnoreArg_inst() PLAT_SPI_Init_CMockIgnoreArg_inst(__LINE__)
void PLAT_SPI_Init_CMockIgnoreArg_inst(UNITY_LINE_TYPE cmock_line);
#define PLAT_SPI_Init_IgnoreArg_ops() PLAT_SPI_Init_CMockIgnoreArg_ops(__LINE__)
void PLAT_SPI_Init_CMockIgnoreArg_ops(UNITY_LINE_TYPE cmock_line);
#define PLAT_SPI_Init_IgnoreArg_ctx() PLAT_SPI_Init_CMockIgnoreArg_ctx(__LINE__)
void PLAT_SPI_Init_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define PLAT_UART_Init_Ignore() TEST_FAIL_MESSAGE("PLAT_UART_Init requires _IgnoreAndReturn");
#define PLAT_UART_Init_IgnoreAndReturn(cmock_retval) PLAT_UART_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_UART_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_UART_Init_StopIgnore() PLAT_UART_Init_CMockStopIgnore()
void PLAT_UART_Init_CMockStopIgnore(void);
#define PLAT_UART_Init_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_UART_Init requires _ExpectAnyArgsAndReturn");
#define PLAT_UART_Init_ExpectAnyArgsAndReturn(cmock_retval) PLAT_UART_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_UART_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_UART_Init_Expect(inst, ops, ctx) TEST_FAIL_MESSAGE("PLAT_UART_Init requires _ExpectAndReturn");
#define PLAT_UART_Init_ExpectAndReturn(inst, ops, ctx, cmock_retval) PLAT_UART_Init_CMockExpectAndReturn(__LINE__, inst, ops, ctx, cmock_retval)
void PLAT_UART_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Instance_s* inst, const UART_Ops_s* ops, void* ctx, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_UART_Init_CALLBACK)(UART_Instance_s* inst, const UART_Ops_s* ops, void* ctx, int cmock_num_calls);
void PLAT_UART_Init_AddCallback(CMOCK_PLAT_UART_Init_CALLBACK Callback);
void PLAT_UART_Init_Stub(CMOCK_PLAT_UART_Init_CALLBACK Callback);
#define PLAT_UART_Init_StubWithCallback PLAT_UART_Init_Stub
int PLAT_UART_Init_CallCount(void);
#define PLAT_UART_Init_ReturnThruPtr_inst(inst) PLAT_UART_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, sizeof(UART_Instance_s))
#define PLAT_UART_Init_ReturnArrayThruPtr_inst(inst, cmock_len) PLAT_UART_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_len * sizeof(*inst)))
#define PLAT_UART_Init_ReturnMemThruPtr_inst(inst, cmock_size) PLAT_UART_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_size))
void PLAT_UART_Init_CMockReturnMemThruPtr_inst(UNITY_LINE_TYPE cmock_line, UART_Instance_s const* inst, size_t cmock_size);
#define PLAT_UART_Init_ReturnThruPtr_ctx(ctx) PLAT_UART_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define PLAT_UART_Init_ReturnArrayThruPtr_ctx(ctx, cmock_len) PLAT_UART_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define PLAT_UART_Init_ReturnMemThruPtr_ctx(ctx, cmock_size) PLAT_UART_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void PLAT_UART_Init_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define PLAT_UART_Init_IgnoreArg_inst() PLAT_UART_Init_CMockIgnoreArg_inst(__LINE__)
void PLAT_UART_Init_CMockIgnoreArg_inst(UNITY_LINE_TYPE cmock_line);
#define PLAT_UART_Init_IgnoreArg_ops() PLAT_UART_Init_CMockIgnoreArg_ops(__LINE__)
void PLAT_UART_Init_CMockIgnoreArg_ops(UNITY_LINE_TYPE cmock_line);
#define PLAT_UART_Init_IgnoreArg_ctx() PLAT_UART_Init_CMockIgnoreArg_ctx(__LINE__)
void PLAT_UART_Init_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define PLAT_PWM_Init_Ignore() TEST_FAIL_MESSAGE("PLAT_PWM_Init requires _IgnoreAndReturn");
#define PLAT_PWM_Init_IgnoreAndReturn(cmock_retval) PLAT_PWM_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_PWM_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_PWM_Init_StopIgnore() PLAT_PWM_Init_CMockStopIgnore()
void PLAT_PWM_Init_CMockStopIgnore(void);
#define PLAT_PWM_Init_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_PWM_Init requires _ExpectAnyArgsAndReturn");
#define PLAT_PWM_Init_ExpectAnyArgsAndReturn(cmock_retval) PLAT_PWM_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_PWM_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_PWM_Init_Expect(inst, ops, ctx) TEST_FAIL_MESSAGE("PLAT_PWM_Init requires _ExpectAndReturn");
#define PLAT_PWM_Init_ExpectAndReturn(inst, ops, ctx, cmock_retval) PLAT_PWM_Init_CMockExpectAndReturn(__LINE__, inst, ops, ctx, cmock_retval)
void PLAT_PWM_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, PWM_Instance_s* inst, const PWM_Ops_s* ops, void* ctx, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_PWM_Init_CALLBACK)(PWM_Instance_s* inst, const PWM_Ops_s* ops, void* ctx, int cmock_num_calls);
void PLAT_PWM_Init_AddCallback(CMOCK_PLAT_PWM_Init_CALLBACK Callback);
void PLAT_PWM_Init_Stub(CMOCK_PLAT_PWM_Init_CALLBACK Callback);
#define PLAT_PWM_Init_StubWithCallback PLAT_PWM_Init_Stub
int PLAT_PWM_Init_CallCount(void);
#define PLAT_PWM_Init_ReturnThruPtr_inst(inst) PLAT_PWM_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, sizeof(PWM_Instance_s))
#define PLAT_PWM_Init_ReturnArrayThruPtr_inst(inst, cmock_len) PLAT_PWM_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_len * sizeof(*inst)))
#define PLAT_PWM_Init_ReturnMemThruPtr_inst(inst, cmock_size) PLAT_PWM_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_size))
void PLAT_PWM_Init_CMockReturnMemThruPtr_inst(UNITY_LINE_TYPE cmock_line, PWM_Instance_s const* inst, size_t cmock_size);
#define PLAT_PWM_Init_ReturnThruPtr_ctx(ctx) PLAT_PWM_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define PLAT_PWM_Init_ReturnArrayThruPtr_ctx(ctx, cmock_len) PLAT_PWM_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define PLAT_PWM_Init_ReturnMemThruPtr_ctx(ctx, cmock_size) PLAT_PWM_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void PLAT_PWM_Init_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define PLAT_PWM_Init_IgnoreArg_inst() PLAT_PWM_Init_CMockIgnoreArg_inst(__LINE__)
void PLAT_PWM_Init_CMockIgnoreArg_inst(UNITY_LINE_TYPE cmock_line);
#define PLAT_PWM_Init_IgnoreArg_ops() PLAT_PWM_Init_CMockIgnoreArg_ops(__LINE__)
void PLAT_PWM_Init_CMockIgnoreArg_ops(UNITY_LINE_TYPE cmock_line);
#define PLAT_PWM_Init_IgnoreArg_ctx() PLAT_PWM_Init_CMockIgnoreArg_ctx(__LINE__)
void PLAT_PWM_Init_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define PLAT_Flash_Init_Ignore() TEST_FAIL_MESSAGE("PLAT_Flash_Init requires _IgnoreAndReturn");
#define PLAT_Flash_Init_IgnoreAndReturn(cmock_retval) PLAT_Flash_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_Flash_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Flash_Init_StopIgnore() PLAT_Flash_Init_CMockStopIgnore()
void PLAT_Flash_Init_CMockStopIgnore(void);
#define PLAT_Flash_Init_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_Flash_Init requires _ExpectAnyArgsAndReturn");
#define PLAT_Flash_Init_ExpectAnyArgsAndReturn(cmock_retval) PLAT_Flash_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_Flash_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Flash_Init_Expect(inst, ops, ctx) TEST_FAIL_MESSAGE("PLAT_Flash_Init requires _ExpectAndReturn");
#define PLAT_Flash_Init_ExpectAndReturn(inst, ops, ctx, cmock_retval) PLAT_Flash_Init_CMockExpectAndReturn(__LINE__, inst, ops, ctx, cmock_retval)
void PLAT_Flash_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Flash_Instance_s* inst, const Flash_Ops_s* ops, void* ctx, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_Flash_Init_CALLBACK)(Flash_Instance_s* inst, const Flash_Ops_s* ops, void* ctx, int cmock_num_calls);
void PLAT_Flash_Init_AddCallback(CMOCK_PLAT_Flash_Init_CALLBACK Callback);
void PLAT_Flash_Init_Stub(CMOCK_PLAT_Flash_Init_CALLBACK Callback);
#define PLAT_Flash_Init_StubWithCallback PLAT_Flash_Init_Stub
int PLAT_Flash_Init_CallCount(void);
#define PLAT_Flash_Init_ReturnThruPtr_inst(inst) PLAT_Flash_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, sizeof(Flash_Instance_s))
#define PLAT_Flash_Init_ReturnArrayThruPtr_inst(inst, cmock_len) PLAT_Flash_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_len * sizeof(*inst)))
#define PLAT_Flash_Init_ReturnMemThruPtr_inst(inst, cmock_size) PLAT_Flash_Init_CMockReturnMemThruPtr_inst(__LINE__, inst, (cmock_size))
void PLAT_Flash_Init_CMockReturnMemThruPtr_inst(UNITY_LINE_TYPE cmock_line, Flash_Instance_s const* inst, size_t cmock_size);
#define PLAT_Flash_Init_ReturnThruPtr_ctx(ctx) PLAT_Flash_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define PLAT_Flash_Init_ReturnArrayThruPtr_ctx(ctx, cmock_len) PLAT_Flash_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define PLAT_Flash_Init_ReturnMemThruPtr_ctx(ctx, cmock_size) PLAT_Flash_Init_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void PLAT_Flash_Init_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define PLAT_Flash_Init_IgnoreArg_inst() PLAT_Flash_Init_CMockIgnoreArg_inst(__LINE__)
void PLAT_Flash_Init_CMockIgnoreArg_inst(UNITY_LINE_TYPE cmock_line);
#define PLAT_Flash_Init_IgnoreArg_ops() PLAT_Flash_Init_CMockIgnoreArg_ops(__LINE__)
void PLAT_Flash_Init_CMockIgnoreArg_ops(UNITY_LINE_TYPE cmock_line);
#define PLAT_Flash_Init_IgnoreArg_ctx() PLAT_Flash_Init_CMockIgnoreArg_ctx(__LINE__)
void PLAT_Flash_Init_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);
#define PLAT_CAN_Create_Ignore() TEST_FAIL_MESSAGE("PLAT_CAN_Create requires _IgnoreAndReturn");
#define PLAT_CAN_Create_IgnoreAndReturn(cmock_retval) PLAT_CAN_Create_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_CAN_Create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, CAN_Instance_s* cmock_to_return);
#define PLAT_CAN_Create_StopIgnore() PLAT_CAN_Create_CMockStopIgnore()
void PLAT_CAN_Create_CMockStopIgnore(void);
#define PLAT_CAN_Create_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_CAN_Create requires _ExpectAnyArgsAndReturn");
#define PLAT_CAN_Create_ExpectAnyArgsAndReturn(cmock_retval) PLAT_CAN_Create_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_CAN_Create_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, CAN_Instance_s* cmock_to_return);
#define PLAT_CAN_Create_Expect(ops, ctx) TEST_FAIL_MESSAGE("PLAT_CAN_Create requires _ExpectAndReturn");
#define PLAT_CAN_Create_ExpectAndReturn(ops, ctx, cmock_retval) PLAT_CAN_Create_CMockExpectAndReturn(__LINE__, ops, ctx, cmock_retval)
void PLAT_CAN_Create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const CAN_Ops_s* ops, void* ctx, CAN_Instance_s* cmock_to_return);
typedef CAN_Instance_s* (* CMOCK_PLAT_CAN_Create_CALLBACK)(const CAN_Ops_s* ops, void* ctx, int cmock_num_calls);
void PLAT_CAN_Create_AddCallback(CMOCK_PLAT_CAN_Create_CALLBACK Callback);
void PLAT_CAN_Create_Stub(CMOCK_PLAT_CAN_Create_CALLBACK Callback);
#define PLAT_CAN_Create_StubWithCallback PLAT_CAN_Create_Stub
int PLAT_CAN_Create_CallCount(void);
#define PLAT_CAN_Create_ReturnThruPtr_ctx(ctx) PLAT_CAN_Create_CMockReturnMemThruPtr_ctx(__LINE__, ctx, sizeof(*ctx))
#define PLAT_CAN_Create_ReturnArrayThruPtr_ctx(ctx, cmock_len) PLAT_CAN_Create_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_len * sizeof(*ctx)))
#define PLAT_CAN_Create_ReturnMemThruPtr_ctx(ctx, cmock_size) PLAT_CAN_Create_CMockReturnMemThruPtr_ctx(__LINE__, ctx, (cmock_size))
void PLAT_CAN_Create_CMockReturnMemThruPtr_ctx(UNITY_LINE_TYPE cmock_line, void const* ctx, size_t cmock_size);
#define PLAT_CAN_Create_IgnoreArg_ops() PLAT_CAN_Create_CMockIgnoreArg_ops(__LINE__)
void PLAT_CAN_Create_CMockIgnoreArg_ops(UNITY_LINE_TYPE cmock_line);
#define PLAT_CAN_Create_IgnoreArg_ctx() PLAT_CAN_Create_CMockIgnoreArg_ctx(__LINE__)
void PLAT_CAN_Create_CMockIgnoreArg_ctx(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
