/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_INDICATOR_DEPS_H
#define _MOCK_INDICATOR_DEPS_H

#include "unity.h"
#include "indicator_deps.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_indicator_deps_Init(void);
void mock_indicator_deps_Destroy(void);
void mock_indicator_deps_Verify(void);




#define Board_StatusLed_Ignore() TEST_FAIL_MESSAGE("Board_StatusLed requires _IgnoreAndReturn");
#define Board_StatusLed_IgnoreAndReturn(cmock_retval) Board_StatusLed_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Board_StatusLed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Instance_s* cmock_to_return);
#define Board_StatusLed_StopIgnore() Board_StatusLed_CMockStopIgnore()
void Board_StatusLed_CMockStopIgnore(void);
#define Board_StatusLed_Expect() TEST_FAIL_MESSAGE("Board_StatusLed requires _ExpectAndReturn");
#define Board_StatusLed_ExpectAndReturn(cmock_retval) Board_StatusLed_CMockExpectAndReturn(__LINE__, cmock_retval)
void Board_StatusLed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Instance_s* cmock_to_return);
typedef SPI_Instance_s* (* CMOCK_Board_StatusLed_CALLBACK)(int cmock_num_calls);
void Board_StatusLed_AddCallback(CMOCK_Board_StatusLed_CALLBACK Callback);
void Board_StatusLed_Stub(CMOCK_Board_StatusLed_CALLBACK Callback);
#define Board_StatusLed_StubWithCallback Board_StatusLed_Stub
int Board_StatusLed_CallCount(void);
#define DEV_WS2812_Init_Ignore() TEST_FAIL_MESSAGE("DEV_WS2812_Init requires _IgnoreAndReturn");
#define DEV_WS2812_Init_IgnoreAndReturn(cmock_retval) DEV_WS2812_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DEV_WS2812_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define DEV_WS2812_Init_StopIgnore() DEV_WS2812_Init_CMockStopIgnore()
void DEV_WS2812_Init_CMockStopIgnore(void);
#define DEV_WS2812_Init_ExpectAnyArgs() TEST_FAIL_MESSAGE("DEV_WS2812_Init requires _ExpectAnyArgsAndReturn");
#define DEV_WS2812_Init_ExpectAnyArgsAndReturn(cmock_retval) DEV_WS2812_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void DEV_WS2812_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define DEV_WS2812_Init_Expect(dev, spi, buf, bytes, count) TEST_FAIL_MESSAGE("DEV_WS2812_Init requires _ExpectAndReturn");
#define DEV_WS2812_Init_ExpectAndReturn(dev, spi, buf, bytes, count, cmock_retval) DEV_WS2812_Init_CMockExpectAndReturn(__LINE__, dev, spi, buf, bytes, count, cmock_retval)
void DEV_WS2812_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DEV_WS2812_s* dev, SPI_Instance_s* spi, uint8_t* buf, uint16_t bytes, uint16_t count, bool cmock_to_return);
typedef bool (* CMOCK_DEV_WS2812_Init_CALLBACK)(DEV_WS2812_s* dev, SPI_Instance_s* spi, uint8_t* buf, uint16_t bytes, uint16_t count, int cmock_num_calls);
void DEV_WS2812_Init_AddCallback(CMOCK_DEV_WS2812_Init_CALLBACK Callback);
void DEV_WS2812_Init_Stub(CMOCK_DEV_WS2812_Init_CALLBACK Callback);
#define DEV_WS2812_Init_StubWithCallback DEV_WS2812_Init_Stub
int DEV_WS2812_Init_CallCount(void);
#define DEV_WS2812_Init_ReturnThruPtr_dev(dev) DEV_WS2812_Init_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(DEV_WS2812_s))
#define DEV_WS2812_Init_ReturnArrayThruPtr_dev(dev, cmock_len) DEV_WS2812_Init_CMockReturnMemThruPtr_dev(__LINE__, dev, (cmock_len * sizeof(*dev)))
#define DEV_WS2812_Init_ReturnMemThruPtr_dev(dev, cmock_size) DEV_WS2812_Init_CMockReturnMemThruPtr_dev(__LINE__, dev, (cmock_size))
void DEV_WS2812_Init_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, DEV_WS2812_s const* dev, size_t cmock_size);
#define DEV_WS2812_Init_ReturnThruPtr_spi(spi) DEV_WS2812_Init_CMockReturnMemThruPtr_spi(__LINE__, spi, sizeof(SPI_Instance_s))
#define DEV_WS2812_Init_ReturnArrayThruPtr_spi(spi, cmock_len) DEV_WS2812_Init_CMockReturnMemThruPtr_spi(__LINE__, spi, (cmock_len * sizeof(*spi)))
#define DEV_WS2812_Init_ReturnMemThruPtr_spi(spi, cmock_size) DEV_WS2812_Init_CMockReturnMemThruPtr_spi(__LINE__, spi, (cmock_size))
void DEV_WS2812_Init_CMockReturnMemThruPtr_spi(UNITY_LINE_TYPE cmock_line, SPI_Instance_s const* spi, size_t cmock_size);
#define DEV_WS2812_Init_ReturnThruPtr_buf(buf) DEV_WS2812_Init_CMockReturnMemThruPtr_buf(__LINE__, buf, sizeof(uint8_t))
#define DEV_WS2812_Init_ReturnArrayThruPtr_buf(buf, cmock_len) DEV_WS2812_Init_CMockReturnMemThruPtr_buf(__LINE__, buf, (cmock_len * sizeof(*buf)))
#define DEV_WS2812_Init_ReturnMemThruPtr_buf(buf, cmock_size) DEV_WS2812_Init_CMockReturnMemThruPtr_buf(__LINE__, buf, (cmock_size))
void DEV_WS2812_Init_CMockReturnMemThruPtr_buf(UNITY_LINE_TYPE cmock_line, uint8_t const* buf, size_t cmock_size);
#define DEV_WS2812_Init_IgnoreArg_dev() DEV_WS2812_Init_CMockIgnoreArg_dev(__LINE__)
void DEV_WS2812_Init_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_Init_IgnoreArg_spi() DEV_WS2812_Init_CMockIgnoreArg_spi(__LINE__)
void DEV_WS2812_Init_CMockIgnoreArg_spi(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_Init_IgnoreArg_buf() DEV_WS2812_Init_CMockIgnoreArg_buf(__LINE__)
void DEV_WS2812_Init_CMockIgnoreArg_buf(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_Init_IgnoreArg_bytes() DEV_WS2812_Init_CMockIgnoreArg_bytes(__LINE__)
void DEV_WS2812_Init_CMockIgnoreArg_bytes(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_Init_IgnoreArg_count() DEV_WS2812_Init_CMockIgnoreArg_count(__LINE__)
void DEV_WS2812_Init_CMockIgnoreArg_count(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_SetPixel_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("DEV_WS2812_SetPixel requires _Ignore (not AndReturn)");
#define DEV_WS2812_SetPixel_Ignore() DEV_WS2812_SetPixel_CMockIgnore()
void DEV_WS2812_SetPixel_CMockIgnore(void);
#define DEV_WS2812_SetPixel_StopIgnore() DEV_WS2812_SetPixel_CMockStopIgnore()
void DEV_WS2812_SetPixel_CMockStopIgnore(void);
#define DEV_WS2812_SetPixel_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("DEV_WS2812_SetPixel requires _ExpectAnyArgs (not AndReturn)");
#define DEV_WS2812_SetPixel_ExpectAnyArgs() DEV_WS2812_SetPixel_CMockExpectAnyArgs(__LINE__)
void DEV_WS2812_SetPixel_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_SetPixel_ExpectAndReturn(dev, index, r, g, b, cmock_retval) TEST_FAIL_MESSAGE("DEV_WS2812_SetPixel requires _Expect (not AndReturn)");
#define DEV_WS2812_SetPixel_Expect(dev, index, r, g, b) DEV_WS2812_SetPixel_CMockExpect(__LINE__, dev, index, r, g, b)
void DEV_WS2812_SetPixel_CMockExpect(UNITY_LINE_TYPE cmock_line, DEV_WS2812_s* dev, uint16_t index, uint8_t r, uint8_t g, uint8_t b);
typedef void (* CMOCK_DEV_WS2812_SetPixel_CALLBACK)(DEV_WS2812_s* dev, uint16_t index, uint8_t r, uint8_t g, uint8_t b, int cmock_num_calls);
void DEV_WS2812_SetPixel_AddCallback(CMOCK_DEV_WS2812_SetPixel_CALLBACK Callback);
void DEV_WS2812_SetPixel_Stub(CMOCK_DEV_WS2812_SetPixel_CALLBACK Callback);
#define DEV_WS2812_SetPixel_StubWithCallback DEV_WS2812_SetPixel_Stub
int DEV_WS2812_SetPixel_CallCount(void);
#define DEV_WS2812_SetPixel_ReturnThruPtr_dev(dev) DEV_WS2812_SetPixel_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(DEV_WS2812_s))
#define DEV_WS2812_SetPixel_ReturnArrayThruPtr_dev(dev, cmock_len) DEV_WS2812_SetPixel_CMockReturnMemThruPtr_dev(__LINE__, dev, (cmock_len * sizeof(*dev)))
#define DEV_WS2812_SetPixel_ReturnMemThruPtr_dev(dev, cmock_size) DEV_WS2812_SetPixel_CMockReturnMemThruPtr_dev(__LINE__, dev, (cmock_size))
void DEV_WS2812_SetPixel_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, DEV_WS2812_s const* dev, size_t cmock_size);
#define DEV_WS2812_SetPixel_IgnoreArg_dev() DEV_WS2812_SetPixel_CMockIgnoreArg_dev(__LINE__)
void DEV_WS2812_SetPixel_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_SetPixel_IgnoreArg_index() DEV_WS2812_SetPixel_CMockIgnoreArg_index(__LINE__)
void DEV_WS2812_SetPixel_CMockIgnoreArg_index(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_SetPixel_IgnoreArg_r() DEV_WS2812_SetPixel_CMockIgnoreArg_r(__LINE__)
void DEV_WS2812_SetPixel_CMockIgnoreArg_r(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_SetPixel_IgnoreArg_g() DEV_WS2812_SetPixel_CMockIgnoreArg_g(__LINE__)
void DEV_WS2812_SetPixel_CMockIgnoreArg_g(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_SetPixel_IgnoreArg_b() DEV_WS2812_SetPixel_CMockIgnoreArg_b(__LINE__)
void DEV_WS2812_SetPixel_CMockIgnoreArg_b(UNITY_LINE_TYPE cmock_line);
#define DEV_WS2812_Show_Ignore() TEST_FAIL_MESSAGE("DEV_WS2812_Show requires _IgnoreAndReturn");
#define DEV_WS2812_Show_IgnoreAndReturn(cmock_retval) DEV_WS2812_Show_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DEV_WS2812_Show_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define DEV_WS2812_Show_StopIgnore() DEV_WS2812_Show_CMockStopIgnore()
void DEV_WS2812_Show_CMockStopIgnore(void);
#define DEV_WS2812_Show_ExpectAnyArgs() TEST_FAIL_MESSAGE("DEV_WS2812_Show requires _ExpectAnyArgsAndReturn");
#define DEV_WS2812_Show_ExpectAnyArgsAndReturn(cmock_retval) DEV_WS2812_Show_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void DEV_WS2812_Show_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define DEV_WS2812_Show_Expect(dev) TEST_FAIL_MESSAGE("DEV_WS2812_Show requires _ExpectAndReturn");
#define DEV_WS2812_Show_ExpectAndReturn(dev, cmock_retval) DEV_WS2812_Show_CMockExpectAndReturn(__LINE__, dev, cmock_retval)
void DEV_WS2812_Show_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DEV_WS2812_s* dev, bool cmock_to_return);
typedef bool (* CMOCK_DEV_WS2812_Show_CALLBACK)(DEV_WS2812_s* dev, int cmock_num_calls);
void DEV_WS2812_Show_AddCallback(CMOCK_DEV_WS2812_Show_CALLBACK Callback);
void DEV_WS2812_Show_Stub(CMOCK_DEV_WS2812_Show_CALLBACK Callback);
#define DEV_WS2812_Show_StubWithCallback DEV_WS2812_Show_Stub
int DEV_WS2812_Show_CallCount(void);
#define DEV_WS2812_Show_ReturnThruPtr_dev(dev) DEV_WS2812_Show_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(DEV_WS2812_s))
#define DEV_WS2812_Show_ReturnArrayThruPtr_dev(dev, cmock_len) DEV_WS2812_Show_CMockReturnMemThruPtr_dev(__LINE__, dev, (cmock_len * sizeof(*dev)))
#define DEV_WS2812_Show_ReturnMemThruPtr_dev(dev, cmock_size) DEV_WS2812_Show_CMockReturnMemThruPtr_dev(__LINE__, dev, (cmock_size))
void DEV_WS2812_Show_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, DEV_WS2812_s const* dev, size_t cmock_size);
#define DEV_WS2812_Show_IgnoreArg_dev() DEV_WS2812_Show_CMockIgnoreArg_dev(__LINE__)
void DEV_WS2812_Show_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define DEV_Watchdog_Register_Ignore() TEST_FAIL_MESSAGE("DEV_Watchdog_Register requires _IgnoreAndReturn");
#define DEV_Watchdog_Register_IgnoreAndReturn(cmock_retval) DEV_Watchdog_Register_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DEV_Watchdog_Register_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define DEV_Watchdog_Register_StopIgnore() DEV_Watchdog_Register_CMockStopIgnore()
void DEV_Watchdog_Register_CMockStopIgnore(void);
#define DEV_Watchdog_Register_ExpectAnyArgs() TEST_FAIL_MESSAGE("DEV_Watchdog_Register requires _ExpectAnyArgsAndReturn");
#define DEV_Watchdog_Register_ExpectAnyArgsAndReturn(cmock_retval) DEV_Watchdog_Register_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void DEV_Watchdog_Register_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define DEV_Watchdog_Register_Expect(wd, name) TEST_FAIL_MESSAGE("DEV_Watchdog_Register requires _ExpectAndReturn");
#define DEV_Watchdog_Register_ExpectAndReturn(wd, name, cmock_retval) DEV_Watchdog_Register_CMockExpectAndReturn(__LINE__, wd, name, cmock_retval)
void DEV_Watchdog_Register_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DEV_Watchdog_s* wd, const char* name, bool cmock_to_return);
typedef bool (* CMOCK_DEV_Watchdog_Register_CALLBACK)(DEV_Watchdog_s* wd, const char* name, int cmock_num_calls);
void DEV_Watchdog_Register_AddCallback(CMOCK_DEV_Watchdog_Register_CALLBACK Callback);
void DEV_Watchdog_Register_Stub(CMOCK_DEV_Watchdog_Register_CALLBACK Callback);
#define DEV_Watchdog_Register_StubWithCallback DEV_Watchdog_Register_Stub
int DEV_Watchdog_Register_CallCount(void);
#define DEV_Watchdog_Register_ReturnThruPtr_wd(wd) DEV_Watchdog_Register_CMockReturnMemThruPtr_wd(__LINE__, wd, sizeof(DEV_Watchdog_s))
#define DEV_Watchdog_Register_ReturnArrayThruPtr_wd(wd, cmock_len) DEV_Watchdog_Register_CMockReturnMemThruPtr_wd(__LINE__, wd, (cmock_len * sizeof(*wd)))
#define DEV_Watchdog_Register_ReturnMemThruPtr_wd(wd, cmock_size) DEV_Watchdog_Register_CMockReturnMemThruPtr_wd(__LINE__, wd, (cmock_size))
void DEV_Watchdog_Register_CMockReturnMemThruPtr_wd(UNITY_LINE_TYPE cmock_line, DEV_Watchdog_s const* wd, size_t cmock_size);
#define DEV_Watchdog_Register_IgnoreArg_wd() DEV_Watchdog_Register_CMockIgnoreArg_wd(__LINE__)
void DEV_Watchdog_Register_CMockIgnoreArg_wd(UNITY_LINE_TYPE cmock_line);
#define DEV_Watchdog_Register_IgnoreArg_name() DEV_Watchdog_Register_CMockIgnoreArg_name(__LINE__)
void DEV_Watchdog_Register_CMockIgnoreArg_name(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("UTIL_Seq_Init requires _Ignore (not AndReturn)");
#define UTIL_Seq_Init_Ignore() UTIL_Seq_Init_CMockIgnore()
void UTIL_Seq_Init_CMockIgnore(void);
#define UTIL_Seq_Init_StopIgnore() UTIL_Seq_Init_CMockStopIgnore()
void UTIL_Seq_Init_CMockStopIgnore(void);
#define UTIL_Seq_Init_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("UTIL_Seq_Init requires _ExpectAnyArgs (not AndReturn)");
#define UTIL_Seq_Init_ExpectAnyArgs() UTIL_Seq_Init_CMockExpectAnyArgs(__LINE__)
void UTIL_Seq_Init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Init_ExpectAndReturn(s, cmock_retval) TEST_FAIL_MESSAGE("UTIL_Seq_Init requires _Expect (not AndReturn)");
#define UTIL_Seq_Init_Expect(s) UTIL_Seq_Init_CMockExpect(__LINE__, s)
void UTIL_Seq_Init_CMockExpect(UNITY_LINE_TYPE cmock_line, UTIL_Seq_s* s);
typedef void (* CMOCK_UTIL_Seq_Init_CALLBACK)(UTIL_Seq_s* s, int cmock_num_calls);
void UTIL_Seq_Init_AddCallback(CMOCK_UTIL_Seq_Init_CALLBACK Callback);
void UTIL_Seq_Init_Stub(CMOCK_UTIL_Seq_Init_CALLBACK Callback);
#define UTIL_Seq_Init_StubWithCallback UTIL_Seq_Init_Stub
int UTIL_Seq_Init_CallCount(void);
#define UTIL_Seq_Init_ReturnThruPtr_s(s) UTIL_Seq_Init_CMockReturnMemThruPtr_s(__LINE__, s, sizeof(UTIL_Seq_s))
#define UTIL_Seq_Init_ReturnArrayThruPtr_s(s, cmock_len) UTIL_Seq_Init_CMockReturnMemThruPtr_s(__LINE__, s, (cmock_len * sizeof(*s)))
#define UTIL_Seq_Init_ReturnMemThruPtr_s(s, cmock_size) UTIL_Seq_Init_CMockReturnMemThruPtr_s(__LINE__, s, (cmock_size))
void UTIL_Seq_Init_CMockReturnMemThruPtr_s(UNITY_LINE_TYPE cmock_line, UTIL_Seq_s const* s, size_t cmock_size);
#define UTIL_Seq_Init_IgnoreArg_s() UTIL_Seq_Init_CMockIgnoreArg_s(__LINE__)
void UTIL_Seq_Init_CMockIgnoreArg_s(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Play_Ignore() TEST_FAIL_MESSAGE("UTIL_Seq_Play requires _IgnoreAndReturn");
#define UTIL_Seq_Play_IgnoreAndReturn(cmock_retval) UTIL_Seq_Play_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void UTIL_Seq_Play_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define UTIL_Seq_Play_StopIgnore() UTIL_Seq_Play_CMockStopIgnore()
void UTIL_Seq_Play_CMockStopIgnore(void);
#define UTIL_Seq_Play_ExpectAnyArgs() TEST_FAIL_MESSAGE("UTIL_Seq_Play requires _ExpectAnyArgsAndReturn");
#define UTIL_Seq_Play_ExpectAnyArgsAndReturn(cmock_retval) UTIL_Seq_Play_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void UTIL_Seq_Play_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define UTIL_Seq_Play_Expect(s, frames, loop, now_ms) TEST_FAIL_MESSAGE("UTIL_Seq_Play requires _ExpectAndReturn");
#define UTIL_Seq_Play_ExpectAndReturn(s, frames, loop, now_ms, cmock_retval) UTIL_Seq_Play_CMockExpectAndReturn(__LINE__, s, frames, loop, now_ms, cmock_retval)
void UTIL_Seq_Play_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UTIL_Seq_s* s, const UTIL_Seq_Frame_s* frames, bool loop, uint32_t now_ms, bool cmock_to_return);
typedef bool (* CMOCK_UTIL_Seq_Play_CALLBACK)(UTIL_Seq_s* s, const UTIL_Seq_Frame_s* frames, bool loop, uint32_t now_ms, int cmock_num_calls);
void UTIL_Seq_Play_AddCallback(CMOCK_UTIL_Seq_Play_CALLBACK Callback);
void UTIL_Seq_Play_Stub(CMOCK_UTIL_Seq_Play_CALLBACK Callback);
#define UTIL_Seq_Play_StubWithCallback UTIL_Seq_Play_Stub
int UTIL_Seq_Play_CallCount(void);
#define UTIL_Seq_Play_ReturnThruPtr_s(s) UTIL_Seq_Play_CMockReturnMemThruPtr_s(__LINE__, s, sizeof(UTIL_Seq_s))
#define UTIL_Seq_Play_ReturnArrayThruPtr_s(s, cmock_len) UTIL_Seq_Play_CMockReturnMemThruPtr_s(__LINE__, s, (cmock_len * sizeof(*s)))
#define UTIL_Seq_Play_ReturnMemThruPtr_s(s, cmock_size) UTIL_Seq_Play_CMockReturnMemThruPtr_s(__LINE__, s, (cmock_size))
void UTIL_Seq_Play_CMockReturnMemThruPtr_s(UNITY_LINE_TYPE cmock_line, UTIL_Seq_s const* s, size_t cmock_size);
#define UTIL_Seq_Play_IgnoreArg_s() UTIL_Seq_Play_CMockIgnoreArg_s(__LINE__)
void UTIL_Seq_Play_CMockIgnoreArg_s(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Play_IgnoreArg_frames() UTIL_Seq_Play_CMockIgnoreArg_frames(__LINE__)
void UTIL_Seq_Play_CMockIgnoreArg_frames(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Play_IgnoreArg_loop() UTIL_Seq_Play_CMockIgnoreArg_loop(__LINE__)
void UTIL_Seq_Play_CMockIgnoreArg_loop(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Play_IgnoreArg_now_ms() UTIL_Seq_Play_CMockIgnoreArg_now_ms(__LINE__)
void UTIL_Seq_Play_CMockIgnoreArg_now_ms(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Step_Ignore() TEST_FAIL_MESSAGE("UTIL_Seq_Step requires _IgnoreAndReturn");
#define UTIL_Seq_Step_IgnoreAndReturn(cmock_retval) UTIL_Seq_Step_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void UTIL_Seq_Step_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define UTIL_Seq_Step_StopIgnore() UTIL_Seq_Step_CMockStopIgnore()
void UTIL_Seq_Step_CMockStopIgnore(void);
#define UTIL_Seq_Step_ExpectAnyArgs() TEST_FAIL_MESSAGE("UTIL_Seq_Step requires _ExpectAnyArgsAndReturn");
#define UTIL_Seq_Step_ExpectAnyArgsAndReturn(cmock_retval) UTIL_Seq_Step_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void UTIL_Seq_Step_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define UTIL_Seq_Step_Expect(s, now_ms) TEST_FAIL_MESSAGE("UTIL_Seq_Step requires _ExpectAndReturn");
#define UTIL_Seq_Step_ExpectAndReturn(s, now_ms, cmock_retval) UTIL_Seq_Step_CMockExpectAndReturn(__LINE__, s, now_ms, cmock_retval)
void UTIL_Seq_Step_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UTIL_Seq_s* s, uint32_t now_ms, bool cmock_to_return);
typedef bool (* CMOCK_UTIL_Seq_Step_CALLBACK)(UTIL_Seq_s* s, uint32_t now_ms, int cmock_num_calls);
void UTIL_Seq_Step_AddCallback(CMOCK_UTIL_Seq_Step_CALLBACK Callback);
void UTIL_Seq_Step_Stub(CMOCK_UTIL_Seq_Step_CALLBACK Callback);
#define UTIL_Seq_Step_StubWithCallback UTIL_Seq_Step_Stub
int UTIL_Seq_Step_CallCount(void);
#define UTIL_Seq_Step_ReturnThruPtr_s(s) UTIL_Seq_Step_CMockReturnMemThruPtr_s(__LINE__, s, sizeof(UTIL_Seq_s))
#define UTIL_Seq_Step_ReturnArrayThruPtr_s(s, cmock_len) UTIL_Seq_Step_CMockReturnMemThruPtr_s(__LINE__, s, (cmock_len * sizeof(*s)))
#define UTIL_Seq_Step_ReturnMemThruPtr_s(s, cmock_size) UTIL_Seq_Step_CMockReturnMemThruPtr_s(__LINE__, s, (cmock_size))
void UTIL_Seq_Step_CMockReturnMemThruPtr_s(UNITY_LINE_TYPE cmock_line, UTIL_Seq_s const* s, size_t cmock_size);
#define UTIL_Seq_Step_IgnoreArg_s() UTIL_Seq_Step_CMockIgnoreArg_s(__LINE__)
void UTIL_Seq_Step_CMockIgnoreArg_s(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Step_IgnoreArg_now_ms() UTIL_Seq_Step_CMockIgnoreArg_now_ms(__LINE__)
void UTIL_Seq_Step_CMockIgnoreArg_now_ms(UNITY_LINE_TYPE cmock_line);
#define UTIL_Seq_Out_Ignore() TEST_FAIL_MESSAGE("UTIL_Seq_Out requires _IgnoreAndReturn");
#define UTIL_Seq_Out_IgnoreAndReturn(cmock_retval) UTIL_Seq_Out_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void UTIL_Seq_Out_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const uint16_t* cmock_to_return);
#define UTIL_Seq_Out_StopIgnore() UTIL_Seq_Out_CMockStopIgnore()
void UTIL_Seq_Out_CMockStopIgnore(void);
#define UTIL_Seq_Out_ExpectAnyArgs() TEST_FAIL_MESSAGE("UTIL_Seq_Out requires _ExpectAnyArgsAndReturn");
#define UTIL_Seq_Out_ExpectAnyArgsAndReturn(cmock_retval) UTIL_Seq_Out_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void UTIL_Seq_Out_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, const uint16_t* cmock_to_return);
#define UTIL_Seq_Out_Expect(s) TEST_FAIL_MESSAGE("UTIL_Seq_Out requires _ExpectAndReturn");
#define UTIL_Seq_Out_ExpectAndReturn(s, cmock_retval) UTIL_Seq_Out_CMockExpectAndReturn(__LINE__, s, cmock_retval)
void UTIL_Seq_Out_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UTIL_Seq_s* s, const uint16_t* cmock_to_return);
typedef const uint16_t* (* CMOCK_UTIL_Seq_Out_CALLBACK)(const UTIL_Seq_s* s, int cmock_num_calls);
void UTIL_Seq_Out_AddCallback(CMOCK_UTIL_Seq_Out_CALLBACK Callback);
void UTIL_Seq_Out_Stub(CMOCK_UTIL_Seq_Out_CALLBACK Callback);
#define UTIL_Seq_Out_StubWithCallback UTIL_Seq_Out_Stub
int UTIL_Seq_Out_CallCount(void);
#define UTIL_Seq_Out_IgnoreArg_s() UTIL_Seq_Out_CMockIgnoreArg_s(__LINE__)
void UTIL_Seq_Out_CMockIgnoreArg_s(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_Ignore() TEST_FAIL_MESSAGE("PLAT_Task_Create requires _IgnoreAndReturn");
#define PLAT_Task_Create_IgnoreAndReturn(cmock_retval) PLAT_Task_Create_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_Task_Create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Task_Create_StopIgnore() PLAT_Task_Create_CMockStopIgnore()
void PLAT_Task_Create_CMockStopIgnore(void);
#define PLAT_Task_Create_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_Task_Create requires _ExpectAnyArgsAndReturn");
#define PLAT_Task_Create_ExpectAnyArgsAndReturn(cmock_retval) PLAT_Task_Create_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_Task_Create_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Task_Create_Expect(task, entry, arg, name, stack, stack_bytes, priority) TEST_FAIL_MESSAGE("PLAT_Task_Create requires _ExpectAndReturn");
#define PLAT_Task_Create_ExpectAndReturn(task, entry, arg, name, stack, stack_bytes, priority, cmock_retval) PLAT_Task_Create_CMockExpectAndReturn(__LINE__, task, entry, arg, name, stack, stack_bytes, priority, cmock_retval)
void PLAT_Task_Create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Task_s* task, PLAT_Task_Entry entry, void* arg, const char* name, void* stack, size_t stack_bytes, uint8_t priority, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_Task_Create_CALLBACK)(Task_s* task, PLAT_Task_Entry entry, void* arg, const char* name, void* stack, size_t stack_bytes, uint8_t priority, int cmock_num_calls);
void PLAT_Task_Create_AddCallback(CMOCK_PLAT_Task_Create_CALLBACK Callback);
void PLAT_Task_Create_Stub(CMOCK_PLAT_Task_Create_CALLBACK Callback);
#define PLAT_Task_Create_StubWithCallback PLAT_Task_Create_Stub
int PLAT_Task_Create_CallCount(void);
#define PLAT_Task_Create_ReturnThruPtr_task(task) PLAT_Task_Create_CMockReturnMemThruPtr_task(__LINE__, task, sizeof(Task_s))
#define PLAT_Task_Create_ReturnArrayThruPtr_task(task, cmock_len) PLAT_Task_Create_CMockReturnMemThruPtr_task(__LINE__, task, (cmock_len * sizeof(*task)))
#define PLAT_Task_Create_ReturnMemThruPtr_task(task, cmock_size) PLAT_Task_Create_CMockReturnMemThruPtr_task(__LINE__, task, (cmock_size))
void PLAT_Task_Create_CMockReturnMemThruPtr_task(UNITY_LINE_TYPE cmock_line, Task_s const* task, size_t cmock_size);
#define PLAT_Task_Create_ReturnThruPtr_arg(arg) PLAT_Task_Create_CMockReturnMemThruPtr_arg(__LINE__, arg, sizeof(*arg))
#define PLAT_Task_Create_ReturnArrayThruPtr_arg(arg, cmock_len) PLAT_Task_Create_CMockReturnMemThruPtr_arg(__LINE__, arg, (cmock_len * sizeof(*arg)))
#define PLAT_Task_Create_ReturnMemThruPtr_arg(arg, cmock_size) PLAT_Task_Create_CMockReturnMemThruPtr_arg(__LINE__, arg, (cmock_size))
void PLAT_Task_Create_CMockReturnMemThruPtr_arg(UNITY_LINE_TYPE cmock_line, void const* arg, size_t cmock_size);
#define PLAT_Task_Create_ReturnThruPtr_stack(stack) PLAT_Task_Create_CMockReturnMemThruPtr_stack(__LINE__, stack, sizeof(*stack))
#define PLAT_Task_Create_ReturnArrayThruPtr_stack(stack, cmock_len) PLAT_Task_Create_CMockReturnMemThruPtr_stack(__LINE__, stack, (cmock_len * sizeof(*stack)))
#define PLAT_Task_Create_ReturnMemThruPtr_stack(stack, cmock_size) PLAT_Task_Create_CMockReturnMemThruPtr_stack(__LINE__, stack, (cmock_size))
void PLAT_Task_Create_CMockReturnMemThruPtr_stack(UNITY_LINE_TYPE cmock_line, void const* stack, size_t cmock_size);
#define PLAT_Task_Create_IgnoreArg_task() PLAT_Task_Create_CMockIgnoreArg_task(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_task(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_IgnoreArg_entry() PLAT_Task_Create_CMockIgnoreArg_entry(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_entry(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_IgnoreArg_arg() PLAT_Task_Create_CMockIgnoreArg_arg(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_arg(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_IgnoreArg_name() PLAT_Task_Create_CMockIgnoreArg_name(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_name(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_IgnoreArg_stack() PLAT_Task_Create_CMockIgnoreArg_stack(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_stack(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_IgnoreArg_stack_bytes() PLAT_Task_Create_CMockIgnoreArg_stack_bytes(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_stack_bytes(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Create_IgnoreArg_priority() PLAT_Task_Create_CMockIgnoreArg_priority(__LINE__)
void PLAT_Task_Create_CMockIgnoreArg_priority(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_TickNow_Ignore() TEST_FAIL_MESSAGE("PLAT_Task_TickNow requires _IgnoreAndReturn");
#define PLAT_Task_TickNow_IgnoreAndReturn(cmock_retval) PLAT_Task_TickNow_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_Task_TickNow_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define PLAT_Task_TickNow_StopIgnore() PLAT_Task_TickNow_CMockStopIgnore()
void PLAT_Task_TickNow_CMockStopIgnore(void);
#define PLAT_Task_TickNow_Expect() TEST_FAIL_MESSAGE("PLAT_Task_TickNow requires _ExpectAndReturn");
#define PLAT_Task_TickNow_ExpectAndReturn(cmock_retval) PLAT_Task_TickNow_CMockExpectAndReturn(__LINE__, cmock_retval)
void PLAT_Task_TickNow_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_PLAT_Task_TickNow_CALLBACK)(int cmock_num_calls);
void PLAT_Task_TickNow_AddCallback(CMOCK_PLAT_Task_TickNow_CALLBACK Callback);
void PLAT_Task_TickNow_Stub(CMOCK_PLAT_Task_TickNow_CALLBACK Callback);
#define PLAT_Task_TickNow_StubWithCallback PLAT_Task_TickNow_Stub
int PLAT_Task_TickNow_CallCount(void);
#define PLAT_Task_DelayUntil_Ignore() TEST_FAIL_MESSAGE("PLAT_Task_DelayUntil requires _IgnoreAndReturn");
#define PLAT_Task_DelayUntil_IgnoreAndReturn(cmock_retval) PLAT_Task_DelayUntil_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_Task_DelayUntil_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Task_DelayUntil_StopIgnore() PLAT_Task_DelayUntil_CMockStopIgnore()
void PLAT_Task_DelayUntil_CMockStopIgnore(void);
#define PLAT_Task_DelayUntil_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_Task_DelayUntil requires _ExpectAnyArgsAndReturn");
#define PLAT_Task_DelayUntil_ExpectAnyArgsAndReturn(cmock_retval) PLAT_Task_DelayUntil_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_Task_DelayUntil_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Task_DelayUntil_Expect(prev_tick, period_ms) TEST_FAIL_MESSAGE("PLAT_Task_DelayUntil requires _ExpectAndReturn");
#define PLAT_Task_DelayUntil_ExpectAndReturn(prev_tick, period_ms, cmock_retval) PLAT_Task_DelayUntil_CMockExpectAndReturn(__LINE__, prev_tick, period_ms, cmock_retval)
void PLAT_Task_DelayUntil_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* prev_tick, uint32_t period_ms, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_Task_DelayUntil_CALLBACK)(uint32_t* prev_tick, uint32_t period_ms, int cmock_num_calls);
void PLAT_Task_DelayUntil_AddCallback(CMOCK_PLAT_Task_DelayUntil_CALLBACK Callback);
void PLAT_Task_DelayUntil_Stub(CMOCK_PLAT_Task_DelayUntil_CALLBACK Callback);
#define PLAT_Task_DelayUntil_StubWithCallback PLAT_Task_DelayUntil_Stub
int PLAT_Task_DelayUntil_CallCount(void);
#define PLAT_Task_DelayUntil_ReturnThruPtr_prev_tick(prev_tick) PLAT_Task_DelayUntil_CMockReturnMemThruPtr_prev_tick(__LINE__, prev_tick, sizeof(uint32_t))
#define PLAT_Task_DelayUntil_ReturnArrayThruPtr_prev_tick(prev_tick, cmock_len) PLAT_Task_DelayUntil_CMockReturnMemThruPtr_prev_tick(__LINE__, prev_tick, (cmock_len * sizeof(*prev_tick)))
#define PLAT_Task_DelayUntil_ReturnMemThruPtr_prev_tick(prev_tick, cmock_size) PLAT_Task_DelayUntil_CMockReturnMemThruPtr_prev_tick(__LINE__, prev_tick, (cmock_size))
void PLAT_Task_DelayUntil_CMockReturnMemThruPtr_prev_tick(UNITY_LINE_TYPE cmock_line, uint32_t const* prev_tick, size_t cmock_size);
#define PLAT_Task_DelayUntil_IgnoreArg_prev_tick() PLAT_Task_DelayUntil_CMockIgnoreArg_prev_tick(__LINE__)
void PLAT_Task_DelayUntil_CMockIgnoreArg_prev_tick(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_DelayUntil_IgnoreArg_period_ms() PLAT_Task_DelayUntil_CMockIgnoreArg_period_ms(__LINE__)
void PLAT_Task_DelayUntil_CMockIgnoreArg_period_ms(UNITY_LINE_TYPE cmock_line);
#define UTIL_Log_Write_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("UTIL_Log_Write requires _Ignore (not AndReturn)");
#define UTIL_Log_Write_Ignore() UTIL_Log_Write_CMockIgnore()
void UTIL_Log_Write_CMockIgnore(void);
#define UTIL_Log_Write_StopIgnore() UTIL_Log_Write_CMockStopIgnore()
void UTIL_Log_Write_CMockStopIgnore(void);
#define UTIL_Log_Write_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("UTIL_Log_Write requires _ExpectAnyArgs (not AndReturn)");
#define UTIL_Log_Write_ExpectAnyArgs() UTIL_Log_Write_CMockExpectAnyArgs(__LINE__)
void UTIL_Log_Write_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define UTIL_Log_Write_ExpectAndReturn(level, tag, fmt, cmock_retval) TEST_FAIL_MESSAGE("UTIL_Log_Write requires _Expect (not AndReturn)");
#define UTIL_Log_Write_Expect(level, tag, fmt) UTIL_Log_Write_CMockExpect(__LINE__, level, tag, fmt)
void UTIL_Log_Write_CMockExpect(UNITY_LINE_TYPE cmock_line, UTIL_Log_Level_e level, const char* tag, const char* fmt);
typedef void (* CMOCK_UTIL_Log_Write_CALLBACK)(UTIL_Log_Level_e level, const char* tag, const char* fmt, int cmock_num_calls);
void UTIL_Log_Write_AddCallback(CMOCK_UTIL_Log_Write_CALLBACK Callback);
void UTIL_Log_Write_Stub(CMOCK_UTIL_Log_Write_CALLBACK Callback);
#define UTIL_Log_Write_StubWithCallback UTIL_Log_Write_Stub
int UTIL_Log_Write_CallCount(void);
#define UTIL_Log_Write_IgnoreArg_level() UTIL_Log_Write_CMockIgnoreArg_level(__LINE__)
void UTIL_Log_Write_CMockIgnoreArg_level(UNITY_LINE_TYPE cmock_line);
#define UTIL_Log_Write_IgnoreArg_tag() UTIL_Log_Write_CMockIgnoreArg_tag(__LINE__)
void UTIL_Log_Write_CMockIgnoreArg_tag(UNITY_LINE_TYPE cmock_line);
#define UTIL_Log_Write_IgnoreArg_fmt() UTIL_Log_Write_CMockIgnoreArg_fmt(__LINE__)
void UTIL_Log_Write_CMockIgnoreArg_fmt(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
