/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_PLAT_MEMORY_H
#define _MOCK_PLAT_MEMORY_H

#include "unity.h"
#include "plat_memory.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_plat_memory_Init(void);
void mock_plat_memory_Destroy(void);
void mock_plat_memory_Verify(void);




#define PLAT_malloc_Ignore() TEST_FAIL_MESSAGE("PLAT_malloc requires _IgnoreAndReturn");
#define PLAT_malloc_IgnoreAndReturn(cmock_retval) PLAT_malloc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_malloc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define PLAT_malloc_StopIgnore() PLAT_malloc_CMockStopIgnore()
void PLAT_malloc_CMockStopIgnore(void);
#define PLAT_malloc_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_malloc requires _ExpectAnyArgsAndReturn");
#define PLAT_malloc_ExpectAnyArgsAndReturn(cmock_retval) PLAT_malloc_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_malloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define PLAT_malloc_Expect(size) TEST_FAIL_MESSAGE("PLAT_malloc requires _ExpectAndReturn");
#define PLAT_malloc_ExpectAndReturn(size, cmock_retval) PLAT_malloc_CMockExpectAndReturn(__LINE__, size, cmock_retval)
void PLAT_malloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t size, void* cmock_to_return);
typedef void* (* CMOCK_PLAT_malloc_CALLBACK)(size_t size, int cmock_num_calls);
void PLAT_malloc_AddCallback(CMOCK_PLAT_malloc_CALLBACK Callback);
void PLAT_malloc_Stub(CMOCK_PLAT_malloc_CALLBACK Callback);
#define PLAT_malloc_StubWithCallback PLAT_malloc_Stub
int PLAT_malloc_CallCount(void);
#define PLAT_malloc_IgnoreArg_size() PLAT_malloc_CMockIgnoreArg_size(__LINE__)
void PLAT_malloc_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define PLAT_free_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("PLAT_free requires _Ignore (not AndReturn)");
#define PLAT_free_Ignore() PLAT_free_CMockIgnore()
void PLAT_free_CMockIgnore(void);
#define PLAT_free_StopIgnore() PLAT_free_CMockStopIgnore()
void PLAT_free_CMockStopIgnore(void);
#define PLAT_free_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("PLAT_free requires _ExpectAnyArgs (not AndReturn)");
#define PLAT_free_ExpectAnyArgs() PLAT_free_CMockExpectAnyArgs(__LINE__)
void PLAT_free_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PLAT_free_ExpectAndReturn(ptr, cmock_retval) TEST_FAIL_MESSAGE("PLAT_free requires _Expect (not AndReturn)");
#define PLAT_free_Expect(ptr) PLAT_free_CMockExpect(__LINE__, ptr)
void PLAT_free_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ptr);
typedef void (* CMOCK_PLAT_free_CALLBACK)(void* ptr, int cmock_num_calls);
void PLAT_free_AddCallback(CMOCK_PLAT_free_CALLBACK Callback);
void PLAT_free_Stub(CMOCK_PLAT_free_CALLBACK Callback);
#define PLAT_free_StubWithCallback PLAT_free_Stub
int PLAT_free_CallCount(void);
#define PLAT_free_ReturnThruPtr_ptr(ptr) PLAT_free_CMockReturnMemThruPtr_ptr(__LINE__, ptr, sizeof(*ptr))
#define PLAT_free_ReturnArrayThruPtr_ptr(ptr, cmock_len) PLAT_free_CMockReturnMemThruPtr_ptr(__LINE__, ptr, (cmock_len * sizeof(*ptr)))
#define PLAT_free_ReturnMemThruPtr_ptr(ptr, cmock_size) PLAT_free_CMockReturnMemThruPtr_ptr(__LINE__, ptr, (cmock_size))
void PLAT_free_CMockReturnMemThruPtr_ptr(UNITY_LINE_TYPE cmock_line, void const* ptr, size_t cmock_size);
#define PLAT_free_IgnoreArg_ptr() PLAT_free_CMockIgnoreArg_ptr(__LINE__)
void PLAT_free_CMockIgnoreArg_ptr(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
