/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_plat_memory.h"

static const char* CMockString_PLAT_free = "PLAT_free";
static const char* CMockString_PLAT_malloc = "PLAT_malloc";
static const char* CMockString_ptr = "ptr";
static const char* CMockString_size = "size";

typedef struct _CMOCK_PLAT_malloc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  int CallOrder;
  size_t Expected_size;
  char IgnoreArg_size;

} CMOCK_PLAT_malloc_CALL_INSTANCE;

typedef struct _CMOCK_PLAT_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  void* Expected_ptr;
  char ReturnThruPtr_ptr_Used;
  void const* ReturnThruPtr_ptr_Val;
  size_t ReturnThruPtr_ptr_Size;
  char IgnoreArg_ptr;

} CMOCK_PLAT_free_CALL_INSTANCE;

static struct mock_plat_memoryInstance
{
  char PLAT_malloc_IgnoreBool;
  void* PLAT_malloc_FinalReturn;
  char PLAT_malloc_CallbackBool;
  CMOCK_PLAT_malloc_CALLBACK PLAT_malloc_CallbackFunctionPointer;
  int PLAT_malloc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PLAT_malloc_CallInstance;
  char PLAT_free_IgnoreBool;
  char PLAT_free_CallbackBool;
  CMOCK_PLAT_free_CALLBACK PLAT_free_CallbackFunctionPointer;
  int PLAT_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PLAT_free_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_plat_memory_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.PLAT_malloc_CallInstance;
  if (Mock.PLAT_malloc_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_malloc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.PLAT_malloc_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.PLAT_free_CallInstance;
  if (Mock.PLAT_free_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_free);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.PLAT_free_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_plat_memory_Init(void)
{
  mock_plat_memory_Destroy();
}

void mock_plat_memory_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void* PLAT_malloc(size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PLAT_malloc);
  cmock_call_instance = (CMOCK_PLAT_malloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PLAT_malloc_CallInstance);
  Mock.PLAT_malloc_CallInstance = CMock_Guts_MemNext(Mock.PLAT_malloc_CallInstance);
  if (Mock.PLAT_malloc_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.PLAT_malloc_FinalReturn;
    Mock.PLAT_malloc_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.PLAT_malloc_CallbackBool &&
      Mock.PLAT_malloc_CallbackFunctionPointer != NULL)
  {
    void* cmock_cb_ret = Mock.PLAT_malloc_CallbackFunctionPointer(size, Mock.PLAT_malloc_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_malloc,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_size, &size, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.PLAT_malloc_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_malloc);
    cmock_call_instance->ReturnVal = Mock.PLAT_malloc_CallbackFunctionPointer(size, Mock.PLAT_malloc_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_PLAT_malloc(CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance, size_t size);
void CMockExpectParameters_PLAT_malloc(CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_size), (const void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_size = 0;
}

void PLAT_malloc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_malloc_CALL_INSTANCE));
  CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_malloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_malloc_CallInstance = CMock_Guts_MemChain(Mock.PLAT_malloc_CallInstance, cmock_guts_index);
  Mock.PLAT_malloc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.PLAT_malloc_IgnoreBool = (char)1;
}

void PLAT_malloc_CMockStopIgnore(void)
{
  if(Mock.PLAT_malloc_IgnoreBool)
    Mock.PLAT_malloc_CallInstance = CMock_Guts_MemNext(Mock.PLAT_malloc_CallInstance);
  Mock.PLAT_malloc_IgnoreBool = (char)0;
}

void PLAT_malloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_malloc_CALL_INSTANCE));
  CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_malloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_malloc_CallInstance = CMock_Guts_MemChain(Mock.PLAT_malloc_CallInstance, cmock_guts_index);
  Mock.PLAT_malloc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PLAT_malloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_malloc_CALL_INSTANCE));
  CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_malloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_malloc_CallInstance = CMock_Guts_MemChain(Mock.PLAT_malloc_CallInstance, cmock_guts_index);
  Mock.PLAT_malloc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PLAT_malloc(cmock_call_instance, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void PLAT_malloc_AddCallback(CMOCK_PLAT_malloc_CALLBACK Callback)
{
  Mock.PLAT_malloc_IgnoreBool = (char)0;
  Mock.PLAT_malloc_CallbackBool = (char)1;
  Mock.PLAT_malloc_CallbackCalls = 0;
  Mock.PLAT_malloc_CallbackFunctionPointer = Callback;
}

int PLAT_malloc_CallCount(void)
{
  return Mock.PLAT_malloc_CallbackCalls;
}

void PLAT_malloc_Stub(CMOCK_PLAT_malloc_CALLBACK Callback)
{
  Mock.PLAT_malloc_IgnoreBool = (char)0;
  Mock.PLAT_malloc_CallbackBool = (char)0;
  Mock.PLAT_malloc_CallbackCalls = 0;
  Mock.PLAT_malloc_CallbackFunctionPointer = Callback;
}

void PLAT_malloc_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_malloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_malloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_malloc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

void PLAT_free(void* ptr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PLAT_free);
  cmock_call_instance = (CMOCK_PLAT_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PLAT_free_CallInstance);
  Mock.PLAT_free_CallInstance = CMock_Guts_MemNext(Mock.PLAT_free_CallInstance);
  if (Mock.PLAT_free_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_ptr_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(ptr, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)ptr, (const void*)cmock_call_instance->ReturnThruPtr_ptr_Val,
      cmock_call_instance->ReturnThruPtr_ptr_Size);
  }
  if (Mock.PLAT_free_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.PLAT_free_CallbackBool &&
      Mock.PLAT_free_CallbackFunctionPointer != NULL)
  {
    Mock.PLAT_free_CallbackFunctionPointer(ptr, Mock.PLAT_free_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_ptr)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_free,CMockString_ptr);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ptr, ptr, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.PLAT_free_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_free);
    Mock.PLAT_free_CallbackFunctionPointer(ptr, Mock.PLAT_free_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_ptr_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(ptr, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)ptr, (const void*)cmock_call_instance->ReturnThruPtr_ptr_Val,
      cmock_call_instance->ReturnThruPtr_ptr_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_PLAT_free(CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance, void* ptr);
void CMockExpectParameters_PLAT_free(CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance, void* ptr)
{
  cmock_call_instance->Expected_ptr = ptr;
  cmock_call_instance->IgnoreArg_ptr = 0;
  cmock_call_instance->ReturnThruPtr_ptr_Used = 0;
}

void PLAT_free_CMockIgnore(void)
{
  Mock.PLAT_free_IgnoreBool = (char)1;
}

void PLAT_free_CMockStopIgnore(void)
{
  Mock.PLAT_free_IgnoreBool = (char)0;
}

void PLAT_free_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_free_CALL_INSTANCE));
  CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_free_CallInstance = CMock_Guts_MemChain(Mock.PLAT_free_CallInstance, cmock_guts_index);
  Mock.PLAT_free_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PLAT_free_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ptr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_free_CALL_INSTANCE));
  CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_free_CallInstance = CMock_Guts_MemChain(Mock.PLAT_free_CallInstance, cmock_guts_index);
  Mock.PLAT_free_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PLAT_free(cmock_call_instance, ptr);
}

void PLAT_free_AddCallback(CMOCK_PLAT_free_CALLBACK Callback)
{
  Mock.PLAT_free_IgnoreBool = (char)0;
  Mock.PLAT_free_CallbackBool = (char)1;
  Mock.PLAT_free_CallbackCalls = 0;
  Mock.PLAT_free_CallbackFunctionPointer = Callback;
}

int PLAT_free_CallCount(void)
{
  return Mock.PLAT_free_CallbackCalls;
}

void PLAT_free_Stub(CMOCK_PLAT_free_CALLBACK Callback)
{
  Mock.PLAT_free_IgnoreBool = (char)0;
  Mock.PLAT_free_CallbackBool = (char)0;
  Mock.PLAT_free_CallbackCalls = 0;
  Mock.PLAT_free_CallbackFunctionPointer = Callback;
}

void PLAT_free_CMockReturnMemThruPtr_ptr(UNITY_LINE_TYPE cmock_line, void const* ptr, size_t cmock_size)
{
  CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_free_CallInstance));
  if (Mock.PLAT_free_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_ptr_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_free_CALL_INSTANCE));
    CMOCK_PLAT_free_CALL_INSTANCE* new_instance = (CMOCK_PLAT_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    Mock.PLAT_free_CallInstance = CMock_Guts_MemChain(Mock.PLAT_free_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_ptr_Used = 1;
  cmock_call_instance->ReturnThruPtr_ptr_Val = ptr;
  cmock_call_instance->ReturnThruPtr_ptr_Size = cmock_size;
}

void PLAT_free_CMockIgnoreArg_ptr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_free_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ptr = 1;
}

