/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_PRTOS_IMPL_SEM_H
#define _MOCK_PRTOS_IMPL_SEM_H

#include "unity.h"
#include "impl_sem.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_prtos_impl_sem_Init(void);
void mock_prtos_impl_sem_Destroy(void);
void mock_prtos_impl_sem_Verify(void);




#define IMPL_Sem_GetOps_Ignore() TEST_FAIL_MESSAGE("IMPL_Sem_GetOps requires _IgnoreAndReturn");
#define IMPL_Sem_GetOps_IgnoreAndReturn(cmock_retval) IMPL_Sem_GetOps_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IMPL_Sem_GetOps_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const IMPL_Sem_Ops_s* cmock_to_return);
#define IMPL_Sem_GetOps_StopIgnore() IMPL_Sem_GetOps_CMockStopIgnore()
void IMPL_Sem_GetOps_CMockStopIgnore(void);
#define IMPL_Sem_GetOps_Expect() TEST_FAIL_MESSAGE("IMPL_Sem_GetOps requires _ExpectAndReturn");
#define IMPL_Sem_GetOps_ExpectAndReturn(cmock_retval) IMPL_Sem_GetOps_CMockExpectAndReturn(__LINE__, cmock_retval)
void IMPL_Sem_GetOps_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const IMPL_Sem_Ops_s* cmock_to_return);
typedef const IMPL_Sem_Ops_s* (* CMOCK_IMPL_Sem_GetOps_CALLBACK)(int cmock_num_calls);
void IMPL_Sem_GetOps_AddCallback(CMOCK_IMPL_Sem_GetOps_CALLBACK Callback);
void IMPL_Sem_GetOps_Stub(CMOCK_IMPL_Sem_GetOps_CALLBACK Callback);
#define IMPL_Sem_GetOps_StubWithCallback IMPL_Sem_GetOps_Stub
int IMPL_Sem_GetOps_CallCount(void);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
