/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_FREERTOS_H
#define _MOCK_FREERTOS_H

#include "unity.h"
#include "FreeRTOS.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_FreeRTOS_Init(void);
void mock_FreeRTOS_Destroy(void);
void mock_FreeRTOS_Verify(void);




#define pvPortMalloc_Ignore() TEST_FAIL_MESSAGE("pvPortMalloc requires _IgnoreAndReturn");
#define pvPortMalloc_IgnoreAndReturn(cmock_retval) pvPortMalloc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void pvPortMalloc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define pvPortMalloc_StopIgnore() pvPortMalloc_CMockStopIgnore()
void pvPortMalloc_CMockStopIgnore(void);
#define pvPortMalloc_ExpectAnyArgs() TEST_FAIL_MESSAGE("pvPortMalloc requires _ExpectAnyArgsAndReturn");
#define pvPortMalloc_ExpectAnyArgsAndReturn(cmock_retval) pvPortMalloc_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void pvPortMalloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define pvPortMalloc_Expect(size) TEST_FAIL_MESSAGE("pvPortMalloc requires _ExpectAndReturn");
#define pvPortMalloc_ExpectAndReturn(size, cmock_retval) pvPortMalloc_CMockExpectAndReturn(__LINE__, size, cmock_retval)
void pvPortMalloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t size, void* cmock_to_return);
typedef void* (* CMOCK_pvPortMalloc_CALLBACK)(size_t size, int cmock_num_calls);
void pvPortMalloc_AddCallback(CMOCK_pvPortMalloc_CALLBACK Callback);
void pvPortMalloc_Stub(CMOCK_pvPortMalloc_CALLBACK Callback);
#define pvPortMalloc_StubWithCallback pvPortMalloc_Stub
int pvPortMalloc_CallCount(void);
#define pvPortMalloc_IgnoreArg_size() pvPortMalloc_CMockIgnoreArg_size(__LINE__)
void pvPortMalloc_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define vPortFree_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortFree requires _Ignore (not AndReturn)");
#define vPortFree_Ignore() vPortFree_CMockIgnore()
void vPortFree_CMockIgnore(void);
#define vPortFree_StopIgnore() vPortFree_CMockStopIgnore()
void vPortFree_CMockStopIgnore(void);
#define vPortFree_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortFree requires _ExpectAnyArgs (not AndReturn)");
#define vPortFree_ExpectAnyArgs() vPortFree_CMockExpectAnyArgs(__LINE__)
void vPortFree_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define vPortFree_ExpectAndReturn(ptr, cmock_retval) TEST_FAIL_MESSAGE("vPortFree requires _Expect (not AndReturn)");
#define vPortFree_Expect(ptr) vPortFree_CMockExpect(__LINE__, ptr)
void vPortFree_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ptr);
typedef void (* CMOCK_vPortFree_CALLBACK)(void* ptr, int cmock_num_calls);
void vPortFree_AddCallback(CMOCK_vPortFree_CALLBACK Callback);
void vPortFree_Stub(CMOCK_vPortFree_CALLBACK Callback);
#define vPortFree_StubWithCallback vPortFree_Stub
int vPortFree_CallCount(void);
#define vPortFree_ReturnThruPtr_ptr(ptr) vPortFree_CMockReturnMemThruPtr_ptr(__LINE__, ptr, sizeof(*ptr))
#define vPortFree_ReturnArrayThruPtr_ptr(ptr, cmock_len) vPortFree_CMockReturnMemThruPtr_ptr(__LINE__, ptr, (cmock_len * sizeof(*ptr)))
#define vPortFree_ReturnMemThruPtr_ptr(ptr, cmock_size) vPortFree_CMockReturnMemThruPtr_ptr(__LINE__, ptr, (cmock_size))
void vPortFree_CMockReturnMemThruPtr_ptr(UNITY_LINE_TYPE cmock_line, void const* ptr, size_t cmock_size);
#define vPortFree_IgnoreArg_ptr() vPortFree_CMockIgnoreArg_ptr(__LINE__)
void vPortFree_CMockIgnoreArg_ptr(UNITY_LINE_TYPE cmock_line);
#define xPortIsInsideInterrupt_Ignore() TEST_FAIL_MESSAGE("xPortIsInsideInterrupt requires _IgnoreAndReturn");
#define xPortIsInsideInterrupt_IgnoreAndReturn(cmock_retval) xPortIsInsideInterrupt_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xPortIsInsideInterrupt_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xPortIsInsideInterrupt_StopIgnore() xPortIsInsideInterrupt_CMockStopIgnore()
void xPortIsInsideInterrupt_CMockStopIgnore(void);
#define xPortIsInsideInterrupt_Expect() TEST_FAIL_MESSAGE("xPortIsInsideInterrupt requires _ExpectAndReturn");
#define xPortIsInsideInterrupt_ExpectAndReturn(cmock_retval) xPortIsInsideInterrupt_CMockExpectAndReturn(__LINE__, cmock_retval)
void xPortIsInsideInterrupt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
typedef BaseType_t (* CMOCK_xPortIsInsideInterrupt_CALLBACK)(int cmock_num_calls);
void xPortIsInsideInterrupt_AddCallback(CMOCK_xPortIsInsideInterrupt_CALLBACK Callback);
void xPortIsInsideInterrupt_Stub(CMOCK_xPortIsInsideInterrupt_CALLBACK Callback);
#define xPortIsInsideInterrupt_StubWithCallback xPortIsInsideInterrupt_Stub
int xPortIsInsideInterrupt_CallCount(void);
#define vPortYieldFromISR_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYieldFromISR requires _Ignore (not AndReturn)");
#define vPortYieldFromISR_Ignore() vPortYieldFromISR_CMockIgnore()
void vPortYieldFromISR_CMockIgnore(void);
#define vPortYieldFromISR_StopIgnore() vPortYieldFromISR_CMockStopIgnore()
void vPortYieldFromISR_CMockStopIgnore(void);
#define vPortYieldFromISR_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYieldFromISR requires _ExpectAnyArgs (not AndReturn)");
#define vPortYieldFromISR_ExpectAnyArgs() vPortYieldFromISR_CMockExpectAnyArgs(__LINE__)
void vPortYieldFromISR_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define vPortYieldFromISR_ExpectAndReturn(woken, cmock_retval) TEST_FAIL_MESSAGE("vPortYieldFromISR requires _Expect (not AndReturn)");
#define vPortYieldFromISR_Expect(woken) vPortYieldFromISR_CMockExpect(__LINE__, woken)
void vPortYieldFromISR_CMockExpect(UNITY_LINE_TYPE cmock_line, BaseType_t woken);
typedef void (* CMOCK_vPortYieldFromISR_CALLBACK)(BaseType_t woken, int cmock_num_calls);
void vPortYieldFromISR_AddCallback(CMOCK_vPortYieldFromISR_CALLBACK Callback);
void vPortYieldFromISR_Stub(CMOCK_vPortYieldFromISR_CALLBACK Callback);
#define vPortYieldFromISR_StubWithCallback vPortYieldFromISR_Stub
int vPortYieldFromISR_CallCount(void);
#define vPortYieldFromISR_IgnoreArg_woken() vPortYieldFromISR_CMockIgnoreArg_woken(__LINE__)
void vPortYieldFromISR_CMockIgnoreArg_woken(UNITY_LINE_TYPE cmock_line);
#define vPortYield_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYield requires _Ignore (not AndReturn)");
#define vPortYield_Ignore() vPortYield_CMockIgnore()
void vPortYield_CMockIgnore(void);
#define vPortYield_StopIgnore() vPortYield_CMockStopIgnore()
void vPortYield_CMockStopIgnore(void);
#define vPortYield_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYield requires _Expect (not AndReturn)");
#define vPortYield_Expect() vPortYield_CMockExpect(__LINE__)
void vPortYield_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_vPortYield_CALLBACK)(int cmock_num_calls);
void vPortYield_AddCallback(CMOCK_vPortYield_CALLBACK Callback);
void vPortYield_Stub(CMOCK_vPortYield_CALLBACK Callback);
#define vPortYield_StubWithCallback vPortYield_Stub
int vPortYield_CallCount(void);
#define vPortDisableInterrupts_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortDisableInterrupts requires _Ignore (not AndReturn)");
#define vPortDisableInterrupts_Ignore() vPortDisableInterrupts_CMockIgnore()
void vPortDisableInterrupts_CMockIgnore(void);
#define vPortDisableInterrupts_StopIgnore() vPortDisableInterrupts_CMockStopIgnore()
void vPortDisableInterrupts_CMockStopIgnore(void);
#define vPortDisableInterrupts_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortDisableInterrupts requires _Expect (not AndReturn)");
#define vPortDisableInterrupts_Expect() vPortDisableInterrupts_CMockExpect(__LINE__)
void vPortDisableInterrupts_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_vPortDisableInterrupts_CALLBACK)(int cmock_num_calls);
void vPortDisableInterrupts_AddCallback(CMOCK_vPortDisableInterrupts_CALLBACK Callback);
void vPortDisableInterrupts_Stub(CMOCK_vPortDisableInterrupts_CALLBACK Callback);
#define vPortDisableInterrupts_StubWithCallback vPortDisableInterrupts_Stub
int vPortDisableInterrupts_CallCount(void);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
