/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_indicator_contract.h"

static const char* CMockString_Board_StatusLed = "Board_StatusLed";
static const char* CMockString_PLAT_Task_Create = "PLAT_Task_Create";
static const char* CMockString_PLAT_Task_DelayUntil = "PLAT_Task_DelayUntil";
static const char* CMockString_PLAT_Task_TickNow = "PLAT_Task_TickNow";
static const char* CMockString_UTIL_Log_Write = "UTIL_Log_Write";
static const char* CMockString_arg = "arg";
static const char* CMockString_entry = "entry";
static const char* CMockString_fmt = "fmt";
static const char* CMockString_level = "level";
static const char* CMockString_name = "name";
static const char* CMockString_period_ms = "period_ms";
static const char* CMockString_prev_tick = "prev_tick";
static const char* CMockString_priority = "priority";
static const char* CMockString_stack = "stack";
static const char* CMockString_stack_bytes = "stack_bytes";
static const char* CMockString_tag = "tag";
static const char* CMockString_task = "task";

typedef struct _CMOCK_Board_StatusLed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  SPI_Instance_s* ReturnVal;
  int CallOrder;

} CMOCK_Board_StatusLed_CALL_INSTANCE;

typedef struct _CMOCK_PLAT_Task_Create_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  int CallOrder;
  Task_s* Expected_task;
  PLAT_Task_Entry Expected_entry;
  void* Expected_arg;
  const char* Expected_name;
  void* Expected_stack;
  size_t Expected_stack_bytes;
  uint8_t Expected_priority;
  char ReturnThruPtr_task_Used;
  Task_s const* ReturnThruPtr_task_Val;
  size_t ReturnThruPtr_task_Size;
  char ReturnThruPtr_arg_Used;
  void const* ReturnThruPtr_arg_Val;
  size_t ReturnThruPtr_arg_Size;
  char ReturnThruPtr_stack_Used;
  void const* ReturnThruPtr_stack_Val;
  size_t ReturnThruPtr_stack_Size;
  char IgnoreArg_task;
  char IgnoreArg_entry;
  char IgnoreArg_arg;
  char IgnoreArg_name;
  char IgnoreArg_stack;
  char IgnoreArg_stack_bytes;
  char IgnoreArg_priority;

} CMOCK_PLAT_Task_Create_CALL_INSTANCE;

typedef struct _CMOCK_PLAT_Task_TickNow_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;

} CMOCK_PLAT_Task_TickNow_CALL_INSTANCE;

typedef struct _CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  int CallOrder;
  uint32_t* Expected_prev_tick;
  uint32_t Expected_period_ms;
  char ReturnThruPtr_prev_tick_Used;
  uint32_t const* ReturnThruPtr_prev_tick_Val;
  size_t ReturnThruPtr_prev_tick_Size;
  char IgnoreArg_prev_tick;
  char IgnoreArg_period_ms;

} CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE;

typedef struct _CMOCK_UTIL_Log_Write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  UTIL_Log_Level_e Expected_level;
  const char* Expected_tag;
  const char* Expected_fmt;
  char IgnoreArg_level;
  char IgnoreArg_tag;
  char IgnoreArg_fmt;

} CMOCK_UTIL_Log_Write_CALL_INSTANCE;

static struct mock_indicator_contractInstance
{
  char Board_StatusLed_IgnoreBool;
  SPI_Instance_s* Board_StatusLed_FinalReturn;
  char Board_StatusLed_CallbackBool;
  CMOCK_Board_StatusLed_CALLBACK Board_StatusLed_CallbackFunctionPointer;
  int Board_StatusLed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Board_StatusLed_CallInstance;
  char PLAT_Task_Create_IgnoreBool;
  bool PLAT_Task_Create_FinalReturn;
  char PLAT_Task_Create_CallbackBool;
  CMOCK_PLAT_Task_Create_CALLBACK PLAT_Task_Create_CallbackFunctionPointer;
  int PLAT_Task_Create_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PLAT_Task_Create_CallInstance;
  char PLAT_Task_TickNow_IgnoreBool;
  uint32_t PLAT_Task_TickNow_FinalReturn;
  char PLAT_Task_TickNow_CallbackBool;
  CMOCK_PLAT_Task_TickNow_CALLBACK PLAT_Task_TickNow_CallbackFunctionPointer;
  int PLAT_Task_TickNow_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PLAT_Task_TickNow_CallInstance;
  char PLAT_Task_DelayUntil_IgnoreBool;
  bool PLAT_Task_DelayUntil_FinalReturn;
  char PLAT_Task_DelayUntil_CallbackBool;
  CMOCK_PLAT_Task_DelayUntil_CALLBACK PLAT_Task_DelayUntil_CallbackFunctionPointer;
  int PLAT_Task_DelayUntil_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PLAT_Task_DelayUntil_CallInstance;
  char UTIL_Log_Write_IgnoreBool;
  char UTIL_Log_Write_CallbackBool;
  CMOCK_UTIL_Log_Write_CALLBACK UTIL_Log_Write_CallbackFunctionPointer;
  int UTIL_Log_Write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UTIL_Log_Write_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_indicator_contract_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Board_StatusLed_CallInstance;
  if (Mock.Board_StatusLed_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Board_StatusLed);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Board_StatusLed_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.PLAT_Task_Create_CallInstance;
  if (Mock.PLAT_Task_Create_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_Task_Create);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.PLAT_Task_Create_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.PLAT_Task_TickNow_CallInstance;
  if (Mock.PLAT_Task_TickNow_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_Task_TickNow);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.PLAT_Task_TickNow_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.PLAT_Task_DelayUntil_CallInstance;
  if (Mock.PLAT_Task_DelayUntil_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_Task_DelayUntil);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UTIL_Log_Write_CallInstance;
  if (Mock.UTIL_Log_Write_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UTIL_Log_Write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UTIL_Log_Write_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_indicator_contract_Init(void)
{
  mock_indicator_contract_Destroy();
}

void mock_indicator_contract_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

SPI_Instance_s* Board_StatusLed(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Board_StatusLed_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Board_StatusLed);
  cmock_call_instance = (CMOCK_Board_StatusLed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Board_StatusLed_CallInstance);
  Mock.Board_StatusLed_CallInstance = CMock_Guts_MemNext(Mock.Board_StatusLed_CallInstance);
  if (Mock.Board_StatusLed_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Board_StatusLed_FinalReturn;
    Mock.Board_StatusLed_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Board_StatusLed_CallbackBool &&
      Mock.Board_StatusLed_CallbackFunctionPointer != NULL)
  {
    SPI_Instance_s* cmock_cb_ret = Mock.Board_StatusLed_CallbackFunctionPointer(Mock.Board_StatusLed_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Board_StatusLed_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_Board_StatusLed);
    cmock_call_instance->ReturnVal = Mock.Board_StatusLed_CallbackFunctionPointer(Mock.Board_StatusLed_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Board_StatusLed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Instance_s* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Board_StatusLed_CALL_INSTANCE));
  CMOCK_Board_StatusLed_CALL_INSTANCE* cmock_call_instance = (CMOCK_Board_StatusLed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Board_StatusLed_CallInstance = CMock_Guts_MemChain(Mock.Board_StatusLed_CallInstance, cmock_guts_index);
  Mock.Board_StatusLed_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Board_StatusLed_IgnoreBool = (char)1;
}

void Board_StatusLed_CMockStopIgnore(void)
{
  if(Mock.Board_StatusLed_IgnoreBool)
    Mock.Board_StatusLed_CallInstance = CMock_Guts_MemNext(Mock.Board_StatusLed_CallInstance);
  Mock.Board_StatusLed_IgnoreBool = (char)0;
}

void Board_StatusLed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Instance_s* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Board_StatusLed_CALL_INSTANCE));
  CMOCK_Board_StatusLed_CALL_INSTANCE* cmock_call_instance = (CMOCK_Board_StatusLed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Board_StatusLed_CallInstance = CMock_Guts_MemChain(Mock.Board_StatusLed_CallInstance, cmock_guts_index);
  Mock.Board_StatusLed_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Board_StatusLed_AddCallback(CMOCK_Board_StatusLed_CALLBACK Callback)
{
  Mock.Board_StatusLed_IgnoreBool = (char)0;
  Mock.Board_StatusLed_CallbackBool = (char)1;
  Mock.Board_StatusLed_CallbackCalls = 0;
  Mock.Board_StatusLed_CallbackFunctionPointer = Callback;
}

int Board_StatusLed_CallCount(void)
{
  return Mock.Board_StatusLed_CallbackCalls;
}

void Board_StatusLed_Stub(CMOCK_Board_StatusLed_CALLBACK Callback)
{
  Mock.Board_StatusLed_IgnoreBool = (char)0;
  Mock.Board_StatusLed_CallbackBool = (char)0;
  Mock.Board_StatusLed_CallbackCalls = 0;
  Mock.Board_StatusLed_CallbackFunctionPointer = Callback;
}

bool PLAT_Task_Create(Task_s* task, PLAT_Task_Entry entry, void* arg, const char* name, void* stack, size_t stack_bytes, uint8_t priority)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PLAT_Task_Create);
  cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PLAT_Task_Create_CallInstance);
  Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemNext(Mock.PLAT_Task_Create_CallInstance);
  if (Mock.PLAT_Task_Create_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_task_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(task, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)task, (const void*)cmock_call_instance->ReturnThruPtr_task_Val,
      cmock_call_instance->ReturnThruPtr_task_Size);
  }
  if (Mock.PLAT_Task_Create_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_arg_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(arg, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)arg, (const void*)cmock_call_instance->ReturnThruPtr_arg_Val,
      cmock_call_instance->ReturnThruPtr_arg_Size);
  }
  if (Mock.PLAT_Task_Create_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_stack_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(stack, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)stack, (const void*)cmock_call_instance->ReturnThruPtr_stack_Val,
      cmock_call_instance->ReturnThruPtr_stack_Size);
  }
  if (Mock.PLAT_Task_Create_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.PLAT_Task_Create_FinalReturn;
    Mock.PLAT_Task_Create_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.PLAT_Task_Create_CallbackBool &&
      Mock.PLAT_Task_Create_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.PLAT_Task_Create_CallbackFunctionPointer(task, entry, arg, name, stack, stack_bytes, priority, Mock.PLAT_Task_Create_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_task)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_task);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_task, task, sizeof(Task_s), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_entry)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_entry);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_entry, &entry, sizeof(PLAT_Task_Entry), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_arg)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_arg);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_arg, arg, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_name)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_stack)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_stack);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_stack, stack, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_stack_bytes)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_stack_bytes);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_stack_bytes, &stack_bytes, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_priority)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_Create,CMockString_priority);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_priority, priority, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.PLAT_Task_Create_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_Task_Create);
    cmock_call_instance->ReturnVal = Mock.PLAT_Task_Create_CallbackFunctionPointer(task, entry, arg, name, stack, stack_bytes, priority, Mock.PLAT_Task_Create_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_task_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(task, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)task, (const void*)cmock_call_instance->ReturnThruPtr_task_Val,
      cmock_call_instance->ReturnThruPtr_task_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_arg_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(arg, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)arg, (const void*)cmock_call_instance->ReturnThruPtr_arg_Val,
      cmock_call_instance->ReturnThruPtr_arg_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_stack_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(stack, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)stack, (const void*)cmock_call_instance->ReturnThruPtr_stack_Val,
      cmock_call_instance->ReturnThruPtr_stack_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_PLAT_Task_Create(CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance, Task_s* task, PLAT_Task_Entry entry, void* arg, const char* name, void* stack, size_t stack_bytes, uint8_t priority);
void CMockExpectParameters_PLAT_Task_Create(CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance, Task_s* task, PLAT_Task_Entry entry, void* arg, const char* name, void* stack, size_t stack_bytes, uint8_t priority)
{
  cmock_call_instance->Expected_task = task;
  cmock_call_instance->IgnoreArg_task = 0;
  cmock_call_instance->ReturnThruPtr_task_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_entry), (const void*)(&entry),
         sizeof(PLAT_Task_Entry[sizeof(entry) == sizeof(PLAT_Task_Entry) ? 1 : -1])); /* add PLAT_Task_Entry to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_entry = 0;
  cmock_call_instance->Expected_arg = arg;
  cmock_call_instance->IgnoreArg_arg = 0;
  cmock_call_instance->ReturnThruPtr_arg_Used = 0;
  cmock_call_instance->Expected_name = name;
  cmock_call_instance->IgnoreArg_name = 0;
  cmock_call_instance->Expected_stack = stack;
  cmock_call_instance->IgnoreArg_stack = 0;
  cmock_call_instance->ReturnThruPtr_stack_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_stack_bytes), (const void*)(&stack_bytes),
         sizeof(size_t[sizeof(stack_bytes) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_stack_bytes = 0;
  cmock_call_instance->Expected_priority = priority;
  cmock_call_instance->IgnoreArg_priority = 0;
}

void PLAT_Task_Create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_Create_CALL_INSTANCE));
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_Create_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_Create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.PLAT_Task_Create_IgnoreBool = (char)1;
}

void PLAT_Task_Create_CMockStopIgnore(void)
{
  if(Mock.PLAT_Task_Create_IgnoreBool)
    Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemNext(Mock.PLAT_Task_Create_CallInstance);
  Mock.PLAT_Task_Create_IgnoreBool = (char)0;
}

void PLAT_Task_Create_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_Create_CALL_INSTANCE));
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_Create_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_Create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PLAT_Task_Create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Task_s* task, PLAT_Task_Entry entry, void* arg, const char* name, void* stack, size_t stack_bytes, uint8_t priority, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_Create_CALL_INSTANCE));
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_Create_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_Create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PLAT_Task_Create(cmock_call_instance, task, entry, arg, name, stack, stack_bytes, priority);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void PLAT_Task_Create_AddCallback(CMOCK_PLAT_Task_Create_CALLBACK Callback)
{
  Mock.PLAT_Task_Create_IgnoreBool = (char)0;
  Mock.PLAT_Task_Create_CallbackBool = (char)1;
  Mock.PLAT_Task_Create_CallbackCalls = 0;
  Mock.PLAT_Task_Create_CallbackFunctionPointer = Callback;
}

int PLAT_Task_Create_CallCount(void)
{
  return Mock.PLAT_Task_Create_CallbackCalls;
}

void PLAT_Task_Create_Stub(CMOCK_PLAT_Task_Create_CALLBACK Callback)
{
  Mock.PLAT_Task_Create_IgnoreBool = (char)0;
  Mock.PLAT_Task_Create_CallbackBool = (char)0;
  Mock.PLAT_Task_Create_CallbackCalls = 0;
  Mock.PLAT_Task_Create_CallbackFunctionPointer = Callback;
}

void PLAT_Task_Create_CMockReturnMemThruPtr_task(UNITY_LINE_TYPE cmock_line, Task_s const* task, size_t cmock_size)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  if (Mock.PLAT_Task_Create_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_task_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_Create_CALL_INSTANCE));
    CMOCK_PLAT_Task_Create_CALL_INSTANCE* new_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_Create_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_task_Used = 1;
  cmock_call_instance->ReturnThruPtr_task_Val = task;
  cmock_call_instance->ReturnThruPtr_task_Size = cmock_size;
}

void PLAT_Task_Create_CMockReturnMemThruPtr_arg(UNITY_LINE_TYPE cmock_line, void const* arg, size_t cmock_size)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  if (Mock.PLAT_Task_Create_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_arg_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_Create_CALL_INSTANCE));
    CMOCK_PLAT_Task_Create_CALL_INSTANCE* new_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_Create_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_arg_Used = 1;
  cmock_call_instance->ReturnThruPtr_arg_Val = arg;
  cmock_call_instance->ReturnThruPtr_arg_Size = cmock_size;
}

void PLAT_Task_Create_CMockReturnMemThruPtr_stack(UNITY_LINE_TYPE cmock_line, void const* stack, size_t cmock_size)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  if (Mock.PLAT_Task_Create_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_stack_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_Create_CALL_INSTANCE));
    CMOCK_PLAT_Task_Create_CALL_INSTANCE* new_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.PLAT_Task_Create_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_Create_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_stack_Used = 1;
  cmock_call_instance->ReturnThruPtr_stack_Val = stack;
  cmock_call_instance->ReturnThruPtr_stack_Size = cmock_size;
}

void PLAT_Task_Create_CMockIgnoreArg_task(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_task = 1;
}

void PLAT_Task_Create_CMockIgnoreArg_entry(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_entry = 1;
}

void PLAT_Task_Create_CMockIgnoreArg_arg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_arg = 1;
}

void PLAT_Task_Create_CMockIgnoreArg_name(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_name = 1;
}

void PLAT_Task_Create_CMockIgnoreArg_stack(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_stack = 1;
}

void PLAT_Task_Create_CMockIgnoreArg_stack_bytes(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_stack_bytes = 1;
}

void PLAT_Task_Create_CMockIgnoreArg_priority(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_Create_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_Create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_Create_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_priority = 1;
}

uint32_t PLAT_Task_TickNow(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PLAT_Task_TickNow_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PLAT_Task_TickNow);
  cmock_call_instance = (CMOCK_PLAT_Task_TickNow_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PLAT_Task_TickNow_CallInstance);
  Mock.PLAT_Task_TickNow_CallInstance = CMock_Guts_MemNext(Mock.PLAT_Task_TickNow_CallInstance);
  if (Mock.PLAT_Task_TickNow_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.PLAT_Task_TickNow_FinalReturn;
    Mock.PLAT_Task_TickNow_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.PLAT_Task_TickNow_CallbackBool &&
      Mock.PLAT_Task_TickNow_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.PLAT_Task_TickNow_CallbackFunctionPointer(Mock.PLAT_Task_TickNow_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.PLAT_Task_TickNow_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_Task_TickNow);
    cmock_call_instance->ReturnVal = Mock.PLAT_Task_TickNow_CallbackFunctionPointer(Mock.PLAT_Task_TickNow_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void PLAT_Task_TickNow_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_TickNow_CALL_INSTANCE));
  CMOCK_PLAT_Task_TickNow_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_TickNow_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_TickNow_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_TickNow_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_TickNow_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.PLAT_Task_TickNow_IgnoreBool = (char)1;
}

void PLAT_Task_TickNow_CMockStopIgnore(void)
{
  if(Mock.PLAT_Task_TickNow_IgnoreBool)
    Mock.PLAT_Task_TickNow_CallInstance = CMock_Guts_MemNext(Mock.PLAT_Task_TickNow_CallInstance);
  Mock.PLAT_Task_TickNow_IgnoreBool = (char)0;
}

void PLAT_Task_TickNow_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_TickNow_CALL_INSTANCE));
  CMOCK_PLAT_Task_TickNow_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_TickNow_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_TickNow_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_TickNow_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_TickNow_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void PLAT_Task_TickNow_AddCallback(CMOCK_PLAT_Task_TickNow_CALLBACK Callback)
{
  Mock.PLAT_Task_TickNow_IgnoreBool = (char)0;
  Mock.PLAT_Task_TickNow_CallbackBool = (char)1;
  Mock.PLAT_Task_TickNow_CallbackCalls = 0;
  Mock.PLAT_Task_TickNow_CallbackFunctionPointer = Callback;
}

int PLAT_Task_TickNow_CallCount(void)
{
  return Mock.PLAT_Task_TickNow_CallbackCalls;
}

void PLAT_Task_TickNow_Stub(CMOCK_PLAT_Task_TickNow_CALLBACK Callback)
{
  Mock.PLAT_Task_TickNow_IgnoreBool = (char)0;
  Mock.PLAT_Task_TickNow_CallbackBool = (char)0;
  Mock.PLAT_Task_TickNow_CallbackCalls = 0;
  Mock.PLAT_Task_TickNow_CallbackFunctionPointer = Callback;
}

bool PLAT_Task_DelayUntil(uint32_t* prev_tick, uint32_t period_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PLAT_Task_DelayUntil);
  cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PLAT_Task_DelayUntil_CallInstance);
  Mock.PLAT_Task_DelayUntil_CallInstance = CMock_Guts_MemNext(Mock.PLAT_Task_DelayUntil_CallInstance);
  if (Mock.PLAT_Task_DelayUntil_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_prev_tick_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(prev_tick, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)prev_tick, (const void*)cmock_call_instance->ReturnThruPtr_prev_tick_Val,
      cmock_call_instance->ReturnThruPtr_prev_tick_Size);
  }
  if (Mock.PLAT_Task_DelayUntil_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.PLAT_Task_DelayUntil_FinalReturn;
    Mock.PLAT_Task_DelayUntil_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.PLAT_Task_DelayUntil_CallbackBool &&
      Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer(prev_tick, period_ms, Mock.PLAT_Task_DelayUntil_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_prev_tick)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_DelayUntil,CMockString_prev_tick);
    if (cmock_call_instance->Expected_prev_tick == NULL)
      { UNITY_TEST_ASSERT_NULL(prev_tick, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_prev_tick, prev_tick, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_period_ms)
  {
    UNITY_SET_DETAILS(CMockString_PLAT_Task_DelayUntil,CMockString_period_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_period_ms, period_ms, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_PLAT_Task_DelayUntil);
    cmock_call_instance->ReturnVal = Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer(prev_tick, period_ms, Mock.PLAT_Task_DelayUntil_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_prev_tick_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(prev_tick, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)prev_tick, (const void*)cmock_call_instance->ReturnThruPtr_prev_tick_Val,
      cmock_call_instance->ReturnThruPtr_prev_tick_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_PLAT_Task_DelayUntil(CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance, uint32_t* prev_tick, uint32_t period_ms);
void CMockExpectParameters_PLAT_Task_DelayUntil(CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance, uint32_t* prev_tick, uint32_t period_ms)
{
  cmock_call_instance->Expected_prev_tick = prev_tick;
  cmock_call_instance->IgnoreArg_prev_tick = 0;
  cmock_call_instance->ReturnThruPtr_prev_tick_Used = 0;
  cmock_call_instance->Expected_period_ms = period_ms;
  cmock_call_instance->IgnoreArg_period_ms = 0;
}

void PLAT_Task_DelayUntil_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE));
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_DelayUntil_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_DelayUntil_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)1;
}

void PLAT_Task_DelayUntil_CMockStopIgnore(void)
{
  if(Mock.PLAT_Task_DelayUntil_IgnoreBool)
    Mock.PLAT_Task_DelayUntil_CallInstance = CMock_Guts_MemNext(Mock.PLAT_Task_DelayUntil_CallInstance);
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)0;
}

void PLAT_Task_DelayUntil_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE));
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_DelayUntil_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_DelayUntil_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PLAT_Task_DelayUntil_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* prev_tick, uint32_t period_ms, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE));
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PLAT_Task_DelayUntil_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_DelayUntil_CallInstance, cmock_guts_index);
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PLAT_Task_DelayUntil(cmock_call_instance, prev_tick, period_ms);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void PLAT_Task_DelayUntil_AddCallback(CMOCK_PLAT_Task_DelayUntil_CALLBACK Callback)
{
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)0;
  Mock.PLAT_Task_DelayUntil_CallbackBool = (char)1;
  Mock.PLAT_Task_DelayUntil_CallbackCalls = 0;
  Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer = Callback;
}

int PLAT_Task_DelayUntil_CallCount(void)
{
  return Mock.PLAT_Task_DelayUntil_CallbackCalls;
}

void PLAT_Task_DelayUntil_Stub(CMOCK_PLAT_Task_DelayUntil_CALLBACK Callback)
{
  Mock.PLAT_Task_DelayUntil_IgnoreBool = (char)0;
  Mock.PLAT_Task_DelayUntil_CallbackBool = (char)0;
  Mock.PLAT_Task_DelayUntil_CallbackCalls = 0;
  Mock.PLAT_Task_DelayUntil_CallbackFunctionPointer = Callback;
}

void PLAT_Task_DelayUntil_CMockReturnMemThruPtr_prev_tick(UNITY_LINE_TYPE cmock_line, uint32_t const* prev_tick, size_t cmock_size)
{
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_DelayUntil_CallInstance));
  if (Mock.PLAT_Task_DelayUntil_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_prev_tick_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE));
    CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* new_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.PLAT_Task_DelayUntil_CallInstance = CMock_Guts_MemChain(Mock.PLAT_Task_DelayUntil_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_prev_tick_Used = 1;
  cmock_call_instance->ReturnThruPtr_prev_tick_Val = prev_tick;
  cmock_call_instance->ReturnThruPtr_prev_tick_Size = cmock_size;
}

void PLAT_Task_DelayUntil_CMockIgnoreArg_prev_tick(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_DelayUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_prev_tick = 1;
}

void PLAT_Task_DelayUntil_CMockIgnoreArg_period_ms(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE* cmock_call_instance = (CMOCK_PLAT_Task_DelayUntil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PLAT_Task_DelayUntil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_period_ms = 1;
}

void UTIL_Log_Write(UTIL_Log_Level_e level, const char* tag, const char* fmt, ...)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UTIL_Log_Write);
  cmock_call_instance = (CMOCK_UTIL_Log_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UTIL_Log_Write_CallInstance);
  Mock.UTIL_Log_Write_CallInstance = CMock_Guts_MemNext(Mock.UTIL_Log_Write_CallInstance);
  if (Mock.UTIL_Log_Write_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UTIL_Log_Write_CallbackBool &&
      Mock.UTIL_Log_Write_CallbackFunctionPointer != NULL)
  {
    Mock.UTIL_Log_Write_CallbackFunctionPointer(level, tag, fmt, Mock.UTIL_Log_Write_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_level)
  {
    UNITY_SET_DETAILS(CMockString_UTIL_Log_Write,CMockString_level);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_level, &level, sizeof(UTIL_Log_Level_e), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_tag)
  {
    UNITY_SET_DETAILS(CMockString_UTIL_Log_Write,CMockString_tag);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_tag, tag, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_fmt)
  {
    UNITY_SET_DETAILS(CMockString_UTIL_Log_Write,CMockString_fmt);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_fmt, fmt, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.UTIL_Log_Write_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UTIL_Log_Write);
    Mock.UTIL_Log_Write_CallbackFunctionPointer(level, tag, fmt, Mock.UTIL_Log_Write_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UTIL_Log_Write(CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance, UTIL_Log_Level_e level, const char* tag, const char* fmt);
void CMockExpectParameters_UTIL_Log_Write(CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance, UTIL_Log_Level_e level, const char* tag, const char* fmt)
{
  memcpy((void*)(&cmock_call_instance->Expected_level), (const void*)(&level),
         sizeof(UTIL_Log_Level_e[sizeof(level) == sizeof(UTIL_Log_Level_e) ? 1 : -1])); /* add UTIL_Log_Level_e to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_level = 0;
  cmock_call_instance->Expected_tag = tag;
  cmock_call_instance->IgnoreArg_tag = 0;
  cmock_call_instance->Expected_fmt = fmt;
  cmock_call_instance->IgnoreArg_fmt = 0;
}

void UTIL_Log_Write_CMockIgnore(void)
{
  Mock.UTIL_Log_Write_IgnoreBool = (char)1;
}

void UTIL_Log_Write_CMockStopIgnore(void)
{
  Mock.UTIL_Log_Write_IgnoreBool = (char)0;
}

void UTIL_Log_Write_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UTIL_Log_Write_CALL_INSTANCE));
  CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_UTIL_Log_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UTIL_Log_Write_CallInstance = CMock_Guts_MemChain(Mock.UTIL_Log_Write_CallInstance, cmock_guts_index);
  Mock.UTIL_Log_Write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void UTIL_Log_Write_CMockExpect(UNITY_LINE_TYPE cmock_line, UTIL_Log_Level_e level, const char* tag, const char* fmt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UTIL_Log_Write_CALL_INSTANCE));
  CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_UTIL_Log_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UTIL_Log_Write_CallInstance = CMock_Guts_MemChain(Mock.UTIL_Log_Write_CallInstance, cmock_guts_index);
  Mock.UTIL_Log_Write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_UTIL_Log_Write(cmock_call_instance, level, tag, fmt);
}

void UTIL_Log_Write_AddCallback(CMOCK_UTIL_Log_Write_CALLBACK Callback)
{
  Mock.UTIL_Log_Write_IgnoreBool = (char)0;
  Mock.UTIL_Log_Write_CallbackBool = (char)1;
  Mock.UTIL_Log_Write_CallbackCalls = 0;
  Mock.UTIL_Log_Write_CallbackFunctionPointer = Callback;
}

int UTIL_Log_Write_CallCount(void)
{
  return Mock.UTIL_Log_Write_CallbackCalls;
}

void UTIL_Log_Write_Stub(CMOCK_UTIL_Log_Write_CALLBACK Callback)
{
  Mock.UTIL_Log_Write_IgnoreBool = (char)0;
  Mock.UTIL_Log_Write_CallbackBool = (char)0;
  Mock.UTIL_Log_Write_CallbackCalls = 0;
  Mock.UTIL_Log_Write_CallbackFunctionPointer = Callback;
}

void UTIL_Log_Write_CMockIgnoreArg_level(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_UTIL_Log_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UTIL_Log_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_level = 1;
}

void UTIL_Log_Write_CMockIgnoreArg_tag(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_UTIL_Log_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UTIL_Log_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_tag = 1;
}

void UTIL_Log_Write_CMockIgnoreArg_fmt(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UTIL_Log_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_UTIL_Log_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UTIL_Log_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_fmt = 1;
}

