/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_FREERTOS_H
#define _MOCK_FREERTOS_H

#include "unity.h"
#include "FreeRTOS.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_FreeRTOS_Init(void);
void mock_FreeRTOS_Destroy(void);
void mock_FreeRTOS_Verify(void);




#define xPortIsInsideInterrupt_Ignore() TEST_FAIL_MESSAGE("xPortIsInsideInterrupt requires _IgnoreAndReturn");
#define xPortIsInsideInterrupt_IgnoreAndReturn(cmock_retval) xPortIsInsideInterrupt_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xPortIsInsideInterrupt_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xPortIsInsideInterrupt_StopIgnore() xPortIsInsideInterrupt_CMockStopIgnore()
void xPortIsInsideInterrupt_CMockStopIgnore(void);
#define xPortIsInsideInterrupt_Expect() TEST_FAIL_MESSAGE("xPortIsInsideInterrupt requires _ExpectAndReturn");
#define xPortIsInsideInterrupt_ExpectAndReturn(cmock_retval) xPortIsInsideInterrupt_CMockExpectAndReturn(__LINE__, cmock_retval)
void xPortIsInsideInterrupt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
typedef BaseType_t (* CMOCK_xPortIsInsideInterrupt_CALLBACK)(int cmock_num_calls);
void xPortIsInsideInterrupt_AddCallback(CMOCK_xPortIsInsideInterrupt_CALLBACK Callback);
void xPortIsInsideInterrupt_Stub(CMOCK_xPortIsInsideInterrupt_CALLBACK Callback);
#define xPortIsInsideInterrupt_StubWithCallback xPortIsInsideInterrupt_Stub
int xPortIsInsideInterrupt_CallCount(void);
#define vPortYieldFromISR_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYieldFromISR requires _Ignore (not AndReturn)");
#define vPortYieldFromISR_Ignore() vPortYieldFromISR_CMockIgnore()
void vPortYieldFromISR_CMockIgnore(void);
#define vPortYieldFromISR_StopIgnore() vPortYieldFromISR_CMockStopIgnore()
void vPortYieldFromISR_CMockStopIgnore(void);
#define vPortYieldFromISR_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYieldFromISR requires _ExpectAnyArgs (not AndReturn)");
#define vPortYieldFromISR_ExpectAnyArgs() vPortYieldFromISR_CMockExpectAnyArgs(__LINE__)
void vPortYieldFromISR_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define vPortYieldFromISR_ExpectAndReturn(woken, cmock_retval) TEST_FAIL_MESSAGE("vPortYieldFromISR requires _Expect (not AndReturn)");
#define vPortYieldFromISR_Expect(woken) vPortYieldFromISR_CMockExpect(__LINE__, woken)
void vPortYieldFromISR_CMockExpect(UNITY_LINE_TYPE cmock_line, BaseType_t woken);
typedef void (* CMOCK_vPortYieldFromISR_CALLBACK)(BaseType_t woken, int cmock_num_calls);
void vPortYieldFromISR_AddCallback(CMOCK_vPortYieldFromISR_CALLBACK Callback);
void vPortYieldFromISR_Stub(CMOCK_vPortYieldFromISR_CALLBACK Callback);
#define vPortYieldFromISR_StubWithCallback vPortYieldFromISR_Stub
int vPortYieldFromISR_CallCount(void);
#define vPortYieldFromISR_IgnoreArg_woken() vPortYieldFromISR_CMockIgnoreArg_woken(__LINE__)
void vPortYieldFromISR_CMockIgnoreArg_woken(UNITY_LINE_TYPE cmock_line);
#define vPortYield_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYield requires _Ignore (not AndReturn)");
#define vPortYield_Ignore() vPortYield_CMockIgnore()
void vPortYield_CMockIgnore(void);
#define vPortYield_StopIgnore() vPortYield_CMockStopIgnore()
void vPortYield_CMockStopIgnore(void);
#define vPortYield_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vPortYield requires _Expect (not AndReturn)");
#define vPortYield_Expect() vPortYield_CMockExpect(__LINE__)
void vPortYield_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_vPortYield_CALLBACK)(int cmock_num_calls);
void vPortYield_AddCallback(CMOCK_vPortYield_CALLBACK Callback);
void vPortYield_Stub(CMOCK_vPortYield_CALLBACK Callback);
#define vPortYield_StubWithCallback vPortYield_Stub
int vPortYield_CallCount(void);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
