/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_semphr.h"

static const char* CMockString_sem = "sem";
static const char* CMockString_storage = "storage";
static const char* CMockString_timeout = "timeout";
static const char* CMockString_xSemaphoreCreateMutexStatic = "xSemaphoreCreateMutexStatic";
static const char* CMockString_xSemaphoreCreateRecursiveMutexStatic = "xSemaphoreCreateRecursiveMutexStatic";
static const char* CMockString_xSemaphoreGive = "xSemaphoreGive";
static const char* CMockString_xSemaphoreGiveRecursive = "xSemaphoreGiveRecursive";
static const char* CMockString_xSemaphoreTake = "xSemaphoreTake";
static const char* CMockString_xSemaphoreTakeRecursive = "xSemaphoreTakeRecursive";

typedef struct _CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  SemaphoreHandle_t ReturnVal;
  int CallOrder;
  StaticSemaphore_t* Expected_storage;
  char ReturnThruPtr_storage_Used;
  StaticSemaphore_t const* ReturnThruPtr_storage_Val;
  size_t ReturnThruPtr_storage_Size;
  char IgnoreArg_storage;

} CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE;

typedef struct _CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  SemaphoreHandle_t ReturnVal;
  int CallOrder;
  StaticSemaphore_t* Expected_storage;
  char ReturnThruPtr_storage_Used;
  StaticSemaphore_t const* ReturnThruPtr_storage_Val;
  size_t ReturnThruPtr_storage_Size;
  char IgnoreArg_storage;

} CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE;

typedef struct _CMOCK_xSemaphoreTake_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  BaseType_t ReturnVal;
  int CallOrder;
  SemaphoreHandle_t Expected_sem;
  TickType_t Expected_timeout;
  char IgnoreArg_sem;
  char IgnoreArg_timeout;

} CMOCK_xSemaphoreTake_CALL_INSTANCE;

typedef struct _CMOCK_xSemaphoreGive_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  BaseType_t ReturnVal;
  int CallOrder;
  SemaphoreHandle_t Expected_sem;
  char IgnoreArg_sem;

} CMOCK_xSemaphoreGive_CALL_INSTANCE;

typedef struct _CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  BaseType_t ReturnVal;
  int CallOrder;
  SemaphoreHandle_t Expected_sem;
  TickType_t Expected_timeout;
  char IgnoreArg_sem;
  char IgnoreArg_timeout;

} CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE;

typedef struct _CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  BaseType_t ReturnVal;
  int CallOrder;
  SemaphoreHandle_t Expected_sem;
  char IgnoreArg_sem;

} CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE;

static struct mock_semphrInstance
{
  char xSemaphoreCreateMutexStatic_IgnoreBool;
  SemaphoreHandle_t xSemaphoreCreateMutexStatic_FinalReturn;
  char xSemaphoreCreateMutexStatic_CallbackBool;
  CMOCK_xSemaphoreCreateMutexStatic_CALLBACK xSemaphoreCreateMutexStatic_CallbackFunctionPointer;
  int xSemaphoreCreateMutexStatic_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xSemaphoreCreateMutexStatic_CallInstance;
  char xSemaphoreCreateRecursiveMutexStatic_IgnoreBool;
  SemaphoreHandle_t xSemaphoreCreateRecursiveMutexStatic_FinalReturn;
  char xSemaphoreCreateRecursiveMutexStatic_CallbackBool;
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALLBACK xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer;
  int xSemaphoreCreateRecursiveMutexStatic_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xSemaphoreCreateRecursiveMutexStatic_CallInstance;
  char xSemaphoreTake_IgnoreBool;
  BaseType_t xSemaphoreTake_FinalReturn;
  char xSemaphoreTake_CallbackBool;
  CMOCK_xSemaphoreTake_CALLBACK xSemaphoreTake_CallbackFunctionPointer;
  int xSemaphoreTake_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xSemaphoreTake_CallInstance;
  char xSemaphoreGive_IgnoreBool;
  BaseType_t xSemaphoreGive_FinalReturn;
  char xSemaphoreGive_CallbackBool;
  CMOCK_xSemaphoreGive_CALLBACK xSemaphoreGive_CallbackFunctionPointer;
  int xSemaphoreGive_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xSemaphoreGive_CallInstance;
  char xSemaphoreTakeRecursive_IgnoreBool;
  BaseType_t xSemaphoreTakeRecursive_FinalReturn;
  char xSemaphoreTakeRecursive_CallbackBool;
  CMOCK_xSemaphoreTakeRecursive_CALLBACK xSemaphoreTakeRecursive_CallbackFunctionPointer;
  int xSemaphoreTakeRecursive_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xSemaphoreTakeRecursive_CallInstance;
  char xSemaphoreGiveRecursive_IgnoreBool;
  BaseType_t xSemaphoreGiveRecursive_FinalReturn;
  char xSemaphoreGiveRecursive_CallbackBool;
  CMOCK_xSemaphoreGiveRecursive_CALLBACK xSemaphoreGiveRecursive_CallbackFunctionPointer;
  int xSemaphoreGiveRecursive_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xSemaphoreGiveRecursive_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_semphr_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.xSemaphoreCreateMutexStatic_CallInstance;
  if (Mock.xSemaphoreCreateMutexStatic_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreCreateMutexStatic);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance;
  if (Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreCreateRecursiveMutexStatic);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.xSemaphoreTake_CallInstance;
  if (Mock.xSemaphoreTake_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreTake);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xSemaphoreTake_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.xSemaphoreGive_CallInstance;
  if (Mock.xSemaphoreGive_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreGive);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xSemaphoreGive_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.xSemaphoreTakeRecursive_CallInstance;
  if (Mock.xSemaphoreTakeRecursive_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreTakeRecursive);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.xSemaphoreGiveRecursive_CallInstance;
  if (Mock.xSemaphoreGiveRecursive_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreGiveRecursive);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_semphr_Init(void)
{
  mock_semphr_Destroy();
}

void mock_semphr_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

SemaphoreHandle_t xSemaphoreCreateMutexStatic(StaticSemaphore_t* storage)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xSemaphoreCreateMutexStatic);
  cmock_call_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xSemaphoreCreateMutexStatic_CallInstance);
  Mock.xSemaphoreCreateMutexStatic_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreCreateMutexStatic_CallInstance);
  if (Mock.xSemaphoreCreateMutexStatic_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  if (Mock.xSemaphoreCreateMutexStatic_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xSemaphoreCreateMutexStatic_FinalReturn;
    memcpy((void*)(&Mock.xSemaphoreCreateMutexStatic_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(SemaphoreHandle_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xSemaphoreCreateMutexStatic_CallbackBool &&
      Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer != NULL)
  {
    SemaphoreHandle_t cmock_cb_ret = Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer(storage, Mock.xSemaphoreCreateMutexStatic_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_storage)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreCreateMutexStatic,CMockString_storage);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_storage, storage, sizeof(StaticSemaphore_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreCreateMutexStatic);
    cmock_call_instance->ReturnVal = Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer(storage, Mock.xSemaphoreCreateMutexStatic_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_xSemaphoreCreateMutexStatic(CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance, StaticSemaphore_t* storage);
void CMockExpectParameters_xSemaphoreCreateMutexStatic(CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance, StaticSemaphore_t* storage)
{
  cmock_call_instance->Expected_storage = storage;
  cmock_call_instance->IgnoreArg_storage = 0;
  cmock_call_instance->ReturnThruPtr_storage_Used = 0;
}

void xSemaphoreCreateMutexStatic_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE));
  CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreCreateMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateMutexStatic_CallInstance, cmock_guts_index);
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)1;
}

void xSemaphoreCreateMutexStatic_CMockStopIgnore(void)
{
  if(Mock.xSemaphoreCreateMutexStatic_IgnoreBool)
    Mock.xSemaphoreCreateMutexStatic_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreCreateMutexStatic_CallInstance);
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)0;
}

void xSemaphoreCreateMutexStatic_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE));
  CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreCreateMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateMutexStatic_CallInstance, cmock_guts_index);
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void xSemaphoreCreateMutexStatic_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t* storage, SemaphoreHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE));
  CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreCreateMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateMutexStatic_CallInstance, cmock_guts_index);
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_xSemaphoreCreateMutexStatic(cmock_call_instance, storage);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(SemaphoreHandle_t[sizeof(cmock_to_return) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
}

void xSemaphoreCreateMutexStatic_AddCallback(CMOCK_xSemaphoreCreateMutexStatic_CALLBACK Callback)
{
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)0;
  Mock.xSemaphoreCreateMutexStatic_CallbackBool = (char)1;
  Mock.xSemaphoreCreateMutexStatic_CallbackCalls = 0;
  Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer = Callback;
}

int xSemaphoreCreateMutexStatic_CallCount(void)
{
  return Mock.xSemaphoreCreateMutexStatic_CallbackCalls;
}

void xSemaphoreCreateMutexStatic_Stub(CMOCK_xSemaphoreCreateMutexStatic_CALLBACK Callback)
{
  Mock.xSemaphoreCreateMutexStatic_IgnoreBool = (char)0;
  Mock.xSemaphoreCreateMutexStatic_CallbackBool = (char)0;
  Mock.xSemaphoreCreateMutexStatic_CallbackCalls = 0;
  Mock.xSemaphoreCreateMutexStatic_CallbackFunctionPointer = Callback;
}

void xSemaphoreCreateMutexStatic_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t const* storage, size_t cmock_size)
{
  CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreCreateMutexStatic_CallInstance));
  if (Mock.xSemaphoreCreateMutexStatic_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_storage_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE));
    CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* new_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.xSemaphoreCreateMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateMutexStatic_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_storage_Used = 1;
  cmock_call_instance->ReturnThruPtr_storage_Val = storage;
  cmock_call_instance->ReturnThruPtr_storage_Size = cmock_size;
}

void xSemaphoreCreateMutexStatic_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreCreateMutexStatic_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_storage = 1;
}

SemaphoreHandle_t xSemaphoreCreateRecursiveMutexStatic(StaticSemaphore_t* storage)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xSemaphoreCreateRecursiveMutexStatic);
  cmock_call_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance);
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance);
  if (Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  if (Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xSemaphoreCreateRecursiveMutexStatic_FinalReturn;
    memcpy((void*)(&Mock.xSemaphoreCreateRecursiveMutexStatic_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(SemaphoreHandle_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackBool &&
      Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer != NULL)
  {
    SemaphoreHandle_t cmock_cb_ret = Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer(storage, Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_storage)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreCreateRecursiveMutexStatic,CMockString_storage);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_storage, storage, sizeof(StaticSemaphore_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreCreateRecursiveMutexStatic);
    cmock_call_instance->ReturnVal = Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer(storage, Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_xSemaphoreCreateRecursiveMutexStatic(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance, StaticSemaphore_t* storage);
void CMockExpectParameters_xSemaphoreCreateRecursiveMutexStatic(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance, StaticSemaphore_t* storage)
{
  cmock_call_instance->Expected_storage = storage;
  cmock_call_instance->IgnoreArg_storage = 0;
  cmock_call_instance->ReturnThruPtr_storage_Used = 0;
}

void xSemaphoreCreateRecursiveMutexStatic_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE));
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance, cmock_guts_index);
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)1;
}

void xSemaphoreCreateRecursiveMutexStatic_CMockStopIgnore(void)
{
  if(Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool)
    Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance);
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)0;
}

void xSemaphoreCreateRecursiveMutexStatic_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE));
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance, cmock_guts_index);
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void xSemaphoreCreateRecursiveMutexStatic_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t* storage, SemaphoreHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE));
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance, cmock_guts_index);
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_xSemaphoreCreateRecursiveMutexStatic(cmock_call_instance, storage);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(SemaphoreHandle_t[sizeof(cmock_to_return) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
}

void xSemaphoreCreateRecursiveMutexStatic_AddCallback(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALLBACK Callback)
{
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)0;
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackBool = (char)1;
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackCalls = 0;
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer = Callback;
}

int xSemaphoreCreateRecursiveMutexStatic_CallCount(void)
{
  return Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackCalls;
}

void xSemaphoreCreateRecursiveMutexStatic_Stub(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALLBACK Callback)
{
  Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool = (char)0;
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackBool = (char)0;
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackCalls = 0;
  Mock.xSemaphoreCreateRecursiveMutexStatic_CallbackFunctionPointer = Callback;
}

void xSemaphoreCreateRecursiveMutexStatic_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t const* storage, size_t cmock_size)
{
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance));
  if (Mock.xSemaphoreCreateRecursiveMutexStatic_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_storage_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE));
    CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* new_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_storage_Used = 1;
  cmock_call_instance->ReturnThruPtr_storage_Val = storage;
  cmock_call_instance->ReturnThruPtr_storage_Size = cmock_size;
}

void xSemaphoreCreateRecursiveMutexStatic_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreCreateRecursiveMutexStatic_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_storage = 1;
}

BaseType_t xSemaphoreTake(SemaphoreHandle_t sem, TickType_t timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xSemaphoreTake);
  cmock_call_instance = (CMOCK_xSemaphoreTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xSemaphoreTake_CallInstance);
  Mock.xSemaphoreTake_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreTake_CallInstance);
  if (Mock.xSemaphoreTake_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xSemaphoreTake_FinalReturn;
    memcpy((void*)(&Mock.xSemaphoreTake_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(BaseType_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xSemaphoreTake_CallbackBool &&
      Mock.xSemaphoreTake_CallbackFunctionPointer != NULL)
  {
    BaseType_t cmock_cb_ret = Mock.xSemaphoreTake_CallbackFunctionPointer(sem, timeout, Mock.xSemaphoreTake_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreTake,CMockString_sem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_sem, &sem, sizeof(SemaphoreHandle_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreTake,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_timeout, &timeout, sizeof(TickType_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.xSemaphoreTake_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreTake);
    cmock_call_instance->ReturnVal = Mock.xSemaphoreTake_CallbackFunctionPointer(sem, timeout, Mock.xSemaphoreTake_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_xSemaphoreTake(CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem, TickType_t timeout);
void CMockExpectParameters_xSemaphoreTake(CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem, TickType_t timeout)
{
  memcpy((void*)(&cmock_call_instance->Expected_sem), (const void*)(&sem),
         sizeof(SemaphoreHandle_t[sizeof(sem) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_sem = 0;
  memcpy((void*)(&cmock_call_instance->Expected_timeout), (const void*)(&timeout),
         sizeof(TickType_t[sizeof(timeout) == sizeof(TickType_t) ? 1 : -1])); /* add TickType_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void xSemaphoreTake_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreTake_CALL_INSTANCE));
  CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreTake_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreTake_CallInstance, cmock_guts_index);
  Mock.xSemaphoreTake_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xSemaphoreTake_IgnoreBool = (char)1;
}

void xSemaphoreTake_CMockStopIgnore(void)
{
  if(Mock.xSemaphoreTake_IgnoreBool)
    Mock.xSemaphoreTake_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreTake_CallInstance);
  Mock.xSemaphoreTake_IgnoreBool = (char)0;
}

void xSemaphoreTake_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreTake_CALL_INSTANCE));
  CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreTake_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreTake_CallInstance, cmock_guts_index);
  Mock.xSemaphoreTake_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void xSemaphoreTake_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, TickType_t timeout, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreTake_CALL_INSTANCE));
  CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreTake_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreTake_CallInstance, cmock_guts_index);
  Mock.xSemaphoreTake_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_xSemaphoreTake(cmock_call_instance, sem, timeout);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(BaseType_t[sizeof(cmock_to_return) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
}

void xSemaphoreTake_AddCallback(CMOCK_xSemaphoreTake_CALLBACK Callback)
{
  Mock.xSemaphoreTake_IgnoreBool = (char)0;
  Mock.xSemaphoreTake_CallbackBool = (char)1;
  Mock.xSemaphoreTake_CallbackCalls = 0;
  Mock.xSemaphoreTake_CallbackFunctionPointer = Callback;
}

int xSemaphoreTake_CallCount(void)
{
  return Mock.xSemaphoreTake_CallbackCalls;
}

void xSemaphoreTake_Stub(CMOCK_xSemaphoreTake_CALLBACK Callback)
{
  Mock.xSemaphoreTake_IgnoreBool = (char)0;
  Mock.xSemaphoreTake_CallbackBool = (char)0;
  Mock.xSemaphoreTake_CallbackCalls = 0;
  Mock.xSemaphoreTake_CallbackFunctionPointer = Callback;
}

void xSemaphoreTake_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreTake_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

void xSemaphoreTake_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreTake_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreTake_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

BaseType_t xSemaphoreGive(SemaphoreHandle_t sem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xSemaphoreGive);
  cmock_call_instance = (CMOCK_xSemaphoreGive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xSemaphoreGive_CallInstance);
  Mock.xSemaphoreGive_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreGive_CallInstance);
  if (Mock.xSemaphoreGive_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xSemaphoreGive_FinalReturn;
    memcpy((void*)(&Mock.xSemaphoreGive_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(BaseType_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xSemaphoreGive_CallbackBool &&
      Mock.xSemaphoreGive_CallbackFunctionPointer != NULL)
  {
    BaseType_t cmock_cb_ret = Mock.xSemaphoreGive_CallbackFunctionPointer(sem, Mock.xSemaphoreGive_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreGive,CMockString_sem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_sem, &sem, sizeof(SemaphoreHandle_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.xSemaphoreGive_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreGive);
    cmock_call_instance->ReturnVal = Mock.xSemaphoreGive_CallbackFunctionPointer(sem, Mock.xSemaphoreGive_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_xSemaphoreGive(CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem);
void CMockExpectParameters_xSemaphoreGive(CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem)
{
  memcpy((void*)(&cmock_call_instance->Expected_sem), (const void*)(&sem),
         sizeof(SemaphoreHandle_t[sizeof(sem) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_sem = 0;
}

void xSemaphoreGive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreGive_CALL_INSTANCE));
  CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreGive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreGive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreGive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xSemaphoreGive_IgnoreBool = (char)1;
}

void xSemaphoreGive_CMockStopIgnore(void)
{
  if(Mock.xSemaphoreGive_IgnoreBool)
    Mock.xSemaphoreGive_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreGive_CallInstance);
  Mock.xSemaphoreGive_IgnoreBool = (char)0;
}

void xSemaphoreGive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreGive_CALL_INSTANCE));
  CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreGive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreGive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreGive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void xSemaphoreGive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreGive_CALL_INSTANCE));
  CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreGive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreGive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreGive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_xSemaphoreGive(cmock_call_instance, sem);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(BaseType_t[sizeof(cmock_to_return) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
}

void xSemaphoreGive_AddCallback(CMOCK_xSemaphoreGive_CALLBACK Callback)
{
  Mock.xSemaphoreGive_IgnoreBool = (char)0;
  Mock.xSemaphoreGive_CallbackBool = (char)1;
  Mock.xSemaphoreGive_CallbackCalls = 0;
  Mock.xSemaphoreGive_CallbackFunctionPointer = Callback;
}

int xSemaphoreGive_CallCount(void)
{
  return Mock.xSemaphoreGive_CallbackCalls;
}

void xSemaphoreGive_Stub(CMOCK_xSemaphoreGive_CALLBACK Callback)
{
  Mock.xSemaphoreGive_IgnoreBool = (char)0;
  Mock.xSemaphoreGive_CallbackBool = (char)0;
  Mock.xSemaphoreGive_CallbackCalls = 0;
  Mock.xSemaphoreGive_CallbackFunctionPointer = Callback;
}

void xSemaphoreGive_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreGive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreGive_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

BaseType_t xSemaphoreTakeRecursive(SemaphoreHandle_t sem, TickType_t timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xSemaphoreTakeRecursive);
  cmock_call_instance = (CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xSemaphoreTakeRecursive_CallInstance);
  Mock.xSemaphoreTakeRecursive_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreTakeRecursive_CallInstance);
  if (Mock.xSemaphoreTakeRecursive_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xSemaphoreTakeRecursive_FinalReturn;
    memcpy((void*)(&Mock.xSemaphoreTakeRecursive_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(BaseType_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xSemaphoreTakeRecursive_CallbackBool &&
      Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer != NULL)
  {
    BaseType_t cmock_cb_ret = Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer(sem, timeout, Mock.xSemaphoreTakeRecursive_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreTakeRecursive,CMockString_sem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_sem, &sem, sizeof(SemaphoreHandle_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreTakeRecursive,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_timeout, &timeout, sizeof(TickType_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreTakeRecursive);
    cmock_call_instance->ReturnVal = Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer(sem, timeout, Mock.xSemaphoreTakeRecursive_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_xSemaphoreTakeRecursive(CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem, TickType_t timeout);
void CMockExpectParameters_xSemaphoreTakeRecursive(CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem, TickType_t timeout)
{
  memcpy((void*)(&cmock_call_instance->Expected_sem), (const void*)(&sem),
         sizeof(SemaphoreHandle_t[sizeof(sem) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_sem = 0;
  memcpy((void*)(&cmock_call_instance->Expected_timeout), (const void*)(&timeout),
         sizeof(TickType_t[sizeof(timeout) == sizeof(TickType_t) ? 1 : -1])); /* add TickType_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void xSemaphoreTakeRecursive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE));
  CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreTakeRecursive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreTakeRecursive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)1;
}

void xSemaphoreTakeRecursive_CMockStopIgnore(void)
{
  if(Mock.xSemaphoreTakeRecursive_IgnoreBool)
    Mock.xSemaphoreTakeRecursive_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreTakeRecursive_CallInstance);
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)0;
}

void xSemaphoreTakeRecursive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE));
  CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreTakeRecursive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreTakeRecursive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void xSemaphoreTakeRecursive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, TickType_t timeout, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE));
  CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreTakeRecursive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreTakeRecursive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_xSemaphoreTakeRecursive(cmock_call_instance, sem, timeout);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(BaseType_t[sizeof(cmock_to_return) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
}

void xSemaphoreTakeRecursive_AddCallback(CMOCK_xSemaphoreTakeRecursive_CALLBACK Callback)
{
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)0;
  Mock.xSemaphoreTakeRecursive_CallbackBool = (char)1;
  Mock.xSemaphoreTakeRecursive_CallbackCalls = 0;
  Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer = Callback;
}

int xSemaphoreTakeRecursive_CallCount(void)
{
  return Mock.xSemaphoreTakeRecursive_CallbackCalls;
}

void xSemaphoreTakeRecursive_Stub(CMOCK_xSemaphoreTakeRecursive_CALLBACK Callback)
{
  Mock.xSemaphoreTakeRecursive_IgnoreBool = (char)0;
  Mock.xSemaphoreTakeRecursive_CallbackBool = (char)0;
  Mock.xSemaphoreTakeRecursive_CallbackCalls = 0;
  Mock.xSemaphoreTakeRecursive_CallbackFunctionPointer = Callback;
}

void xSemaphoreTakeRecursive_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreTakeRecursive_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

void xSemaphoreTakeRecursive_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreTakeRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreTakeRecursive_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

BaseType_t xSemaphoreGiveRecursive(SemaphoreHandle_t sem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xSemaphoreGiveRecursive);
  cmock_call_instance = (CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xSemaphoreGiveRecursive_CallInstance);
  Mock.xSemaphoreGiveRecursive_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreGiveRecursive_CallInstance);
  if (Mock.xSemaphoreGiveRecursive_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xSemaphoreGiveRecursive_FinalReturn;
    memcpy((void*)(&Mock.xSemaphoreGiveRecursive_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(BaseType_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xSemaphoreGiveRecursive_CallbackBool &&
      Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer != NULL)
  {
    BaseType_t cmock_cb_ret = Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer(sem, Mock.xSemaphoreGiveRecursive_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_xSemaphoreGiveRecursive,CMockString_sem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_sem, &sem, sizeof(SemaphoreHandle_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xSemaphoreGiveRecursive);
    cmock_call_instance->ReturnVal = Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer(sem, Mock.xSemaphoreGiveRecursive_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_xSemaphoreGiveRecursive(CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem);
void CMockExpectParameters_xSemaphoreGiveRecursive(CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance, SemaphoreHandle_t sem)
{
  memcpy((void*)(&cmock_call_instance->Expected_sem), (const void*)(&sem),
         sizeof(SemaphoreHandle_t[sizeof(sem) == sizeof(SemaphoreHandle_t) ? 1 : -1])); /* add SemaphoreHandle_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_sem = 0;
}

void xSemaphoreGiveRecursive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE));
  CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreGiveRecursive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreGiveRecursive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)1;
}

void xSemaphoreGiveRecursive_CMockStopIgnore(void)
{
  if(Mock.xSemaphoreGiveRecursive_IgnoreBool)
    Mock.xSemaphoreGiveRecursive_CallInstance = CMock_Guts_MemNext(Mock.xSemaphoreGiveRecursive_CallInstance);
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)0;
}

void xSemaphoreGiveRecursive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE));
  CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreGiveRecursive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreGiveRecursive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void xSemaphoreGiveRecursive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, BaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE));
  CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xSemaphoreGiveRecursive_CallInstance = CMock_Guts_MemChain(Mock.xSemaphoreGiveRecursive_CallInstance, cmock_guts_index);
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_xSemaphoreGiveRecursive(cmock_call_instance, sem);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(BaseType_t[sizeof(cmock_to_return) == sizeof(BaseType_t) ? 1 : -1])); /* add BaseType_t to :treat_as_array if this causes an error */
}

void xSemaphoreGiveRecursive_AddCallback(CMOCK_xSemaphoreGiveRecursive_CALLBACK Callback)
{
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)0;
  Mock.xSemaphoreGiveRecursive_CallbackBool = (char)1;
  Mock.xSemaphoreGiveRecursive_CallbackCalls = 0;
  Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer = Callback;
}

int xSemaphoreGiveRecursive_CallCount(void)
{
  return Mock.xSemaphoreGiveRecursive_CallbackCalls;
}

void xSemaphoreGiveRecursive_Stub(CMOCK_xSemaphoreGiveRecursive_CALLBACK Callback)
{
  Mock.xSemaphoreGiveRecursive_IgnoreBool = (char)0;
  Mock.xSemaphoreGiveRecursive_CallbackBool = (char)0;
  Mock.xSemaphoreGiveRecursive_CallbackCalls = 0;
  Mock.xSemaphoreGiveRecursive_CallbackFunctionPointer = Callback;
}

void xSemaphoreGiveRecursive_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE* cmock_call_instance = (CMOCK_xSemaphoreGiveRecursive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.xSemaphoreGiveRecursive_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

