/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SEMPHR_H
#define _MOCK_SEMPHR_H

#include "unity.h"
#include "semphr.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_semphr_Init(void);
void mock_semphr_Destroy(void);
void mock_semphr_Verify(void);




#define xSemaphoreCreateMutexStatic_Ignore() TEST_FAIL_MESSAGE("xSemaphoreCreateMutexStatic requires _IgnoreAndReturn");
#define xSemaphoreCreateMutexStatic_IgnoreAndReturn(cmock_retval) xSemaphoreCreateMutexStatic_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xSemaphoreCreateMutexStatic_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return);
#define xSemaphoreCreateMutexStatic_StopIgnore() xSemaphoreCreateMutexStatic_CMockStopIgnore()
void xSemaphoreCreateMutexStatic_CMockStopIgnore(void);
#define xSemaphoreCreateMutexStatic_ExpectAnyArgs() TEST_FAIL_MESSAGE("xSemaphoreCreateMutexStatic requires _ExpectAnyArgsAndReturn");
#define xSemaphoreCreateMutexStatic_ExpectAnyArgsAndReturn(cmock_retval) xSemaphoreCreateMutexStatic_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void xSemaphoreCreateMutexStatic_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return);
#define xSemaphoreCreateMutexStatic_Expect(storage) TEST_FAIL_MESSAGE("xSemaphoreCreateMutexStatic requires _ExpectAndReturn");
#define xSemaphoreCreateMutexStatic_ExpectAndReturn(storage, cmock_retval) xSemaphoreCreateMutexStatic_CMockExpectAndReturn(__LINE__, storage, cmock_retval)
void xSemaphoreCreateMutexStatic_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t* storage, SemaphoreHandle_t cmock_to_return);
typedef SemaphoreHandle_t (* CMOCK_xSemaphoreCreateMutexStatic_CALLBACK)(StaticSemaphore_t* storage, int cmock_num_calls);
void xSemaphoreCreateMutexStatic_AddCallback(CMOCK_xSemaphoreCreateMutexStatic_CALLBACK Callback);
void xSemaphoreCreateMutexStatic_Stub(CMOCK_xSemaphoreCreateMutexStatic_CALLBACK Callback);
#define xSemaphoreCreateMutexStatic_StubWithCallback xSemaphoreCreateMutexStatic_Stub
int xSemaphoreCreateMutexStatic_CallCount(void);
#define xSemaphoreCreateMutexStatic_ReturnThruPtr_storage(storage) xSemaphoreCreateMutexStatic_CMockReturnMemThruPtr_storage(__LINE__, storage, sizeof(StaticSemaphore_t))
#define xSemaphoreCreateMutexStatic_ReturnArrayThruPtr_storage(storage, cmock_len) xSemaphoreCreateMutexStatic_CMockReturnMemThruPtr_storage(__LINE__, storage, (cmock_len * sizeof(*storage)))
#define xSemaphoreCreateMutexStatic_ReturnMemThruPtr_storage(storage, cmock_size) xSemaphoreCreateMutexStatic_CMockReturnMemThruPtr_storage(__LINE__, storage, (cmock_size))
void xSemaphoreCreateMutexStatic_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t const* storage, size_t cmock_size);
#define xSemaphoreCreateMutexStatic_IgnoreArg_storage() xSemaphoreCreateMutexStatic_CMockIgnoreArg_storage(__LINE__)
void xSemaphoreCreateMutexStatic_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreCreateRecursiveMutexStatic_Ignore() TEST_FAIL_MESSAGE("xSemaphoreCreateRecursiveMutexStatic requires _IgnoreAndReturn");
#define xSemaphoreCreateRecursiveMutexStatic_IgnoreAndReturn(cmock_retval) xSemaphoreCreateRecursiveMutexStatic_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xSemaphoreCreateRecursiveMutexStatic_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return);
#define xSemaphoreCreateRecursiveMutexStatic_StopIgnore() xSemaphoreCreateRecursiveMutexStatic_CMockStopIgnore()
void xSemaphoreCreateRecursiveMutexStatic_CMockStopIgnore(void);
#define xSemaphoreCreateRecursiveMutexStatic_ExpectAnyArgs() TEST_FAIL_MESSAGE("xSemaphoreCreateRecursiveMutexStatic requires _ExpectAnyArgsAndReturn");
#define xSemaphoreCreateRecursiveMutexStatic_ExpectAnyArgsAndReturn(cmock_retval) xSemaphoreCreateRecursiveMutexStatic_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void xSemaphoreCreateRecursiveMutexStatic_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t cmock_to_return);
#define xSemaphoreCreateRecursiveMutexStatic_Expect(storage) TEST_FAIL_MESSAGE("xSemaphoreCreateRecursiveMutexStatic requires _ExpectAndReturn");
#define xSemaphoreCreateRecursiveMutexStatic_ExpectAndReturn(storage, cmock_retval) xSemaphoreCreateRecursiveMutexStatic_CMockExpectAndReturn(__LINE__, storage, cmock_retval)
void xSemaphoreCreateRecursiveMutexStatic_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t* storage, SemaphoreHandle_t cmock_to_return);
typedef SemaphoreHandle_t (* CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALLBACK)(StaticSemaphore_t* storage, int cmock_num_calls);
void xSemaphoreCreateRecursiveMutexStatic_AddCallback(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALLBACK Callback);
void xSemaphoreCreateRecursiveMutexStatic_Stub(CMOCK_xSemaphoreCreateRecursiveMutexStatic_CALLBACK Callback);
#define xSemaphoreCreateRecursiveMutexStatic_StubWithCallback xSemaphoreCreateRecursiveMutexStatic_Stub
int xSemaphoreCreateRecursiveMutexStatic_CallCount(void);
#define xSemaphoreCreateRecursiveMutexStatic_ReturnThruPtr_storage(storage) xSemaphoreCreateRecursiveMutexStatic_CMockReturnMemThruPtr_storage(__LINE__, storage, sizeof(StaticSemaphore_t))
#define xSemaphoreCreateRecursiveMutexStatic_ReturnArrayThruPtr_storage(storage, cmock_len) xSemaphoreCreateRecursiveMutexStatic_CMockReturnMemThruPtr_storage(__LINE__, storage, (cmock_len * sizeof(*storage)))
#define xSemaphoreCreateRecursiveMutexStatic_ReturnMemThruPtr_storage(storage, cmock_size) xSemaphoreCreateRecursiveMutexStatic_CMockReturnMemThruPtr_storage(__LINE__, storage, (cmock_size))
void xSemaphoreCreateRecursiveMutexStatic_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, StaticSemaphore_t const* storage, size_t cmock_size);
#define xSemaphoreCreateRecursiveMutexStatic_IgnoreArg_storage() xSemaphoreCreateRecursiveMutexStatic_CMockIgnoreArg_storage(__LINE__)
void xSemaphoreCreateRecursiveMutexStatic_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreTake_Ignore() TEST_FAIL_MESSAGE("xSemaphoreTake requires _IgnoreAndReturn");
#define xSemaphoreTake_IgnoreAndReturn(cmock_retval) xSemaphoreTake_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xSemaphoreTake_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreTake_StopIgnore() xSemaphoreTake_CMockStopIgnore()
void xSemaphoreTake_CMockStopIgnore(void);
#define xSemaphoreTake_ExpectAnyArgs() TEST_FAIL_MESSAGE("xSemaphoreTake requires _ExpectAnyArgsAndReturn");
#define xSemaphoreTake_ExpectAnyArgsAndReturn(cmock_retval) xSemaphoreTake_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void xSemaphoreTake_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreTake_Expect(sem, timeout) TEST_FAIL_MESSAGE("xSemaphoreTake requires _ExpectAndReturn");
#define xSemaphoreTake_ExpectAndReturn(sem, timeout, cmock_retval) xSemaphoreTake_CMockExpectAndReturn(__LINE__, sem, timeout, cmock_retval)
void xSemaphoreTake_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, TickType_t timeout, BaseType_t cmock_to_return);
typedef BaseType_t (* CMOCK_xSemaphoreTake_CALLBACK)(SemaphoreHandle_t sem, TickType_t timeout, int cmock_num_calls);
void xSemaphoreTake_AddCallback(CMOCK_xSemaphoreTake_CALLBACK Callback);
void xSemaphoreTake_Stub(CMOCK_xSemaphoreTake_CALLBACK Callback);
#define xSemaphoreTake_StubWithCallback xSemaphoreTake_Stub
int xSemaphoreTake_CallCount(void);
#define xSemaphoreTake_IgnoreArg_sem() xSemaphoreTake_CMockIgnoreArg_sem(__LINE__)
void xSemaphoreTake_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreTake_IgnoreArg_timeout() xSemaphoreTake_CMockIgnoreArg_timeout(__LINE__)
void xSemaphoreTake_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreGive_Ignore() TEST_FAIL_MESSAGE("xSemaphoreGive requires _IgnoreAndReturn");
#define xSemaphoreGive_IgnoreAndReturn(cmock_retval) xSemaphoreGive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xSemaphoreGive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreGive_StopIgnore() xSemaphoreGive_CMockStopIgnore()
void xSemaphoreGive_CMockStopIgnore(void);
#define xSemaphoreGive_ExpectAnyArgs() TEST_FAIL_MESSAGE("xSemaphoreGive requires _ExpectAnyArgsAndReturn");
#define xSemaphoreGive_ExpectAnyArgsAndReturn(cmock_retval) xSemaphoreGive_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void xSemaphoreGive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreGive_Expect(sem) TEST_FAIL_MESSAGE("xSemaphoreGive requires _ExpectAndReturn");
#define xSemaphoreGive_ExpectAndReturn(sem, cmock_retval) xSemaphoreGive_CMockExpectAndReturn(__LINE__, sem, cmock_retval)
void xSemaphoreGive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, BaseType_t cmock_to_return);
typedef BaseType_t (* CMOCK_xSemaphoreGive_CALLBACK)(SemaphoreHandle_t sem, int cmock_num_calls);
void xSemaphoreGive_AddCallback(CMOCK_xSemaphoreGive_CALLBACK Callback);
void xSemaphoreGive_Stub(CMOCK_xSemaphoreGive_CALLBACK Callback);
#define xSemaphoreGive_StubWithCallback xSemaphoreGive_Stub
int xSemaphoreGive_CallCount(void);
#define xSemaphoreGive_IgnoreArg_sem() xSemaphoreGive_CMockIgnoreArg_sem(__LINE__)
void xSemaphoreGive_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreTakeRecursive_Ignore() TEST_FAIL_MESSAGE("xSemaphoreTakeRecursive requires _IgnoreAndReturn");
#define xSemaphoreTakeRecursive_IgnoreAndReturn(cmock_retval) xSemaphoreTakeRecursive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xSemaphoreTakeRecursive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreTakeRecursive_StopIgnore() xSemaphoreTakeRecursive_CMockStopIgnore()
void xSemaphoreTakeRecursive_CMockStopIgnore(void);
#define xSemaphoreTakeRecursive_ExpectAnyArgs() TEST_FAIL_MESSAGE("xSemaphoreTakeRecursive requires _ExpectAnyArgsAndReturn");
#define xSemaphoreTakeRecursive_ExpectAnyArgsAndReturn(cmock_retval) xSemaphoreTakeRecursive_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void xSemaphoreTakeRecursive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreTakeRecursive_Expect(sem, timeout) TEST_FAIL_MESSAGE("xSemaphoreTakeRecursive requires _ExpectAndReturn");
#define xSemaphoreTakeRecursive_ExpectAndReturn(sem, timeout, cmock_retval) xSemaphoreTakeRecursive_CMockExpectAndReturn(__LINE__, sem, timeout, cmock_retval)
void xSemaphoreTakeRecursive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, TickType_t timeout, BaseType_t cmock_to_return);
typedef BaseType_t (* CMOCK_xSemaphoreTakeRecursive_CALLBACK)(SemaphoreHandle_t sem, TickType_t timeout, int cmock_num_calls);
void xSemaphoreTakeRecursive_AddCallback(CMOCK_xSemaphoreTakeRecursive_CALLBACK Callback);
void xSemaphoreTakeRecursive_Stub(CMOCK_xSemaphoreTakeRecursive_CALLBACK Callback);
#define xSemaphoreTakeRecursive_StubWithCallback xSemaphoreTakeRecursive_Stub
int xSemaphoreTakeRecursive_CallCount(void);
#define xSemaphoreTakeRecursive_IgnoreArg_sem() xSemaphoreTakeRecursive_CMockIgnoreArg_sem(__LINE__)
void xSemaphoreTakeRecursive_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreTakeRecursive_IgnoreArg_timeout() xSemaphoreTakeRecursive_CMockIgnoreArg_timeout(__LINE__)
void xSemaphoreTakeRecursive_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define xSemaphoreGiveRecursive_Ignore() TEST_FAIL_MESSAGE("xSemaphoreGiveRecursive requires _IgnoreAndReturn");
#define xSemaphoreGiveRecursive_IgnoreAndReturn(cmock_retval) xSemaphoreGiveRecursive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xSemaphoreGiveRecursive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreGiveRecursive_StopIgnore() xSemaphoreGiveRecursive_CMockStopIgnore()
void xSemaphoreGiveRecursive_CMockStopIgnore(void);
#define xSemaphoreGiveRecursive_ExpectAnyArgs() TEST_FAIL_MESSAGE("xSemaphoreGiveRecursive requires _ExpectAnyArgsAndReturn");
#define xSemaphoreGiveRecursive_ExpectAnyArgsAndReturn(cmock_retval) xSemaphoreGiveRecursive_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void xSemaphoreGiveRecursive_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, BaseType_t cmock_to_return);
#define xSemaphoreGiveRecursive_Expect(sem) TEST_FAIL_MESSAGE("xSemaphoreGiveRecursive requires _ExpectAndReturn");
#define xSemaphoreGiveRecursive_ExpectAndReturn(sem, cmock_retval) xSemaphoreGiveRecursive_CMockExpectAndReturn(__LINE__, sem, cmock_retval)
void xSemaphoreGiveRecursive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SemaphoreHandle_t sem, BaseType_t cmock_to_return);
typedef BaseType_t (* CMOCK_xSemaphoreGiveRecursive_CALLBACK)(SemaphoreHandle_t sem, int cmock_num_calls);
void xSemaphoreGiveRecursive_AddCallback(CMOCK_xSemaphoreGiveRecursive_CALLBACK Callback);
void xSemaphoreGiveRecursive_Stub(CMOCK_xSemaphoreGiveRecursive_CALLBACK Callback);
#define xSemaphoreGiveRecursive_StubWithCallback xSemaphoreGiveRecursive_Stub
int xSemaphoreGiveRecursive_CallCount(void);
#define xSemaphoreGiveRecursive_IgnoreArg_sem() xSemaphoreGiveRecursive_CMockIgnoreArg_sem(__LINE__)
void xSemaphoreGiveRecursive_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
