/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_PLAT_TASK_H
#define _MOCK_PLAT_TASK_H

#include "unity.h"
#include "plat_task.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_plat_task_Init(void);
void mock_plat_task_Destroy(void);
void mock_plat_task_Verify(void);




#define PLAT_Task_Current_Ignore() TEST_FAIL_MESSAGE("PLAT_Task_Current requires _IgnoreAndReturn");
#define PLAT_Task_Current_IgnoreAndReturn(cmock_retval) PLAT_Task_Current_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_Task_Current_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
#define PLAT_Task_Current_StopIgnore() PLAT_Task_Current_CMockStopIgnore()
void PLAT_Task_Current_CMockStopIgnore(void);
#define PLAT_Task_Current_Expect() TEST_FAIL_MESSAGE("PLAT_Task_Current requires _ExpectAndReturn");
#define PLAT_Task_Current_ExpectAndReturn(cmock_retval) PLAT_Task_Current_CMockExpectAndReturn(__LINE__, cmock_retval)
void PLAT_Task_Current_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return);
typedef void* (* CMOCK_PLAT_Task_Current_CALLBACK)(int cmock_num_calls);
void PLAT_Task_Current_AddCallback(CMOCK_PLAT_Task_Current_CALLBACK Callback);
void PLAT_Task_Current_Stub(CMOCK_PLAT_Task_Current_CALLBACK Callback);
#define PLAT_Task_Current_StubWithCallback PLAT_Task_Current_Stub
int PLAT_Task_Current_CallCount(void);
#define PLAT_Task_Notify_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("PLAT_Task_Notify requires _Ignore (not AndReturn)");
#define PLAT_Task_Notify_Ignore() PLAT_Task_Notify_CMockIgnore()
void PLAT_Task_Notify_CMockIgnore(void);
#define PLAT_Task_Notify_StopIgnore() PLAT_Task_Notify_CMockStopIgnore()
void PLAT_Task_Notify_CMockStopIgnore(void);
#define PLAT_Task_Notify_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("PLAT_Task_Notify requires _ExpectAnyArgs (not AndReturn)");
#define PLAT_Task_Notify_ExpectAnyArgs() PLAT_Task_Notify_CMockExpectAnyArgs(__LINE__)
void PLAT_Task_Notify_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Notify_ExpectAndReturn(task, cmock_retval) TEST_FAIL_MESSAGE("PLAT_Task_Notify requires _Expect (not AndReturn)");
#define PLAT_Task_Notify_Expect(task) PLAT_Task_Notify_CMockExpect(__LINE__, task)
void PLAT_Task_Notify_CMockExpect(UNITY_LINE_TYPE cmock_line, void* task);
typedef void (* CMOCK_PLAT_Task_Notify_CALLBACK)(void* task, int cmock_num_calls);
void PLAT_Task_Notify_AddCallback(CMOCK_PLAT_Task_Notify_CALLBACK Callback);
void PLAT_Task_Notify_Stub(CMOCK_PLAT_Task_Notify_CALLBACK Callback);
#define PLAT_Task_Notify_StubWithCallback PLAT_Task_Notify_Stub
int PLAT_Task_Notify_CallCount(void);
#define PLAT_Task_Notify_ReturnThruPtr_task(task) PLAT_Task_Notify_CMockReturnMemThruPtr_task(__LINE__, task, sizeof(*task))
#define PLAT_Task_Notify_ReturnArrayThruPtr_task(task, cmock_len) PLAT_Task_Notify_CMockReturnMemThruPtr_task(__LINE__, task, (cmock_len * sizeof(*task)))
#define PLAT_Task_Notify_ReturnMemThruPtr_task(task, cmock_size) PLAT_Task_Notify_CMockReturnMemThruPtr_task(__LINE__, task, (cmock_size))
void PLAT_Task_Notify_CMockReturnMemThruPtr_task(UNITY_LINE_TYPE cmock_line, void const* task, size_t cmock_size);
#define PLAT_Task_Notify_IgnoreArg_task() PLAT_Task_Notify_CMockIgnoreArg_task(__LINE__)
void PLAT_Task_Notify_CMockIgnoreArg_task(UNITY_LINE_TYPE cmock_line);
#define PLAT_Task_Wait_Ignore() TEST_FAIL_MESSAGE("PLAT_Task_Wait requires _IgnoreAndReturn");
#define PLAT_Task_Wait_IgnoreAndReturn(cmock_retval) PLAT_Task_Wait_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PLAT_Task_Wait_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Task_Wait_StopIgnore() PLAT_Task_Wait_CMockStopIgnore()
void PLAT_Task_Wait_CMockStopIgnore(void);
#define PLAT_Task_Wait_ExpectAnyArgs() TEST_FAIL_MESSAGE("PLAT_Task_Wait requires _ExpectAnyArgsAndReturn");
#define PLAT_Task_Wait_ExpectAnyArgsAndReturn(cmock_retval) PLAT_Task_Wait_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PLAT_Task_Wait_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define PLAT_Task_Wait_Expect(timeout_ms) TEST_FAIL_MESSAGE("PLAT_Task_Wait requires _ExpectAndReturn");
#define PLAT_Task_Wait_ExpectAndReturn(timeout_ms, cmock_retval) PLAT_Task_Wait_CMockExpectAndReturn(__LINE__, timeout_ms, cmock_retval)
void PLAT_Task_Wait_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t timeout_ms, bool cmock_to_return);
typedef bool (* CMOCK_PLAT_Task_Wait_CALLBACK)(uint32_t timeout_ms, int cmock_num_calls);
void PLAT_Task_Wait_AddCallback(CMOCK_PLAT_Task_Wait_CALLBACK Callback);
void PLAT_Task_Wait_Stub(CMOCK_PLAT_Task_Wait_CALLBACK Callback);
#define PLAT_Task_Wait_StubWithCallback PLAT_Task_Wait_Stub
int PLAT_Task_Wait_CallCount(void);
#define PLAT_Task_Wait_IgnoreArg_timeout_ms() PLAT_Task_Wait_CMockIgnoreArg_timeout_ms(__LINE__)
void PLAT_Task_Wait_CMockIgnoreArg_timeout_ms(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
