/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_SEGGER_RTT.h"

static const char* CMockString_SEGGER_RTT_WriteString = "SEGGER_RTT_WriteString";
static const char* CMockString_SEGGER_RTT_printf = "SEGGER_RTT_printf";
static const char* CMockString_SEGGER_RTT_vprintf = "SEGGER_RTT_vprintf";
static const char* CMockString_args = "args";
static const char* CMockString_buffer_index = "buffer_index";
static const char* CMockString_format = "format";
static const char* CMockString_text = "text";

typedef struct _CMOCK_SEGGER_RTT_printf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  int CallOrder;
  unsigned Expected_buffer_index;
  const char* Expected_format;
  char IgnoreArg_buffer_index;
  char IgnoreArg_format;

} CMOCK_SEGGER_RTT_printf_CALL_INSTANCE;

typedef struct _CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  int CallOrder;
  unsigned Expected_buffer_index;
  const char* Expected_format;
  va_list* Expected_args;
  char ReturnThruPtr_args_Used;
  va_list const* ReturnThruPtr_args_Val;
  size_t ReturnThruPtr_args_Size;
  char IgnoreArg_buffer_index;
  char IgnoreArg_format;
  char IgnoreArg_args;

} CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE;

typedef struct _CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned ReturnVal;
  int CallOrder;
  unsigned Expected_buffer_index;
  const char* Expected_text;
  char IgnoreArg_buffer_index;
  char IgnoreArg_text;

} CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE;

static struct mock_SEGGER_RTTInstance
{
  char SEGGER_RTT_printf_IgnoreBool;
  int SEGGER_RTT_printf_FinalReturn;
  char SEGGER_RTT_printf_CallbackBool;
  CMOCK_SEGGER_RTT_printf_CALLBACK SEGGER_RTT_printf_CallbackFunctionPointer;
  int SEGGER_RTT_printf_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SEGGER_RTT_printf_CallInstance;
  char SEGGER_RTT_vprintf_IgnoreBool;
  int SEGGER_RTT_vprintf_FinalReturn;
  char SEGGER_RTT_vprintf_CallbackBool;
  CMOCK_SEGGER_RTT_vprintf_CALLBACK SEGGER_RTT_vprintf_CallbackFunctionPointer;
  int SEGGER_RTT_vprintf_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SEGGER_RTT_vprintf_CallInstance;
  char SEGGER_RTT_WriteString_IgnoreBool;
  unsigned SEGGER_RTT_WriteString_FinalReturn;
  char SEGGER_RTT_WriteString_CallbackBool;
  CMOCK_SEGGER_RTT_WriteString_CALLBACK SEGGER_RTT_WriteString_CallbackFunctionPointer;
  int SEGGER_RTT_WriteString_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SEGGER_RTT_WriteString_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_SEGGER_RTT_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SEGGER_RTT_printf_CallInstance;
  if (Mock.SEGGER_RTT_printf_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SEGGER_RTT_printf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SEGGER_RTT_printf_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SEGGER_RTT_vprintf_CallInstance;
  if (Mock.SEGGER_RTT_vprintf_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SEGGER_RTT_vprintf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SEGGER_RTT_WriteString_CallInstance;
  if (Mock.SEGGER_RTT_WriteString_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SEGGER_RTT_WriteString);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_SEGGER_RTT_Init(void)
{
  mock_SEGGER_RTT_Destroy();
}

void mock_SEGGER_RTT_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

int SEGGER_RTT_printf(unsigned buffer_index, const char* format, ...)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SEGGER_RTT_printf);
  cmock_call_instance = (CMOCK_SEGGER_RTT_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SEGGER_RTT_printf_CallInstance);
  Mock.SEGGER_RTT_printf_CallInstance = CMock_Guts_MemNext(Mock.SEGGER_RTT_printf_CallInstance);
  if (Mock.SEGGER_RTT_printf_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SEGGER_RTT_printf_FinalReturn;
    Mock.SEGGER_RTT_printf_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SEGGER_RTT_printf_CallbackBool &&
      Mock.SEGGER_RTT_printf_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.SEGGER_RTT_printf_CallbackFunctionPointer(buffer_index, format, Mock.SEGGER_RTT_printf_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_buffer_index)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_printf,CMockString_buffer_index);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_buffer_index, &buffer_index, sizeof(unsigned), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_format)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_printf,CMockString_format);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_format, format, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SEGGER_RTT_printf_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SEGGER_RTT_printf);
    cmock_call_instance->ReturnVal = Mock.SEGGER_RTT_printf_CallbackFunctionPointer(buffer_index, format, Mock.SEGGER_RTT_printf_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SEGGER_RTT_printf(CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance, unsigned buffer_index, const char* format);
void CMockExpectParameters_SEGGER_RTT_printf(CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance, unsigned buffer_index, const char* format)
{
  memcpy((void*)(&cmock_call_instance->Expected_buffer_index), (const void*)(&buffer_index),
         sizeof(unsigned[sizeof(buffer_index) == sizeof(unsigned) ? 1 : -1])); /* add unsigned to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_buffer_index = 0;
  cmock_call_instance->Expected_format = format;
  cmock_call_instance->IgnoreArg_format = 0;
}

void SEGGER_RTT_printf_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_printf_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_printf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_printf_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)1;
}

void SEGGER_RTT_printf_CMockStopIgnore(void)
{
  if(Mock.SEGGER_RTT_printf_IgnoreBool)
    Mock.SEGGER_RTT_printf_CallInstance = CMock_Guts_MemNext(Mock.SEGGER_RTT_printf_CallInstance);
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)0;
}

void SEGGER_RTT_printf_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_printf_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_printf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_printf_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SEGGER_RTT_printf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned buffer_index, const char* format, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_printf_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_printf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_printf_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SEGGER_RTT_printf(cmock_call_instance, buffer_index, format);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SEGGER_RTT_printf_AddCallback(CMOCK_SEGGER_RTT_printf_CALLBACK Callback)
{
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)0;
  Mock.SEGGER_RTT_printf_CallbackBool = (char)1;
  Mock.SEGGER_RTT_printf_CallbackCalls = 0;
  Mock.SEGGER_RTT_printf_CallbackFunctionPointer = Callback;
}

int SEGGER_RTT_printf_CallCount(void)
{
  return Mock.SEGGER_RTT_printf_CallbackCalls;
}

void SEGGER_RTT_printf_Stub(CMOCK_SEGGER_RTT_printf_CALLBACK Callback)
{
  Mock.SEGGER_RTT_printf_IgnoreBool = (char)0;
  Mock.SEGGER_RTT_printf_CallbackBool = (char)0;
  Mock.SEGGER_RTT_printf_CallbackCalls = 0;
  Mock.SEGGER_RTT_printf_CallbackFunctionPointer = Callback;
}

void SEGGER_RTT_printf_CMockIgnoreArg_buffer_index(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_printf_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer_index = 1;
}

void SEGGER_RTT_printf_CMockIgnoreArg_format(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_printf_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_format = 1;
}

int SEGGER_RTT_vprintf(unsigned buffer_index, const char* format, va_list* args)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SEGGER_RTT_vprintf);
  cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SEGGER_RTT_vprintf_CallInstance);
  Mock.SEGGER_RTT_vprintf_CallInstance = CMock_Guts_MemNext(Mock.SEGGER_RTT_vprintf_CallInstance);
  if (Mock.SEGGER_RTT_vprintf_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_args_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(args, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)args, (const void*)cmock_call_instance->ReturnThruPtr_args_Val,
      cmock_call_instance->ReturnThruPtr_args_Size);
  }
  if (Mock.SEGGER_RTT_vprintf_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SEGGER_RTT_vprintf_FinalReturn;
    Mock.SEGGER_RTT_vprintf_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SEGGER_RTT_vprintf_CallbackBool &&
      Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer(buffer_index, format, args, Mock.SEGGER_RTT_vprintf_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_buffer_index)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_vprintf,CMockString_buffer_index);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_buffer_index, &buffer_index, sizeof(unsigned), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_format)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_vprintf,CMockString_format);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_format, format, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_args)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_vprintf,CMockString_args);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_args, args, sizeof(va_list), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SEGGER_RTT_vprintf);
    cmock_call_instance->ReturnVal = Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer(buffer_index, format, args, Mock.SEGGER_RTT_vprintf_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_args_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(args, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)args, (const void*)cmock_call_instance->ReturnThruPtr_args_Val,
      cmock_call_instance->ReturnThruPtr_args_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SEGGER_RTT_vprintf(CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance, unsigned buffer_index, const char* format, va_list* args);
void CMockExpectParameters_SEGGER_RTT_vprintf(CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance, unsigned buffer_index, const char* format, va_list* args)
{
  memcpy((void*)(&cmock_call_instance->Expected_buffer_index), (const void*)(&buffer_index),
         sizeof(unsigned[sizeof(buffer_index) == sizeof(unsigned) ? 1 : -1])); /* add unsigned to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_buffer_index = 0;
  cmock_call_instance->Expected_format = format;
  cmock_call_instance->IgnoreArg_format = 0;
  cmock_call_instance->Expected_args = args;
  cmock_call_instance->IgnoreArg_args = 0;
  cmock_call_instance->ReturnThruPtr_args_Used = 0;
}

void SEGGER_RTT_vprintf_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_vprintf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_vprintf_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)1;
}

void SEGGER_RTT_vprintf_CMockStopIgnore(void)
{
  if(Mock.SEGGER_RTT_vprintf_IgnoreBool)
    Mock.SEGGER_RTT_vprintf_CallInstance = CMock_Guts_MemNext(Mock.SEGGER_RTT_vprintf_CallInstance);
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)0;
}

void SEGGER_RTT_vprintf_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_vprintf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_vprintf_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SEGGER_RTT_vprintf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned buffer_index, const char* format, va_list* args, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_vprintf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_vprintf_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SEGGER_RTT_vprintf(cmock_call_instance, buffer_index, format, args);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SEGGER_RTT_vprintf_AddCallback(CMOCK_SEGGER_RTT_vprintf_CALLBACK Callback)
{
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)0;
  Mock.SEGGER_RTT_vprintf_CallbackBool = (char)1;
  Mock.SEGGER_RTT_vprintf_CallbackCalls = 0;
  Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer = Callback;
}

int SEGGER_RTT_vprintf_CallCount(void)
{
  return Mock.SEGGER_RTT_vprintf_CallbackCalls;
}

void SEGGER_RTT_vprintf_Stub(CMOCK_SEGGER_RTT_vprintf_CALLBACK Callback)
{
  Mock.SEGGER_RTT_vprintf_IgnoreBool = (char)0;
  Mock.SEGGER_RTT_vprintf_CallbackBool = (char)0;
  Mock.SEGGER_RTT_vprintf_CallbackCalls = 0;
  Mock.SEGGER_RTT_vprintf_CallbackFunctionPointer = Callback;
}

void SEGGER_RTT_vprintf_CMockReturnMemThruPtr_args(UNITY_LINE_TYPE cmock_line, va_list const* args, size_t cmock_size)
{
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_vprintf_CallInstance));
  if (Mock.SEGGER_RTT_vprintf_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_args_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE));
    CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* new_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.SEGGER_RTT_vprintf_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_vprintf_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_args_Used = 1;
  cmock_call_instance->ReturnThruPtr_args_Val = args;
  cmock_call_instance->ReturnThruPtr_args_Size = cmock_size;
}

void SEGGER_RTT_vprintf_CMockIgnoreArg_buffer_index(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_vprintf_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer_index = 1;
}

void SEGGER_RTT_vprintf_CMockIgnoreArg_format(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_vprintf_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_format = 1;
}

void SEGGER_RTT_vprintf_CMockIgnoreArg_args(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_vprintf_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_args = 1;
}

unsigned SEGGER_RTT_WriteString(unsigned buffer_index, const char* text)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SEGGER_RTT_WriteString);
  cmock_call_instance = (CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SEGGER_RTT_WriteString_CallInstance);
  Mock.SEGGER_RTT_WriteString_CallInstance = CMock_Guts_MemNext(Mock.SEGGER_RTT_WriteString_CallInstance);
  if (Mock.SEGGER_RTT_WriteString_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SEGGER_RTT_WriteString_FinalReturn;
    memcpy((void*)(&Mock.SEGGER_RTT_WriteString_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(unsigned[sizeof(cmock_call_instance->ReturnVal) == sizeof(unsigned) ? 1 : -1])); /* add unsigned to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SEGGER_RTT_WriteString_CallbackBool &&
      Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer != NULL)
  {
    unsigned cmock_cb_ret = Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer(buffer_index, text, Mock.SEGGER_RTT_WriteString_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_buffer_index)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_WriteString,CMockString_buffer_index);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_buffer_index, &buffer_index, sizeof(unsigned), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_text)
  {
    UNITY_SET_DETAILS(CMockString_SEGGER_RTT_WriteString,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SEGGER_RTT_WriteString);
    cmock_call_instance->ReturnVal = Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer(buffer_index, text, Mock.SEGGER_RTT_WriteString_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SEGGER_RTT_WriteString(CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance, unsigned buffer_index, const char* text);
void CMockExpectParameters_SEGGER_RTT_WriteString(CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance, unsigned buffer_index, const char* text)
{
  memcpy((void*)(&cmock_call_instance->Expected_buffer_index), (const void*)(&buffer_index),
         sizeof(unsigned[sizeof(buffer_index) == sizeof(unsigned) ? 1 : -1])); /* add unsigned to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_buffer_index = 0;
  cmock_call_instance->Expected_text = text;
  cmock_call_instance->IgnoreArg_text = 0;
}

void SEGGER_RTT_WriteString_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, unsigned cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_WriteString_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_WriteString_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)1;
}

void SEGGER_RTT_WriteString_CMockStopIgnore(void)
{
  if(Mock.SEGGER_RTT_WriteString_IgnoreBool)
    Mock.SEGGER_RTT_WriteString_CallInstance = CMock_Guts_MemNext(Mock.SEGGER_RTT_WriteString_CallInstance);
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)0;
}

void SEGGER_RTT_WriteString_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_WriteString_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_WriteString_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SEGGER_RTT_WriteString_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned buffer_index, const char* text, unsigned cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE));
  CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SEGGER_RTT_WriteString_CallInstance = CMock_Guts_MemChain(Mock.SEGGER_RTT_WriteString_CallInstance, cmock_guts_index);
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SEGGER_RTT_WriteString(cmock_call_instance, buffer_index, text);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(unsigned[sizeof(cmock_to_return) == sizeof(unsigned) ? 1 : -1])); /* add unsigned to :treat_as_array if this causes an error */
}

void SEGGER_RTT_WriteString_AddCallback(CMOCK_SEGGER_RTT_WriteString_CALLBACK Callback)
{
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)0;
  Mock.SEGGER_RTT_WriteString_CallbackBool = (char)1;
  Mock.SEGGER_RTT_WriteString_CallbackCalls = 0;
  Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer = Callback;
}

int SEGGER_RTT_WriteString_CallCount(void)
{
  return Mock.SEGGER_RTT_WriteString_CallbackCalls;
}

void SEGGER_RTT_WriteString_Stub(CMOCK_SEGGER_RTT_WriteString_CALLBACK Callback)
{
  Mock.SEGGER_RTT_WriteString_IgnoreBool = (char)0;
  Mock.SEGGER_RTT_WriteString_CallbackBool = (char)0;
  Mock.SEGGER_RTT_WriteString_CallbackCalls = 0;
  Mock.SEGGER_RTT_WriteString_CallbackFunctionPointer = Callback;
}

void SEGGER_RTT_WriteString_CMockIgnoreArg_buffer_index(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_WriteString_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer_index = 1;
}

void SEGGER_RTT_WriteString_CMockIgnoreArg_text(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE* cmock_call_instance = (CMOCK_SEGGER_RTT_WriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SEGGER_RTT_WriteString_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_text = 1;
}

