/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BMI088_PEER_H
#define _MOCK_BMI088_PEER_H

#include "unity.h"
#include "bmi088_peer.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_bmi088_peer_Init(void);
void mock_bmi088_peer_Destroy(void);
void mock_bmi088_peer_Verify(void);




#define DEV_BMI088_SetGyroBias_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("DEV_BMI088_SetGyroBias requires _Ignore (not AndReturn)");
#define DEV_BMI088_SetGyroBias_Ignore() DEV_BMI088_SetGyroBias_CMockIgnore()
void DEV_BMI088_SetGyroBias_CMockIgnore(void);
#define DEV_BMI088_SetGyroBias_StopIgnore() DEV_BMI088_SetGyroBias_CMockStopIgnore()
void DEV_BMI088_SetGyroBias_CMockStopIgnore(void);
#define DEV_BMI088_SetGyroBias_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("DEV_BMI088_SetGyroBias requires _ExpectAnyArgs (not AndReturn)");
#define DEV_BMI088_SetGyroBias_ExpectAnyArgs() DEV_BMI088_SetGyroBias_CMockExpectAnyArgs(__LINE__)
void DEV_BMI088_SetGyroBias_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DEV_BMI088_SetGyroBias_ExpectAndReturn(imu, bias, cmock_retval) TEST_FAIL_MESSAGE("DEV_BMI088_SetGyroBias requires _Expect (not AndReturn)");
#define DEV_BMI088_SetGyroBias_Expect(imu, bias) DEV_BMI088_SetGyroBias_CMockExpect(__LINE__, imu, bias)
void DEV_BMI088_SetGyroBias_CMockExpect(UNITY_LINE_TYPE cmock_line, DEV_BMI088_s* imu, const float* bias);
typedef void (* CMOCK_DEV_BMI088_SetGyroBias_CALLBACK)(DEV_BMI088_s* imu, const float* bias, int cmock_num_calls);
void DEV_BMI088_SetGyroBias_AddCallback(CMOCK_DEV_BMI088_SetGyroBias_CALLBACK Callback);
void DEV_BMI088_SetGyroBias_Stub(CMOCK_DEV_BMI088_SetGyroBias_CALLBACK Callback);
#define DEV_BMI088_SetGyroBias_StubWithCallback DEV_BMI088_SetGyroBias_Stub
int DEV_BMI088_SetGyroBias_CallCount(void);
#define DEV_BMI088_SetGyroBias_ReturnThruPtr_imu(imu) DEV_BMI088_SetGyroBias_CMockReturnMemThruPtr_imu(__LINE__, imu, sizeof(DEV_BMI088_s))
#define DEV_BMI088_SetGyroBias_ReturnArrayThruPtr_imu(imu, cmock_len) DEV_BMI088_SetGyroBias_CMockReturnMemThruPtr_imu(__LINE__, imu, (cmock_len * sizeof(*imu)))
#define DEV_BMI088_SetGyroBias_ReturnMemThruPtr_imu(imu, cmock_size) DEV_BMI088_SetGyroBias_CMockReturnMemThruPtr_imu(__LINE__, imu, (cmock_size))
void DEV_BMI088_SetGyroBias_CMockReturnMemThruPtr_imu(UNITY_LINE_TYPE cmock_line, DEV_BMI088_s const* imu, size_t cmock_size);
#define DEV_BMI088_SetGyroBias_IgnoreArg_imu() DEV_BMI088_SetGyroBias_CMockIgnoreArg_imu(__LINE__)
void DEV_BMI088_SetGyroBias_CMockIgnoreArg_imu(UNITY_LINE_TYPE cmock_line);
#define DEV_BMI088_SetGyroBias_IgnoreArg_bias() DEV_BMI088_SetGyroBias_CMockIgnoreArg_bias(__LINE__)
void DEV_BMI088_SetGyroBias_CMockIgnoreArg_bias(UNITY_LINE_TYPE cmock_line);
#define DEV_BMI088_GetGyroBias_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("DEV_BMI088_GetGyroBias requires _Ignore (not AndReturn)");
#define DEV_BMI088_GetGyroBias_Ignore() DEV_BMI088_GetGyroBias_CMockIgnore()
void DEV_BMI088_GetGyroBias_CMockIgnore(void);
#define DEV_BMI088_GetGyroBias_StopIgnore() DEV_BMI088_GetGyroBias_CMockStopIgnore()
void DEV_BMI088_GetGyroBias_CMockStopIgnore(void);
#define DEV_BMI088_GetGyroBias_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("DEV_BMI088_GetGyroBias requires _ExpectAnyArgs (not AndReturn)");
#define DEV_BMI088_GetGyroBias_ExpectAnyArgs() DEV_BMI088_GetGyroBias_CMockExpectAnyArgs(__LINE__)
void DEV_BMI088_GetGyroBias_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DEV_BMI088_GetGyroBias_ExpectAndReturn(imu, out, cmock_retval) TEST_FAIL_MESSAGE("DEV_BMI088_GetGyroBias requires _Expect (not AndReturn)");
#define DEV_BMI088_GetGyroBias_Expect(imu, out) DEV_BMI088_GetGyroBias_CMockExpect(__LINE__, imu, out)
void DEV_BMI088_GetGyroBias_CMockExpect(UNITY_LINE_TYPE cmock_line, const DEV_BMI088_s* imu, float* out);
typedef void (* CMOCK_DEV_BMI088_GetGyroBias_CALLBACK)(const DEV_BMI088_s* imu, float* out, int cmock_num_calls);
void DEV_BMI088_GetGyroBias_AddCallback(CMOCK_DEV_BMI088_GetGyroBias_CALLBACK Callback);
void DEV_BMI088_GetGyroBias_Stub(CMOCK_DEV_BMI088_GetGyroBias_CALLBACK Callback);
#define DEV_BMI088_GetGyroBias_StubWithCallback DEV_BMI088_GetGyroBias_Stub
int DEV_BMI088_GetGyroBias_CallCount(void);
#define DEV_BMI088_GetGyroBias_ReturnThruPtr_out(out) DEV_BMI088_GetGyroBias_CMockReturnMemThruPtr_out(__LINE__, out, sizeof(float))
#define DEV_BMI088_GetGyroBias_ReturnArrayThruPtr_out(out, cmock_len) DEV_BMI088_GetGyroBias_CMockReturnMemThruPtr_out(__LINE__, out, (cmock_len * sizeof(*out)))
#define DEV_BMI088_GetGyroBias_ReturnMemThruPtr_out(out, cmock_size) DEV_BMI088_GetGyroBias_CMockReturnMemThruPtr_out(__LINE__, out, (cmock_size))
void DEV_BMI088_GetGyroBias_CMockReturnMemThruPtr_out(UNITY_LINE_TYPE cmock_line, float const* out, size_t cmock_size);
#define DEV_BMI088_GetGyroBias_IgnoreArg_imu() DEV_BMI088_GetGyroBias_CMockIgnoreArg_imu(__LINE__)
void DEV_BMI088_GetGyroBias_CMockIgnoreArg_imu(UNITY_LINE_TYPE cmock_line);
#define DEV_BMI088_GetGyroBias_IgnoreArg_out() DEV_BMI088_GetGyroBias_CMockIgnoreArg_out(__LINE__)
void DEV_BMI088_GetGyroBias_CMockIgnoreArg_out(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
