/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_bmi088_peer.h"

static const char* CMockString_DEV_BMI088_GetGyroBias = "DEV_BMI088_GetGyroBias";
static const char* CMockString_DEV_BMI088_SetGyroBias = "DEV_BMI088_SetGyroBias";
static const char* CMockString_bias = "bias";
static const char* CMockString_imu = "imu";
static const char* CMockString_out = "out";

typedef struct _CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  DEV_BMI088_s* Expected_imu;
  const float* Expected_bias;
  char ReturnThruPtr_imu_Used;
  DEV_BMI088_s const* ReturnThruPtr_imu_Val;
  size_t ReturnThruPtr_imu_Size;
  char IgnoreArg_imu;
  char IgnoreArg_bias;

} CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE;

typedef struct _CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  const DEV_BMI088_s* Expected_imu;
  float* Expected_out;
  char ReturnThruPtr_out_Used;
  float const* ReturnThruPtr_out_Val;
  size_t ReturnThruPtr_out_Size;
  char IgnoreArg_imu;
  char IgnoreArg_out;

} CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE;

static struct mock_bmi088_peerInstance
{
  char DEV_BMI088_SetGyroBias_IgnoreBool;
  char DEV_BMI088_SetGyroBias_CallbackBool;
  CMOCK_DEV_BMI088_SetGyroBias_CALLBACK DEV_BMI088_SetGyroBias_CallbackFunctionPointer;
  int DEV_BMI088_SetGyroBias_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE DEV_BMI088_SetGyroBias_CallInstance;
  char DEV_BMI088_GetGyroBias_IgnoreBool;
  char DEV_BMI088_GetGyroBias_CallbackBool;
  CMOCK_DEV_BMI088_GetGyroBias_CALLBACK DEV_BMI088_GetGyroBias_CallbackFunctionPointer;
  int DEV_BMI088_GetGyroBias_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE DEV_BMI088_GetGyroBias_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_bmi088_peer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.DEV_BMI088_SetGyroBias_CallInstance;
  if (Mock.DEV_BMI088_SetGyroBias_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_DEV_BMI088_SetGyroBias);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.DEV_BMI088_GetGyroBias_CallInstance;
  if (Mock.DEV_BMI088_GetGyroBias_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_DEV_BMI088_GetGyroBias);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_bmi088_peer_Init(void)
{
  mock_bmi088_peer_Destroy();
}

void mock_bmi088_peer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void DEV_BMI088_SetGyroBias(DEV_BMI088_s* imu, const float* bias)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_DEV_BMI088_SetGyroBias);
  cmock_call_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.DEV_BMI088_SetGyroBias_CallInstance);
  Mock.DEV_BMI088_SetGyroBias_CallInstance = CMock_Guts_MemNext(Mock.DEV_BMI088_SetGyroBias_CallInstance);
  if (Mock.DEV_BMI088_SetGyroBias_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_imu_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(imu, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)imu, (const void*)cmock_call_instance->ReturnThruPtr_imu_Val,
      cmock_call_instance->ReturnThruPtr_imu_Size);
  }
  if (Mock.DEV_BMI088_SetGyroBias_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.DEV_BMI088_SetGyroBias_CallbackBool &&
      Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer != NULL)
  {
    Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer(imu, bias, Mock.DEV_BMI088_SetGyroBias_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_imu)
  {
    UNITY_SET_DETAILS(CMockString_DEV_BMI088_SetGyroBias,CMockString_imu);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_imu, imu, sizeof(DEV_BMI088_s), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_bias)
  {
    UNITY_SET_DETAILS(CMockString_DEV_BMI088_SetGyroBias,CMockString_bias);
    if (cmock_call_instance->Expected_bias == NULL)
      { UNITY_TEST_ASSERT_NULL(bias, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY(cmock_call_instance->Expected_bias, bias, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_DEV_BMI088_SetGyroBias);
    Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer(imu, bias, Mock.DEV_BMI088_SetGyroBias_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_imu_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(imu, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)imu, (const void*)cmock_call_instance->ReturnThruPtr_imu_Val,
      cmock_call_instance->ReturnThruPtr_imu_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_DEV_BMI088_SetGyroBias(CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance, DEV_BMI088_s* imu, const float* bias);
void CMockExpectParameters_DEV_BMI088_SetGyroBias(CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance, DEV_BMI088_s* imu, const float* bias)
{
  cmock_call_instance->Expected_imu = imu;
  cmock_call_instance->IgnoreArg_imu = 0;
  cmock_call_instance->ReturnThruPtr_imu_Used = 0;
  cmock_call_instance->Expected_bias = bias;
  cmock_call_instance->IgnoreArg_bias = 0;
}

void DEV_BMI088_SetGyroBias_CMockIgnore(void)
{
  Mock.DEV_BMI088_SetGyroBias_IgnoreBool = (char)1;
}

void DEV_BMI088_SetGyroBias_CMockStopIgnore(void)
{
  Mock.DEV_BMI088_SetGyroBias_IgnoreBool = (char)0;
}

void DEV_BMI088_SetGyroBias_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE));
  CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DEV_BMI088_SetGyroBias_CallInstance = CMock_Guts_MemChain(Mock.DEV_BMI088_SetGyroBias_CallInstance, cmock_guts_index);
  Mock.DEV_BMI088_SetGyroBias_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void DEV_BMI088_SetGyroBias_CMockExpect(UNITY_LINE_TYPE cmock_line, DEV_BMI088_s* imu, const float* bias)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE));
  CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DEV_BMI088_SetGyroBias_CallInstance = CMock_Guts_MemChain(Mock.DEV_BMI088_SetGyroBias_CallInstance, cmock_guts_index);
  Mock.DEV_BMI088_SetGyroBias_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_DEV_BMI088_SetGyroBias(cmock_call_instance, imu, bias);
}

void DEV_BMI088_SetGyroBias_AddCallback(CMOCK_DEV_BMI088_SetGyroBias_CALLBACK Callback)
{
  Mock.DEV_BMI088_SetGyroBias_IgnoreBool = (char)0;
  Mock.DEV_BMI088_SetGyroBias_CallbackBool = (char)1;
  Mock.DEV_BMI088_SetGyroBias_CallbackCalls = 0;
  Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer = Callback;
}

int DEV_BMI088_SetGyroBias_CallCount(void)
{
  return Mock.DEV_BMI088_SetGyroBias_CallbackCalls;
}

void DEV_BMI088_SetGyroBias_Stub(CMOCK_DEV_BMI088_SetGyroBias_CALLBACK Callback)
{
  Mock.DEV_BMI088_SetGyroBias_IgnoreBool = (char)0;
  Mock.DEV_BMI088_SetGyroBias_CallbackBool = (char)0;
  Mock.DEV_BMI088_SetGyroBias_CallbackCalls = 0;
  Mock.DEV_BMI088_SetGyroBias_CallbackFunctionPointer = Callback;
}

void DEV_BMI088_SetGyroBias_CMockReturnMemThruPtr_imu(UNITY_LINE_TYPE cmock_line, DEV_BMI088_s const* imu, size_t cmock_size)
{
  CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DEV_BMI088_SetGyroBias_CallInstance));
  if (Mock.DEV_BMI088_SetGyroBias_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_imu_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE));
    CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* new_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    Mock.DEV_BMI088_SetGyroBias_CallInstance = CMock_Guts_MemChain(Mock.DEV_BMI088_SetGyroBias_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_imu_Used = 1;
  cmock_call_instance->ReturnThruPtr_imu_Val = imu;
  cmock_call_instance->ReturnThruPtr_imu_Size = cmock_size;
}

void DEV_BMI088_SetGyroBias_CMockIgnoreArg_imu(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DEV_BMI088_SetGyroBias_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_imu = 1;
}

void DEV_BMI088_SetGyroBias_CMockIgnoreArg_bias(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_SetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DEV_BMI088_SetGyroBias_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bias = 1;
}

void DEV_BMI088_GetGyroBias(const DEV_BMI088_s* imu, float* out)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_DEV_BMI088_GetGyroBias);
  cmock_call_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.DEV_BMI088_GetGyroBias_CallInstance);
  Mock.DEV_BMI088_GetGyroBias_CallInstance = CMock_Guts_MemNext(Mock.DEV_BMI088_GetGyroBias_CallInstance);
  if (Mock.DEV_BMI088_GetGyroBias_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_out_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(out, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)out, (const void*)cmock_call_instance->ReturnThruPtr_out_Val,
      cmock_call_instance->ReturnThruPtr_out_Size);
  }
  if (Mock.DEV_BMI088_GetGyroBias_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.DEV_BMI088_GetGyroBias_CallbackBool &&
      Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer != NULL)
  {
    Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer(imu, out, Mock.DEV_BMI088_GetGyroBias_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_imu)
  {
    UNITY_SET_DETAILS(CMockString_DEV_BMI088_GetGyroBias,CMockString_imu);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_imu, imu, sizeof(const DEV_BMI088_s), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_out)
  {
    UNITY_SET_DETAILS(CMockString_DEV_BMI088_GetGyroBias,CMockString_out);
    if (cmock_call_instance->Expected_out == NULL)
      { UNITY_TEST_ASSERT_NULL(out, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY(cmock_call_instance->Expected_out, out, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_DEV_BMI088_GetGyroBias);
    Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer(imu, out, Mock.DEV_BMI088_GetGyroBias_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_out_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(out, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)out, (const void*)cmock_call_instance->ReturnThruPtr_out_Val,
      cmock_call_instance->ReturnThruPtr_out_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_DEV_BMI088_GetGyroBias(CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance, const DEV_BMI088_s* imu, float* out);
void CMockExpectParameters_DEV_BMI088_GetGyroBias(CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance, const DEV_BMI088_s* imu, float* out)
{
  cmock_call_instance->Expected_imu = imu;
  cmock_call_instance->IgnoreArg_imu = 0;
  cmock_call_instance->Expected_out = out;
  cmock_call_instance->IgnoreArg_out = 0;
  cmock_call_instance->ReturnThruPtr_out_Used = 0;
}

void DEV_BMI088_GetGyroBias_CMockIgnore(void)
{
  Mock.DEV_BMI088_GetGyroBias_IgnoreBool = (char)1;
}

void DEV_BMI088_GetGyroBias_CMockStopIgnore(void)
{
  Mock.DEV_BMI088_GetGyroBias_IgnoreBool = (char)0;
}

void DEV_BMI088_GetGyroBias_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE));
  CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DEV_BMI088_GetGyroBias_CallInstance = CMock_Guts_MemChain(Mock.DEV_BMI088_GetGyroBias_CallInstance, cmock_guts_index);
  Mock.DEV_BMI088_GetGyroBias_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void DEV_BMI088_GetGyroBias_CMockExpect(UNITY_LINE_TYPE cmock_line, const DEV_BMI088_s* imu, float* out)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE));
  CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DEV_BMI088_GetGyroBias_CallInstance = CMock_Guts_MemChain(Mock.DEV_BMI088_GetGyroBias_CallInstance, cmock_guts_index);
  Mock.DEV_BMI088_GetGyroBias_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_DEV_BMI088_GetGyroBias(cmock_call_instance, imu, out);
}

void DEV_BMI088_GetGyroBias_AddCallback(CMOCK_DEV_BMI088_GetGyroBias_CALLBACK Callback)
{
  Mock.DEV_BMI088_GetGyroBias_IgnoreBool = (char)0;
  Mock.DEV_BMI088_GetGyroBias_CallbackBool = (char)1;
  Mock.DEV_BMI088_GetGyroBias_CallbackCalls = 0;
  Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer = Callback;
}

int DEV_BMI088_GetGyroBias_CallCount(void)
{
  return Mock.DEV_BMI088_GetGyroBias_CallbackCalls;
}

void DEV_BMI088_GetGyroBias_Stub(CMOCK_DEV_BMI088_GetGyroBias_CALLBACK Callback)
{
  Mock.DEV_BMI088_GetGyroBias_IgnoreBool = (char)0;
  Mock.DEV_BMI088_GetGyroBias_CallbackBool = (char)0;
  Mock.DEV_BMI088_GetGyroBias_CallbackCalls = 0;
  Mock.DEV_BMI088_GetGyroBias_CallbackFunctionPointer = Callback;
}

void DEV_BMI088_GetGyroBias_CMockReturnMemThruPtr_out(UNITY_LINE_TYPE cmock_line, float const* out, size_t cmock_size)
{
  CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DEV_BMI088_GetGyroBias_CallInstance));
  if (Mock.DEV_BMI088_GetGyroBias_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_out_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE));
    CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* new_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    Mock.DEV_BMI088_GetGyroBias_CallInstance = CMock_Guts_MemChain(Mock.DEV_BMI088_GetGyroBias_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_out_Used = 1;
  cmock_call_instance->ReturnThruPtr_out_Val = out;
  cmock_call_instance->ReturnThruPtr_out_Size = cmock_size;
}

void DEV_BMI088_GetGyroBias_CMockIgnoreArg_imu(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DEV_BMI088_GetGyroBias_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_imu = 1;
}

void DEV_BMI088_GetGyroBias_CMockIgnoreArg_out(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE* cmock_call_instance = (CMOCK_DEV_BMI088_GetGyroBias_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DEV_BMI088_GetGyroBias_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_out = 1;
}

